<?php
include('../config.php');
$pagegen=new page_gen();$pagegen->round_to=4;$pagegen->start();
$s=new Game();if(!$s->loggedIn||!isset($_GET['time'])){header('Location: ../index.php');exit;}$db=$s->db_link;$uid=(int)$_SESSION['userid'];
function comm_h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function comm_boot(mysqli $db):void{
 $db->query("CREATE TABLE IF NOT EXISTS guild_channels (channel_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,guild_id INT NOT NULL,channel_name VARCHAR(80) NOT NULL,channel_topic VARCHAR(180) NOT NULL DEFAULT '',is_archived TINYINT(1) NOT NULL DEFAULT 0,created_by INT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(channel_id),UNIQUE KEY uq_guild_channel(guild_id,channel_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->query("CREATE TABLE IF NOT EXISTS guild_messages (guild_message_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,channel_id BIGINT UNSIGNED NOT NULL,guild_id INT NOT NULL,from_uid INT NOT NULL,body TEXT NOT NULL,is_deleted TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(guild_message_id),KEY idx_guild_messages_channel(channel_id,guild_message_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->query("CREATE TABLE IF NOT EXISTS guild_message_reads (channel_id BIGINT UNSIGNED NOT NULL,uid INT NOT NULL,last_read_message_id BIGINT UNSIGNED NOT NULL DEFAULT 0,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(channel_id,uid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->query("CREATE TABLE IF NOT EXISTS message_preferences (uid INT NOT NULL PRIMARY KEY,allow_private_messages TINYINT(1) NOT NULL DEFAULT 1,allow_guild_messages TINYINT(1) NOT NULL DEFAULT 1,muted_until DATETIME NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->query("CREATE TABLE IF NOT EXISTS communication_moderation (moderation_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,guild_id INT NULL,message_type ENUM('private','guild') NOT NULL,message_id BIGINT UNSIGNED NOT NULL,moderator_uid INT NOT NULL,action_type ENUM('hide','restore','mute') NOT NULL,reason VARCHAR(255) NOT NULL DEFAULT '',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(moderation_id),KEY idx_comm_mod_message(message_type,message_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}
comm_boot($db);$u=$db->query('SELECT uname,allyid FROM users WHERE uid='.$uid.' LIMIT 1')->fetch_assoc();$guild=(int)($u['allyid']??0);$action=(string)($_REQUEST['atype']??'inbox');$notice='';$error='';
if(empty($_SESSION['comm_csrf']))$_SESSION['comm_csrf']=bin2hex(random_bytes(16));$csrf=$_SESSION['comm_csrf'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf']??''))){$error='Security validation failed. Refresh and retry.';}
 elseif($action==='send_pm'){$to=(int)($_POST['to_uid']??0);$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));if($to<=0||$to===$uid||$body==='')$error='Choose another player and enter a message.';else{$q=$db->prepare('SELECT uid FROM users WHERE uid=? LIMIT 1');$q->bind_param('i',$to);$q->execute();if(!$q->get_result()->fetch_assoc())$error='Recipient not found.';else{$subject=$subject?:'(no subject)';$time=date('Y-m-d H:i:s');$st=$db->prepare('INSERT INTO messages (fromUID,toUID,subject,message,timeSent,isRead,isDeleted,replyToMid) VALUES (?,?,?,?,?,0,0,0)');$st->bind_param('iisss',$uid,$to,$subject,$body,$time);$st->execute();$notice='Private message sent.';$action='inbox';}}}
 elseif($action==='send_guild'){$body=trim((string)($_POST['body']??''));$channel=(int)($_POST['channel_id']??0);if($guild<=0)$error='You are not assigned to a guild.';elseif($body==='')$error='Guild message cannot be empty.';else{$q=$db->prepare('SELECT channel_id FROM guild_channels WHERE channel_id=? AND guild_id=? AND is_archived=0 LIMIT 1');$q->bind_param('ii',$channel,$guild);$q->execute();if(!$q->get_result()->fetch_assoc())$error='Guild channel not found.';else{$st=$db->prepare('INSERT INTO guild_messages (channel_id,guild_id,from_uid,body) VALUES (?,?,?,?)');$st->bind_param('iiis',$channel,$guild,$uid,$body);$st->execute();$notice='Guild message posted.';$action='guild';}}}
}
if($guild>0){$db->query("INSERT IGNORE INTO guild_channels (guild_id,channel_name,channel_topic,created_by) VALUES ($guild,'Command Channel','Guild command and operations',$uid),($guild,'General','Guild-wide discussion',$uid)");}
$unread=(int)($db->query('SELECT COUNT(*) c FROM messages WHERE toUID='.$uid.' AND isRead=0 AND isDeleted=0')->fetch_assoc()['c']??0);
$channels=$guild>0?$db->query('SELECT * FROM guild_channels WHERE guild_id='.$guild.' AND is_archived=0 ORDER BY channel_id'):false;
echo '<style>.comm-shell{max-width:900px}.comm-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0 16px}.comm-tabs a,.comm-btn{background:#062b46;color:#9feaff;border:1px solid #167ea4;padding:7px 12px;text-decoration:none;cursor:pointer}.comm-tabs a.active,.comm-tabs a:hover,.comm-btn:hover{background:#0a5574;color:#fff}.comm-card{background:rgba(3,20,35,.8);border:1px solid #14516b;padding:14px;margin:10px 0}.comm-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.comm-card input,.comm-card textarea,.comm-card select{width:100%;box-sizing:border-box;background:#061a29;color:#d9f7ff;border:1px solid #21627b;padding:8px}.comm-msg{padding:10px;border-bottom:1px solid #16485d}.comm-unread{border-left:3px solid #28d7ff}.comm-meta{color:#75b8cc;font-size:.85em}.comm-alert{padding:10px;border:1px solid #25a7cf;background:#082c43}.comm-error{border-color:#c45a61;color:#ffb6bd}@media(max-width:650px){.comm-grid{grid-template-columns:1fr}}</style><div class="comm-shell"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // COMMUNICATIONS</span><h3>Private and Guild Communications</h3><p>Coordinate your civilization, issue private orders, and keep guild operations synchronized.</p></div>';
if($notice)echo '<div class="comm-alert">'.comm_h($notice).'</div>';if($error)echo '<div class="comm-alert comm-error">'.comm_h($error).'</div>';
echo '<nav class="comm-tabs"><a class="'.($action==='inbox'?'active':''). '" href="javascript:void(0)" onclick="sendData(\'communications\',\'get\',\'mainDisplay\',\'inbox\')">Inbox'.($unread?' <b>('.$unread.')</b>':'').'</a><a class="'.($action==='compose'?'active':'').'" href="javascript:void(0)" onclick="sendData(\'communications\',\'get\',\'mainDisplay\',\'compose\')">Private Message</a><a class="'.($action==='guild'?'active':'').'" href="javascript:void(0)" onclick="sendData(\'communications\',\'get\',\'mainDisplay\',\'guild\')">Guild Channel</a><a href="javascript:void(0)" onclick="sendData(\'messages\',\'get\',\'mainDisplay\',\'inbox\')">Legacy Message Center</a></nav>';
if($action==='compose'){echo '<section class="comm-card"><h4>Send Private Message</h4><form method="post" action="modules/communications.php?time='.time().'&atype=send_pm"><input type="hidden" name="csrf" value="'.comm_h($csrf).'"/><label>Recipient UID<input type="number" name="to_uid" min="1" required></label><label>Subject<input name="subject" maxlength="255"></label><label>Message<textarea name="body" rows="8" maxlength="5000" required></textarea></label><button class="comm-btn">Transmit Message</button></form></section>';
}elseif($action==='guild'){if($guild<=0)echo '<section class="comm-card"><h4>No Guild Assignment</h4><p>Join or create a guild before using guild communications.</p></section>';else{$rows=$db->query('SELECT gm.*,u.uname,c.channel_name FROM guild_messages gm INNER JOIN users u ON u.uid=gm.from_uid INNER JOIN guild_channels c ON c.channel_id=gm.channel_id WHERE gm.guild_id='.$guild.' AND gm.is_deleted=0 ORDER BY gm.guild_message_id DESC LIMIT 80');echo '<div class="comm-grid"><section class="comm-card"><h4>Guild Channels</h4>';while($c=$channels->fetch_assoc())echo '<p><b>'.comm_h($c['channel_name']).'</b><br><span class="comm-meta">'.comm_h($c['channel_topic']).'</span></p>';echo '</section><section class="comm-card"><h4>Post to Guild</h4><form method="post" action="modules/communications.php?time='.time().'&atype=send_guild"><input type="hidden" name="csrf" value="'.comm_h($csrf).'"/><label>Channel<select name="channel_id" required>'; $channels2=$db->query('SELECT channel_id,channel_name FROM guild_channels WHERE guild_id='.$guild.' AND is_archived=0');while($c=$channels2->fetch_assoc())echo '<option value="'.(int)$c['channel_id'].'">'.comm_h($c['channel_name']).'</option>';echo '</select></label><label>Message<textarea name="body" rows="5" maxlength="5000" required></textarea></label><button class="comm-btn">Post Guild Message</button></form></section></div><section class="comm-card"><h4>Guild Channel History</h4>';while($r=$rows->fetch_assoc())echo '<div class="comm-msg"><b>'.comm_h($r['uname']).'</b> <span class="comm-meta">'.comm_h($r['channel_name']).' · '.comm_h($r['created_at']).'</span><div>'.nl2br(comm_h($r['body'])).'</div></div>';echo '</section>';}}
else{$rows=$db->query('SELECT m.*,u.uname sender FROM messages m INNER JOIN users u ON u.uid=m.fromUID WHERE m.toUID='.$uid.' AND m.isDeleted=0 ORDER BY m.mid DESC LIMIT 80');echo '<section class="comm-card"><h4>Private Inbox</h4>';if(!$rows||$rows->num_rows===0)echo '<p>No private messages.</p>';else while($r=$rows->fetch_assoc())echo '<div class="comm-msg '.(!(int)$r['isRead']?'comm-unread':'').'">'.(!(int)$r['isRead']?'<b>UNREAD </b>':'').'<b>'.comm_h($r['sender']).'</b> · '.comm_h($r['timeSent']).'<br><a href="javascript:void(0)" onclick="sendData(\'messages\',\'get\',\''.((int)$r['mid']).'\',\'read\')">'.comm_h($r['subject']).'</a></div>';echo '</section>';}
echo '</div>'; $pagegen->stop();print('page generation time: '.$pagegen->gen());
?>
