<?php
include('../config.php');
require_once __DIR__ . '/../base/FleetPolicy.class.php';
require_once __DIR__ . '/../base/ModuleFittingPolicy.class.php';
$pagegen=new page_gen();$pagegen->round_to=4;$pagegen->start();$game=new Game();
if(!$game->loggedIn||!isset($_GET['time'])){header('Location: ../index.php');exit;}
$blueprints=FleetPolicy::BLUEPRINTS;$modules=ModuleFittingPolicy::MODULES;$h=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$moduleData=[];foreach($modules as $key=>$module)$moduleData[$key]=['name'=>$module['name'],'slot'=>$module['slot'],'power_grid'=>(int)$module['power_grid'],'cpu'=>(int)$module['cpu'],'capacitor'=>(int)$module['capacitor'],'attack'=>(int)$module['attack'],'defense'=>(int)$module['defense'],'capacity'=>(int)$module['capacity']];
$blueprintData=[];foreach($blueprints as $key=>$blueprint)$blueprintData[$key]=['name'=>$blueprint['name'],'attack'=>(int)$blueprint['attack'],'defense'=>(int)$blueprint['defense'],'capacity'=>(int)$blueprint['capacity'],'high_slots'=>(int)$blueprint['high_slots'],'medium_slots'=>(int)$blueprint['medium_slots'],'low_slots'=>(int)$blueprint['low_slots'],'power_grid'=>(int)$blueprint['power_grid'],'sensor'=>(int)$blueprint['sensor'],'capacitor'=>(int)$blueprint['capacitor']];
echo '<div class="comm-shell fitting-simulator"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // FITTING LAB</span><h3>Visual Ship Fitting Simulator</h3><p>Test a blueprint and module layout before committing a fleet to construction or deployment. The simulator uses the same slot and fitting rules as the server.</p></div><div class="fit-sim-grid"><section class="comm-card"><h4>Hull Selection</h4><label>Blueprint<select id="fit-hull">';foreach($blueprints as $key=>$blueprint)echo '<option value="'.$h($key).'">'.$h($blueprint['name']).' · T'.(int)$blueprint['tier'].'</option>';echo '</select></label><div id="fit-hull-specs" class="fit-spec-grid"></div></section><section class="comm-card"><h4>Fitting Layout</h4><div class="fit-slot-columns">';foreach(['high'=>'High Slots · Weapons','medium'=>'Medium Slots · Shields / EW','low'=>'Low Slots · Armor / Logistics'] as $slot=>$label){echo '<div class="fit-slot-group" data-slot-group="'.$slot.'"><h5>'.$h($label).'</h5>';foreach($modules as $key=>$module)if($module['slot']===$slot)echo '<label class="fit-module-row"><span>'.$h($module['name']).'</span><input class="fit-module" data-module="'.$h($key).'" type="number" min="0" max="20" value="0"></label>';echo '</div>';}echo '</div></section><section class="comm-card fit-summary-card"><h4>Live Fitting Report</h4><div id="fit-status" class="fit-status"></div><div id="fit-summary" class="fit-stat-list"></div><p class="market-note">A fitting is valid only when slot counts, power grid, CPU, and capacitor remain within the selected hull limits.</p></section></div></div>';
echo '<script>(function(){const hulls='.json_encode($blueprintData,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).',modules='.json_encode($moduleData,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP).';const hull=document.getElementById("fit-hull"),status=document.getElementById("fit-status"),summary=document.getElementById("fit-summary"),specs=document.getElementById("fit-hull-specs");function render(){const b=hulls[hull.value],fit={high:0,medium:0,low:0,power_grid:0,cpu:0,capacitor:0,attack:b.attack,defense:b.defense,capacity:b.capacity};document.querySelectorAll(".fit-module").forEach(input=>{const q=Math.max(0,Math.min(20,parseInt(input.value||0,10))),m=modules[input.dataset.module];if(!m||!q)return;fit[m.slot]+=q;fit.power_grid+=m.power_grid*q;fit.cpu+=m.cpu*q;fit.capacitor+=m.capacitor*q;fit.attack+=m.attack*q;fit.defense+=m.defense*q;fit.capacity+=m.capacity*q;});const errors=[];if(fit.high>b.high_slots)errors.push("High slots exceeded");if(fit.medium>b.medium_slots)errors.push("Medium slots exceeded");if(fit.low>b.low_slots)errors.push("Low slots exceeded");if(fit.power_grid>b.power_grid)errors.push("Power grid exceeded");if(fit.cpu>b.sensor)errors.push("CPU exceeded");if(fit.capacitor>b.capacitor)errors.push("Capacitor exceeded");status.className="fit-status "+(errors.length?"fit-invalid":"fit-valid");status.textContent=errors.length?"INVALID FIT · "+errors.join(" · "):"VALID FIT · Ready for deployment review";specs.innerHTML="<span>Slots H/M/L: "+b.high_slots+" / "+b.medium_slots+" / "+b.low_slots+"</span><span>PG/CPU/Cap: "+b.power_grid+" / "+b.sensor+" / "+b.capacitor+"</span>";summary.innerHTML="<span>Attack <b>"+fit.attack+"</b></span><span>Defense <b>"+fit.defense+"</b></span><span>Capacity <b>"+fit.capacity+"</b></span><span>Slots used <b>"+fit.high+" / "+fit.medium+" / "+fit.low+"</b></span><span>Grid used <b>"+fit.power_grid+" / "+b.power_grid+"</b></span><span>CPU used <b>"+fit.cpu+" / "+b.sensor+"</b></span><span>Cap used <b>"+fit.capacitor+" / "+b.capacitor+"</b></span>";}hull.addEventListener("change",render);document.querySelectorAll(".fit-module").forEach(i=>i.addEventListener("input",render));render();})();</script>';
$pagegen->stop();print('page generation time: '.$pagegen->gen());
?>
