<?php
include('../config.php');
require_once __DIR__.'/../base/LeaderboardPolicy.class.php';
require_once __DIR__.'/../base/PvPRankingPolicy.class.php';
$pagegen=new page_gen();$pagegen->round_to=4;$pagegen->start();$s=new Game();
if(!$s->loggedIn||!isset($_GET['time'])){header('Location: ../index.php');exit;}
$db=$s->db_link;$uid=(int)$_SESSION['userid'];$board=(string)($_GET['board']??'territory_power');if(!LeaderboardPolicy::validBoard($board))$board='territory_power';
$db->query("CREATE TABLE IF NOT EXISTS pvp_rankings (season_code VARCHAR(32) NOT NULL,uid INT NOT NULL,rating INT NOT NULL DEFAULT 1000,wins INT UNSIGNED NOT NULL DEFAULT 0,losses INT UNSIGNED NOT NULL DEFAULT 0,draws INT UNSIGNED NOT NULL DEFAULT 0,points_for BIGINT UNSIGNED NOT NULL DEFAULT 0,points_against BIGINT UNSIGNED NOT NULL DEFAULT 0,last_battle_at DATETIME NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(season_code,uid),KEY idx_pvp_rankings_board(season_code,rating,wins,uid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$season=PvPRankingPolicy::SEASON_CODE;$rows=null;$my=null;
if($board==='pvp_ranked'){$rows=$db->query("SELECT r.*,u.uname FROM pvp_rankings r LEFT JOIN users u ON u.uid=r.uid WHERE r.season_code='".$db->real_escape_string($season)."' ORDER BY r.rating DESC,r.wins DESC,r.uid ASC LIMIT 50");$myQ=$db->query("SELECT r.*,1+(SELECT COUNT(*) FROM pvp_rankings x WHERE x.season_code=r.season_code AND (x.rating>r.rating OR (x.rating=r.rating AND x.wins>r.wins))) AS rank_position FROM pvp_rankings r WHERE r.season_code='".$db->real_escape_string($season)."' AND r.uid=$uid LIMIT 1");$my=$myQ?$myQ->fetch_assoc():null;}else{$rows=$db->query("SELECT subject_type,subject_id,score,rank_position,captured_at FROM leaderboard_snapshots WHERE board_key='".$db->real_escape_string($board)."' ORDER BY rank_position ASC,captured_at DESC LIMIT 50");}
$ach=$db->query("SELECT d.name,d.description,d.target_value,COALESCE(p.progress_value,0) progress_value,p.unlocked_at FROM achievement_definitions d LEFT JOIN achievement_progress p ON p.achievement_key=d.achievement_key AND p.uid=$uid ORDER BY d.achievement_key");
echo '<div class="comm-shell"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // RECORDS</span><h3>Leaderboards and Achievements</h3><p>Track the commanders, corporations, territories, fleets, and ranked PvP champions shaping the current season.</p></div>';
echo '<section class="comm-card"><h4>Leaderboard</h4><p><a href="modules/leaderboards.php?time='.time().'&board=pvp_ranked">Ranked PvP Season</a> · <a href="modules/leaderboards.php?time='.time().'&board=territory_power">Territory Power</a> · <a href="modules/leaderboards.php?time='.time().'&board=guild_power">Guild Power</a> · <a href="modules/leaderboards.php?time='.time().'&board=member_contribution">Member Contribution</a> · <a href="modules/leaderboards.php?time='.time().'&board=member_fleet">Member Fleet</a></p>';
if($board==='pvp_ranked'){$rank=0;echo '<div class="ranking-hero"><strong>Season '.htmlspecialchars($season,ENT_QUOTES,'UTF-8').'</strong><span>Commander divisions · ELO rating · ranked battle record</span></div>';if($my)echo '<div class="ranking-self"><b>Your standing: #'.(int)$my['rank_position'].'</b><span>'.htmlspecialchars(PvPRankingPolicy::division((int)$my['rating']),ENT_QUOTES,'UTF-8').' · '.(int)$my['rating'].' rating · '.(int)$my['wins'].'W / '.(int)$my['losses'].'L / '.(int)$my['draws'].'D</span></div>';echo '<div class="admin-table-wrap"><table><tr><th>Rank</th><th>Commander</th><th>Division</th><th>Rating</th><th>Record</th><th>Battle Power</th></tr>';if($rows)while($r=$rows->fetch_assoc())echo '<tr><td>#'.(++$rank).'</td><td>'.htmlspecialchars($r['uname']?:'Commander #'.$r['uid'],ENT_QUOTES,'UTF-8').'</td><td>'.htmlspecialchars(PvPRankingPolicy::division((int)$r['rating']),ENT_QUOTES,'UTF-8').'</td><td>'.number_format((int)$r['rating']).'</td><td>'.(int)$r['wins'].'W / '.(int)$r['losses'].'L / '.(int)$r['draws'].'D</td><td>'.number_format((int)$r['points_for']).' / '.number_format((int)$r['points_against']).'</td></tr>';echo '</table></div>';}else{echo '<div class="admin-table-wrap"><table><tr><th>Rank</th><th>Subject</th><th>Score</th><th>Captured</th></tr>';if($rows)while($r=$rows->fetch_assoc())echo '<tr><td>#'.(int)$r['rank_position'].'</td><td>'.htmlspecialchars($r['subject_type'].' #'.$r['subject_id'],ENT_QUOTES,'UTF-8').'</td><td>'.number_format((int)$r['score']).'</td><td>'.htmlspecialchars($r['captured_at'],ENT_QUOTES,'UTF-8').'</td></tr>';echo '</table></div>';}echo '</section>';
echo '<section class="comm-card"><h4>Achievements</h4><div class="admin-table-wrap"><table><tr><th>Achievement</th><th>Progress</th><th>Status</th><th>Description</th></tr>';if($ach)while($a=$ach->fetch_assoc())echo '<tr><td>'.htmlspecialchars($a['name'],ENT_QUOTES,'UTF-8').'</td><td>'.number_format((int)$a['progress_value']).' / '.number_format((int)$a['target_value']).'</td><td>'.($a['unlocked_at']?'Unlocked':'In progress').'</td><td>'.htmlspecialchars($a['description'],ENT_QUOTES,'UTF-8').'</td></tr>';echo '</table></div></section></div>';$pagegen->stop();print('page generation time: '.$pagegen->gen()); ?>
