<?php
include('../config.php');
require_once __DIR__ . '/../base/NotificationPolicy.class.php';
$pagegen=new page_gen();$pagegen->round_to=4;$pagegen->start();$s=new Game();
if(!$s->loggedIn||!isset($_GET['time'])){header('Location: ../index.php');exit;}
$db=$s->db_link;$uid=(int)$_SESSION['userid'];NotificationPolicy::ensureTable($db);
$gq=$db->query("SELECT allyid FROM users WHERE uid=$uid LIMIT 1");$guildId=(int)(($gq&&$gq->num_rows)?$gq->fetch_assoc()['allyid']:0);
if(empty($_SESSION['notify_csrf']))$_SESSION['notify_csrf']=bin2hex(random_bytes(16));$csrf=$_SESSION['notify_csrf'];$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($csrf,(string)($_POST['csrf']??'')))$error='Security validation failed.';
    else{
        $action=(string)($_POST['notification_action']??'');
        if($action==='read'){$id=(int)($_POST['notification_id']??0);$db->query("UPDATE guild_notifications n INNER JOIN guild_members m ON m.guild_id=n.guild_id AND m.uid=$uid SET n.status='read' WHERE n.notification_id=$id LIMIT 1");$notice='Guild notification marked read.';}
        elseif($action==='player_read'){$id=(int)($_POST['player_notification_id']??0);$db->query("UPDATE player_notifications SET is_read=1 WHERE notification_id=$id AND uid=$uid LIMIT 1");$notice='Player notification marked read.';}
        elseif($action==='player_read_all'){$db->query("UPDATE player_notifications SET is_read=1 WHERE uid=$uid AND is_read=0");$notice='All player notifications marked read.';}
        elseif($action==='webhook'&&$guildId>0){$url=trim((string)($_POST['endpoint_url']??''));if(!filter_var($url,FILTER_VALIDATE_URL)||!in_array(parse_url($url,PHP_URL_SCHEME),['https'],true))$error='Webhook endpoint must be an HTTPS URL.';else{$st=$db->prepare('INSERT INTO guild_webhooks(guild_id,endpoint_url) VALUES(?,?)');$st->bind_param('is',$guildId,$url);if($st->execute())$notice='Guild webhook registered.';else$error='Webhook registration failed.';}}
    }
}
$notifications=$guildId?$db->query("SELECT notification_id,title,body,status,created_at FROM guild_notifications WHERE guild_id=$guildId ORDER BY notification_id DESC LIMIT 50"):false;
$hooks=$guildId?$db->query("SELECT webhook_id,endpoint_url,enabled,failure_count,last_success_at FROM guild_webhooks WHERE guild_id=$guildId ORDER BY webhook_id DESC LIMIT 10"):false;
$playerUnreadQ=$db->query("SELECT COUNT(*) AS total FROM player_notifications WHERE uid=$uid AND is_read=0");$playerUnread=(int)(($playerUnreadQ&&($ur=$playerUnreadQ->fetch_assoc()))?$ur['total']:0);
$playerFeed=$db->query("SELECT notification_id,category,title,body,is_read,created_at FROM player_notifications WHERE uid=$uid ORDER BY created_at DESC,notification_id DESC LIMIT 50");
$h=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
echo '<div class="comm-shell"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // ALERT NETWORK</span><h3>Guild and Player Notifications</h3><p>Research, warfare, market, guild, and territory events appear in the alert network.</p></div>';if($notice)echo '<div class="comm-alert">'.$h($notice).'</div>';if($error)echo '<div class="comm-alert comm-error">'.$h($error).'</div>';
echo '<section class="comm-card"><h4>Player Alert Feed</h4><p><strong>'.number_format($playerUnread).'</strong> unread player notifications. Blueprint research completion alerts appear here automatically.</p><form method="post" action="/modules/notifications.php?time='.time().'"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="notification_action" value="player_read_all"/><button class="comm-btn">Mark All Player Alerts Read</button></form><div class="admin-table-wrap"><table><tr><th>Status</th><th>Category</th><th>Title</th><th>Message</th><th>Created</th><th>Action</th></tr>';if($playerFeed)while($n=$playerFeed->fetch_assoc())echo '<tr><td>'.((int)$n['is_read']?'Read':'<strong>New</strong>').'</td><td>'.$h($n['category']).'</td><td>'.$h($n['title']).'</td><td>'.$h($n['body']).'</td><td>'.$h($n['created_at']).'</td><td>'.((int)$n['is_read']?'—':'<form method="post" action="/modules/notifications.php?time='.time().'" class="inline-form"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="notification_action" value="player_read"/><input type="hidden" name="player_notification_id" value="'.(int)$n['notification_id'].'"/><button class="comm-btn">Mark Read</button></form>').'</td></tr>';echo '</table></div></section>';
echo '<section class="comm-card"><h4>Live Guild Event Feed</h4><p>Refresh this console or poll the notification endpoint to receive new guild alerts.</p><div class="admin-table-wrap"><table><tr><th>Status</th><th>Title</th><th>Message</th><th>Created</th><th>Action</th></tr>';if($notifications)while($n=$notifications->fetch_assoc())echo '<tr><td>'.$h($n['status']).'</td><td>'.$h($n['title']).'</td><td>'.$h($n['body']).'</td><td>'.$h($n['created_at']).'</td><td>'.($n['status']==='unread'?'<form method="post" action="/modules/notifications.php?time='.time().'" class="inline-form"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="notification_action" value="read"/><input type="hidden" name="notification_id" value="'.(int)$n['notification_id'].'"/><button class="comm-btn">Mark Read</button></form>':'Read').'</td></tr>';echo '</table></div></section><section class="comm-card"><h4>Guild Webhook</h4><p>Register an HTTPS endpoint for server-delivered JSON event alerts. Secrets are never displayed in the console.</p><form method="post" action="/modules/notifications.php?time='.time().'" class="inline-form"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="notification_action" value="webhook"/><input type="url" name="endpoint_url" placeholder="https://example.invalid/guild-events" required><button class="comm-btn">Register Webhook</button></form><div class="admin-table-wrap"><table><tr><th>Endpoint</th><th>Enabled</th><th>Failures</th><th>Last Success</th></tr>';if($hooks)while($wh=$hooks->fetch_assoc())echo '<tr><td>'.$h($wh['endpoint_url']).'</td><td>'.((int)$wh['enabled']?'Yes':'No').'</td><td>'.(int)$wh['failure_count'].'</td><td>'.$h((string)$wh['last_success_at']).'</td></tr>';echo '</table></div></section></div>';
$pagegen->stop();print('page generation time: '.$pagegen->gen());
?>
