<?php
include('../config.php');
require_once __DIR__ . '/../base/PlayerMarketPolicy.class.php';
require_once __DIR__ . '/../base/ResearchBlueprintPolicy.class.php';
$pagegen = new page_gen(); $pagegen->round_to = 4; $pagegen->start();
$game = new Game();
if (!$game->loggedIn || !isset($_GET['time'])) { header('Location: ../index.php'); exit; }
$db = $game->db_link; $uid = (int)$_SESSION['userid']; ResearchBlueprintPolicy::ensureTable($db);
if (empty($_SESSION['player_market_csrf'])) $_SESSION['player_market_csrf'] = bin2hex(random_bytes(24));
$csrf = $_SESSION['player_market_csrf']; $notice = ''; $error = '';
$h = static fn($v): string => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$db->query("CREATE TABLE IF NOT EXISTS player_blueprints (uid INT NOT NULL,blueprint_key VARCHAR(64) NOT NULL,quantity INT UNSIGNED NOT NULL DEFAULT 0,acquired_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(uid,blueprint_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS player_market_listings (listing_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,seller_uid INT NOT NULL,item_type ENUM('blueprint','module') NOT NULL,item_key VARCHAR(64) NOT NULL,item_level TINYINT UNSIGNED NOT NULL DEFAULT 0,quantity INT UNSIGNED NOT NULL,unit_price BIGINT UNSIGNED NOT NULL,status ENUM('active','sold','cancelled') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at DATETIME NULL,PRIMARY KEY(listing_id),KEY idx_market_active(status,item_type,item_key,unit_price,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS player_trade_offers (trade_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,proposer_uid INT NOT NULL,recipient_uid INT NOT NULL,offered_type ENUM('blueprint','module') NOT NULL,offered_key VARCHAR(64) NOT NULL,offered_level TINYINT UNSIGNED NOT NULL DEFAULT 0,offered_quantity INT UNSIGNED NOT NULL,requested_type ENUM('blueprint','module') NOT NULL,requested_key VARCHAR(64) NOT NULL,requested_level TINYINT UNSIGNED NOT NULL DEFAULT 0,requested_quantity INT UNSIGNED NOT NULL,offered_credits BIGINT UNSIGNED NOT NULL DEFAULT 0,requested_credits BIGINT UNSIGNED NOT NULL DEFAULT 0,status ENUM('pending','accepted','rejected','cancelled','expired') NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at DATETIME NULL,PRIMARY KEY(trade_id),KEY idx_trade_recipient(recipient_uid,status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("INSERT IGNORE INTO player_blueprints(uid,blueprint_key,quantity) VALUES($uid,'scout',1)");$db->query("INSERT IGNORE INTO player_blueprint_research(uid,blueprint_key,source,status,unlocked_at) VALUES($uid,'scout','starter','unlocked',NOW())");
function pm_item(mysqli $db, int $uid, string $type, string $key, int $level): int { $safe = $db->real_escape_string($key); if ($type === 'blueprint') { $q = $db->query("SELECT quantity FROM player_blueprints WHERE uid=$uid AND blueprint_key='$safe' FOR UPDATE"); return (int)(($q && ($r=$q->fetch_assoc())) ? $r['quantity'] : 0); } $q = $db->query("SELECT quantity,level FROM player_equipment WHERE uid=$uid AND equipment_key='$safe' FOR UPDATE"); $r = $q ? $q->fetch_assoc() : null; return $r && (int)$r['level'] === $level ? (int)$r['quantity'] : 0; }
function pm_change_item(mysqli $db, int $uid, string $type, string $key, int $level, int $delta): bool { $safe=$db->real_escape_string($key); if ($type === 'blueprint') { $db->query("INSERT IGNORE INTO player_blueprints(uid,blueprint_key,quantity) VALUES($uid,'$safe',0)"); $q=$db->query("UPDATE player_blueprints SET quantity=quantity+($delta) WHERE uid=$uid AND blueprint_key='$safe' AND quantity+($delta)>=0 LIMIT 1"); return (bool)$q && $db->affected_rows===1; } $q=$db->query("UPDATE player_equipment SET quantity=quantity+($delta) WHERE uid=$uid AND equipment_key='$safe' AND level=$level AND quantity+($delta)>=0 LIMIT 1"); return (bool)$q && $db->affected_rows===1; }
function pm_add_item(mysqli $db, int $uid, string $type, string $key, int $level, int $quantity): bool { $safe=$db->real_escape_string($key); if ($type === 'blueprint') { $db->query("INSERT INTO player_blueprints(uid,blueprint_key,quantity) VALUES($uid,'$safe',$quantity) ON DUPLICATE KEY UPDATE quantity=quantity+$quantity"); $db->query("INSERT IGNORE INTO player_blueprint_research(uid,blueprint_key,source,status,unlocked_at) VALUES($uid,'$safe','market','unlocked',NOW())"); return true; } $exists=$db->query("SELECT level FROM player_equipment WHERE uid=$uid AND equipment_key='$safe' LIMIT 1"); if($exists&&$exists->num_rows){$row=$exists->fetch_assoc();if((int)$row['level']!==$level)return false;$db->query("UPDATE player_equipment SET quantity=quantity+$quantity WHERE uid=$uid AND equipment_key='$safe' LIMIT 1");return true;} $db->query("INSERT INTO player_equipment(uid,equipment_key,level,quantity) VALUES($uid,'$safe',$level,$quantity)"); return true; }
function pm_credit(mysqli $db, int $uid, int $delta): bool { $db->query("INSERT IGNORE INTO bank(uid,onHand) VALUES($uid,0)"); $db->query("UPDATE bank SET onHand=onHand+($delta) WHERE uid=$uid AND onHand+($delta)>=0 LIMIT 1"); return $db->affected_rows===1; }
function pm_label(string $type,string $key,int $level): string { return PlayerMarketPolicy::label($type,$key,$level); }
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!hash_equals($csrf,(string)($_POST['csrf']??''))) $error='Security validation failed.';
    else {
        $action=(string)($_POST['market_action']??'');
        try {
            if ($action==='create_listing') {
                $type=(string)($_POST['item_type']??'');$key=(string)($_POST['item_key']??'');$level=max(0,min(10,(int)($_POST['item_level']??0)));$quantity=PlayerMarketPolicy::normalizeQuantity((int)($_POST['quantity']??0));$price=PlayerMarketPolicy::normalizePrice((int)($_POST['unit_price']??0));
                if(!PlayerMarketPolicy::validType($type)||!PlayerMarketPolicy::validItem($type,$key)||($type==='module'&&$level<1)||($type==='blueprint'&&$level!==0))throw new RuntimeException('Select a valid blueprint or module level.');
                $db->begin_transaction(); if(pm_item($db,$uid,$type,$key,$level)<$quantity||!pm_change_item($db,$uid,$type,$key,$level,-$quantity))throw new RuntimeException('You do not have enough of that item.'); $st=$db->prepare('INSERT INTO player_market_listings(seller_uid,item_type,item_key,item_level,quantity,unit_price) VALUES(?,?,?,?,?,?)');$st->bind_param('issiii',$uid,$type,$key,$level,$quantity,$price);if(!$st->execute())throw new RuntimeException('Listing could not be created.');$db->commit();$notice='Listing posted: '.pm_label($type,$key,$level).' x'.$quantity.'.';
            } elseif ($action==='buy_listing') {
                $listingId=(int)($_POST['listing_id']??0);$db->begin_transaction();$q=$db->query("SELECT * FROM player_market_listings WHERE listing_id=$listingId AND status='active' FOR UPDATE");$l=$q?$q->fetch_assoc():null;if(!$l||$l['seller_uid']===$uid)throw new RuntimeException('Listing is unavailable.');$total=(int)$l['quantity']*(int)$l['unit_price'];$bank=$db->query("SELECT onHand FROM bank WHERE uid=$uid FOR UPDATE")->fetch_assoc();if(!$bank||$bank['onHand']<$total)throw new RuntimeException('Insufficient Naquadah.');if(!pm_credit($db,$uid,-$total))throw new RuntimeException('Payment could not be reserved.');$sellerNet=(int)floor($total*(100-PlayerMarketPolicy::MARKET_FEE_PERCENT)/100);if(!pm_credit($db,(int)$l['seller_uid'],$sellerNet)||!pm_add_item($db,$uid,$l['item_type'],$l['item_key'],(int)$l['item_level'],(int)$l['quantity']))throw new RuntimeException('Item transfer failed.');$db->query("UPDATE player_market_listings SET status='sold',closed_at=NOW() WHERE listing_id=$listingId AND status='active' LIMIT 1");$db->commit();$notice='Purchase complete: '.pm_label($l['item_type'],$l['item_key'],(int)$l['item_level']).'.';
            } elseif ($action==='cancel_listing') {
                $listingId=(int)($_POST['listing_id']??0);$db->begin_transaction();$q=$db->query("SELECT * FROM player_market_listings WHERE listing_id=$listingId AND seller_uid=$uid AND status='active' FOR UPDATE");$l=$q?$q->fetch_assoc():null;if(!$l||!pm_add_item($db,$uid,$l['item_type'],$l['item_key'],(int)$l['item_level'],(int)$l['quantity']))throw new RuntimeException('Listing cannot be cancelled.');$db->query("UPDATE player_market_listings SET status='cancelled',closed_at=NOW() WHERE listing_id=$listingId LIMIT 1");$db->commit();$notice='Listing cancelled and item returned.';
            } elseif ($action==='create_trade') {
                $recipient=(int)($_POST['recipient_uid']??0);$ot=(string)($_POST['offered_type']??'');$ok=(string)($_POST['offered_key']??'');$ol=max(0,min(10,(int)($_POST['offered_level']??0)));$oq=PlayerMarketPolicy::normalizeQuantity((int)($_POST['offered_quantity']??0));$rt=(string)($_POST['requested_type']??'');$rk=(string)($_POST['requested_key']??'');$rl=max(0,min(10,(int)($_POST['requested_level']??0)));$rq=PlayerMarketPolicy::normalizeQuantity((int)($_POST['requested_quantity']??0));$oc=max(0,min(PlayerMarketPolicy::MAX_PRICE,(int)($_POST['offered_credits']??0)));$rc=max(0,min(PlayerMarketPolicy::MAX_PRICE,(int)($_POST['requested_credits']??0)));
                if($recipient<=0||$recipient===$uid||!PlayerMarketPolicy::validType($ot)||!PlayerMarketPolicy::validType($rt)||!PlayerMarketPolicy::validItem($ot,$ok)||!PlayerMarketPolicy::validItem($rt,$rk))throw new RuntimeException('Trade participants or items are invalid.');$db->begin_transaction();if(pm_item($db,$uid,$ot,$ok,$ol)<$oq||!pm_change_item($db,$uid,$ot,$ok,$ol,-$oq))throw new RuntimeException('You do not have enough to offer.');if($oc>0&&!pm_credit($db,$uid,-$oc))throw new RuntimeException('You do not have enough credits for the offer.');$st=$db->prepare('INSERT INTO player_trade_offers(proposer_uid,recipient_uid,offered_type,offered_key,offered_level,offered_quantity,requested_type,requested_key,requested_level,requested_quantity,offered_credits,requested_credits) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$st->bind_param('iissiissiiii',$uid,$recipient,$ot,$ok,$ol,$oq,$rt,$rk,$rl,$rq,$oc,$rc);
                if(!$st->execute())throw new RuntimeException('Trade offer could not be created.');$db->commit();$notice='Trade offer sent to commander #'.$recipient.'.';
            } elseif ($action==='resolve_trade') {
                $tradeId=(int)($_POST['trade_id']??0);$decision=(string)($_POST['decision']??'');$db->begin_transaction();$q=$db->query("SELECT * FROM player_trade_offers WHERE trade_id=$tradeId AND status='pending' FOR UPDATE");$t=$q?$q->fetch_assoc():null;if(!$t||((int)$t['recipient_uid']!==$uid&&(int)$t['proposer_uid']!==$uid))throw new RuntimeException('Trade offer is unavailable.');if($decision==='cancel'&&((int)$t['proposer_uid']!==$uid))throw new RuntimeException('Only the proposer can cancel.');if($decision!=='accept'){$db->query("UPDATE player_trade_offers SET status='".($decision==='cancel'?'cancelled':'rejected')."',resolved_at=NOW() WHERE trade_id=$tradeId LIMIT 1");if(!pm_add_item($db,(int)$t['proposer_uid'],$t['offered_type'],$t['offered_key'],(int)$t['offered_level'],(int)$t['offered_quantity'])||((int)$t['offered_credits']>0&&!pm_credit($db,(int)$t['proposer_uid'],(int)$t['offered_credits'])))throw new RuntimeException('Offer refund failed.');$db->commit();$notice='Trade offer closed and your reserved assets were returned.';}else{if((int)$t['recipient_uid']!==$uid)throw new RuntimeException('Only the recipient can accept.');if(pm_item($db,$uid,$t['requested_type'],$t['requested_key'],(int)$t['requested_level'])<(int)$t['requested_quantity'])throw new RuntimeException('You do not have the requested item.');if((int)$t['requested_credits']>0&&!pm_credit($db,$uid,-(int)$t['requested_credits']))throw new RuntimeException('You do not have the requested credits.');if(!pm_change_item($db,$uid,$t['requested_type'],$t['requested_key'],(int)$t['requested_level'],-(int)$t['requested_quantity'])||!pm_add_item($db,$uid,$t['offered_type'],$t['offered_key'],(int)$t['offered_level'],(int)$t['offered_quantity'])||!pm_add_item($db,(int)$t['proposer_uid'],$t['requested_type'],$t['requested_key'],(int)$t['requested_level'],(int)$t['requested_quantity'])||((int)$t['requested_credits']>0&&!pm_credit($db,(int)$t['proposer_uid'],(int)$t['requested_credits']))||((int)$t['offered_credits']>0&&!pm_credit($db,$uid,(int)$t['offered_credits'])))throw new RuntimeException('Trade settlement failed.');$db->query("UPDATE player_trade_offers SET status='accepted',resolved_at=NOW() WHERE trade_id=$tradeId LIMIT 1");$db->commit();$notice='Trade accepted and assets transferred.';}
            }
        } catch(Throwable $e){if($db->thread_id&&$db->errno===0)$db->rollback();else $db->rollback();$error=$e->getMessage()?:'Market operation failed.';}
    }
}
$types=['blueprint','module'];$blueprints=FleetPolicy::BLUEPRINTS;$modules=ModuleFittingPolicy::MODULES;
$listings=$db->query("SELECT l.*,u.uname FROM player_market_listings l JOIN users u ON u.uid=l.seller_uid WHERE l.status='active' ORDER BY l.unit_price ASC,l.created_at DESC LIMIT 200");$mine=$db->query("SELECT * FROM player_market_listings WHERE seller_uid=$uid AND status='active' ORDER BY created_at DESC");$trades=$db->query("SELECT t.*,pu.uname proposer_name,ru.uname recipient_name FROM player_trade_offers t JOIN users pu ON pu.uid=t.proposer_uid JOIN users ru ON ru.uid=t.recipient_uid WHERE t.proposer_uid=$uid OR t.recipient_uid=$uid ORDER BY t.trade_id DESC LIMIT 50");
echo '<div class="comm-shell player-market"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // PLAYER EXCHANGE</span><h3>Blueprint and Module Market</h3><p>Buy, sell, and trade blueprint licenses and fitted ship modules with server-authoritative settlement.</p></div>';if($notice)echo '<div class="comm-alert">'.$h($notice).'</div>';if($error)echo '<div class="comm-alert comm-error">'.$h($error).'</div>';
echo '<section class="comm-card"><h4>Post Market Listing</h4><form method="post" action="/modules/player_market.php?time='.time().'" class="admin-form-grid"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="create_listing"/><label>Item type<select name="item_type"><option value="blueprint">Blueprint</option><option value="module">Fitted Module</option></select></label><label>Item key<input name="item_key" placeholder="scout or railgun_array" required></label><label>Module level<input type="number" name="item_level" min="0" max="10" value="0"></label><label>Quantity<input type="number" name="quantity" min="1" max="100000" value="1" required></label><label>Price per item (Naq)<input type="number" name="unit_price" min="1" max="100000000000" value="1000" required></label><button class="comm-btn">Reserve and List</button></form><p class="market-note">Blueprint level is 0. Module listings preserve their crafted level and reserve the listed inventory until sale or cancellation. A '.PlayerMarketPolicy::MARKET_FEE_PERCENT.'% fee applies to completed market sales.</p></section>';
echo '<section class="comm-card"><h4>Direct Trade Offer</h4><form method="post" action="/modules/player_market.php?time='.time().'" class="admin-form-grid"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="create_trade"/><label>Recipient UID<input type="number" name="recipient_uid" min="1" required></label><label>Offer type<select name="offered_type"><option value="blueprint">Blueprint</option><option value="module">Module</option></select></label><label>Offer key<input name="offered_key" placeholder="scout" required></label><label>Offer level<input type="number" name="offered_level" min="0" max="10" value="0"></label><label>Offer quantity<input type="number" name="offered_quantity" min="1" value="1" required></label><label>Request type<select name="requested_type"><option value="blueprint">Blueprint</option><option value="module">Module</option></select></label><label>Request key<input name="requested_key" placeholder="shield_hardener" required></label><label>Request level<input type="number" name="requested_level" min="0" max="10" value="0"></label><label>Request quantity<input type="number" name="requested_quantity" min="1" value="1" required></label><label>Credits offered<input type="number" name="offered_credits" min="0" value="0"></label><label>Credits requested<input type="number" name="requested_credits" min="0" value="0"></label><button class="comm-btn">Send Trade Offer</button></form></section>';
echo '<section class="comm-card"><h4>My Active Listings</h4><div class="admin-table-wrap"><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Action</th></tr>';if($mine)while($l=$mine->fetch_assoc())echo '<tr><td>'.$h(pm_label($l['item_type'],$l['item_key'],(int)$l['item_level'])).'</td><td>'.number_format((int)$l['quantity']).'</td><td>'.number_format((int)$l['unit_price']).' Naq</td><td><form method="post" action="/modules/player_market.php?time='.time().'"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="cancel_listing"/><input type="hidden" name="listing_id" value="'.(int)$l['listing_id'].'"/><button class="comm-btn">Cancel</button></form></td></tr>';echo '</table></div></section>';
echo '<section class="comm-card"><h4>Market Listings</h4><div class="admin-table-wrap"><table><tr><th>Item</th><th>Seller</th><th>Qty</th><th>Unit Price</th><th>Action</th></tr>';if($listings)while($l=$listings->fetch_assoc())echo '<tr><td>'.$h(pm_label($l['item_type'],$l['item_key'],(int)$l['item_level'])).'</td><td>'.$h($l['uname']).'</td><td>'.number_format((int)$l['quantity']).'</td><td>'.number_format((int)$l['unit_price']).' Naq</td><td>'.((int)$l['seller_uid']===$uid?'Your listing':'<form method="post" action="/modules/player_market.php?time='.time().'"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="buy_listing"/><input type="hidden" name="listing_id" value="'.(int)$l['listing_id'].'"/><button class="comm-btn">Buy</button></form>').'</td></tr>';echo '</table></div></section>';
echo '<section class="comm-card"><h4>Trade Offers</h4><div class="admin-table-wrap"><table><tr><th>Trade</th><th>From</th><th>Offer</th><th>Request</th><th>Status</th><th>Action</th></tr>';if($trades)while($t=$trades->fetch_assoc()){ $action='—'; if($t['status']==='pending'&&(int)$t['recipient_uid']===$uid)$action='<form method="post" action="/modules/player_market.php?time='.time().'" class="inline-form"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="resolve_trade"/><input type="hidden" name="trade_id" value="'.(int)$t['trade_id'].'"/><button class="comm-btn" name="decision" value="accept">Accept</button><button class="comm-btn" name="decision" value="reject">Reject</button></form>';elseif($t['status']==='pending'&&(int)$t['proposer_uid']===$uid)$action='<form method="post" action="/modules/player_market.php?time='.time().'" class="inline-form"><input type="hidden" name="csrf" value="'.$h($csrf).'"/><input type="hidden" name="market_action" value="resolve_trade"/><input type="hidden" name="trade_id" value="'.(int)$t['trade_id'].'"/><button class="comm-btn" name="decision" value="cancel">Cancel</button></form>';echo '<tr><td>#'.(int)$t['trade_id'].'</td><td>'.$h($t['proposer_name']).' → '.$h($t['recipient_name']).'</td><td>'.$h(pm_label($t['offered_type'],$t['offered_key'],(int)$t['offered_level'])).' × '.(int)$t['offered_quantity'].' + '.number_format((int)$t['offered_credits']).' Naq</td><td>'.$h(pm_label($t['requested_type'],$t['requested_key'],(int)$t['requested_level'])).' × '.(int)$t['requested_quantity'].' + '.number_format((int)$t['requested_credits']).' Naq</td><td>'.$h($t['status']).'</td><td>'.$action.'</td></tr>'; }echo '</table></div></section></div>';
$pagegen->stop();print('page generation time: '.$pagegen->gen());
?>
