<?php
include_once('../config.php');
require_once('../base/FleetPolicy.class.php');
require_once('../base/PvPPolicy.class.php');
require_once('../base/PvPResolver.class.php');
require_once('../base/PvPMatchmakingService.class.php');
require_once('../base/PvPExpansionPolicy.class.php');
require_once('../base/PlayerActionCache.class.php');
$pagegen = new page_gen(); $pagegen->round_to = 4; $pagegen->start();
$game = new Game();
if (!$game->loggedIn || !isset($_GET['time'])) { header('Location: ../index.php'); exit; }
$db = $game->db_link; $uid = (int)($_SESSION['userid'] ?? 0);
$csrf = $_SESSION['pvp_csrf'] ?? bin2hex(random_bytes(24)); $_SESSION['pvp_csrf'] = $csrf;
$notice = ''; $error = '';
function pvp_h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function pvp_one(mysqli $db, string $sql): ?array { $q = $db->query($sql); return $q ? ($q->fetch_assoc() ?: null) : null; }
function pvp_install(mysqli $db, int $uid): void {
    $db->query("CREATE TABLE IF NOT EXISTS pvp_seasons (season_code VARCHAR(32) NOT NULL PRIMARY KEY,title VARCHAR(120) NOT NULL,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("INSERT IGNORE INTO pvp_seasons(season_code,title,starts_at,ends_at,status) VALUES ('S1-2026','Season 1: Frontier Ascension','2026-01-01 00:00:00','2026-12-31 23:59:59','active')");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_rankings (season_code VARCHAR(32) NOT NULL,uid INT NOT NULL,rating INT NOT NULL DEFAULT 1000,wins INT UNSIGNED NOT NULL DEFAULT 0,losses INT UNSIGNED NOT NULL DEFAULT 0,draws INT UNSIGNED NOT NULL DEFAULT 0,points_for BIGINT UNSIGNED NOT NULL DEFAULT 0,points_against BIGINT UNSIGNED NOT NULL DEFAULT 0,last_battle_at DATETIME NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(season_code,uid),KEY idx_pvp_rankings_board(season_code,rating,wins,uid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_rating_history (history_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,season_code VARCHAR(32) NOT NULL,battle_id BIGINT UNSIGNED NOT NULL,uid INT NOT NULL,result VARCHAR(8) NOT NULL,rating_before INT NOT NULL,rating_delta INT NOT NULL,rating_after INT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_pvp_rating_battle_player(season_code,battle_id,uid),KEY idx_pvp_rating_uid(season_code,uid,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("ALTER TABLE pvp_battles ADD COLUMN IF NOT EXISTS ranking_settled TINYINT(1) NOT NULL DEFAULT 0");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_replay_events (replay_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,battle_id BIGINT UNSIGNED NOT NULL,sequence_no INT UNSIGNED NOT NULL,phase VARCHAR(32) NOT NULL,event_at_seconds INT UNSIGNED NOT NULL DEFAULT 0,label VARCHAR(160) NOT NULL,event_json LONGTEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_pvp_replay_event(battle_id,sequence_no),KEY idx_pvp_replay_battle(battle_id,sequence_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_matchmaking_queue (queue_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,season_code VARCHAR(32) NOT NULL,uid INT NOT NULL,rating INT NOT NULL DEFAULT 1000,division VARCHAR(32) NOT NULL DEFAULT 'Commander',status VARCHAR(16) NOT NULL DEFAULT 'queued',queued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,matched_battle_id BIGINT UNSIGNED NULL,origin_planet_id INT NOT NULL DEFAULT 0,target_planet_id INT NOT NULL DEFAULT 0,fleet_json LONGTEXT NOT NULL,fitting_json LONGTEXT NOT NULL,UNIQUE KEY uq_pvp_queue_player(season_code,uid,status),KEY idx_pvp_queue_search(season_code,status,rating,queued_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_season_rewards (reward_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,season_code VARCHAR(32) NOT NULL,uid INT NOT NULL,place_position INT NOT NULL,title VARCHAR(80) NOT NULL,dark_matter BIGINT UNSIGNED NOT NULL DEFAULT 0,metal BIGINT UNSIGNED NOT NULL DEFAULT 0,crystal BIGINT UNSIGNED NOT NULL DEFAULT 0,deuterium BIGINT UNSIGNED NOT NULL DEFAULT 0,claimed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_pvp_reward_player(season_code,uid),KEY idx_pvp_reward_season(season_code,place_position)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_player_state (uid INT NOT NULL,protected_until DATETIME NULL,last_attack_at DATETIME NULL,attacks_today INT UNSIGNED NOT NULL DEFAULT 0,attack_day DATE NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(uid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_battles (battle_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,attacker_uid INT NOT NULL,defender_uid INT NOT NULL,target_planet_id INT NOT NULL,origin_planet_id INT NOT NULL,fleet_json LONGTEXT NOT NULL,fitting_json LONGTEXT NOT NULL DEFAULT '{}',attack_power INT UNSIGNED NOT NULL DEFAULT 0,defense_power INT UNSIGNED NOT NULL DEFAULT 0,outcome ENUM('pending','attacker_victory','defender_victory','draw','cancelled','protected') NOT NULL DEFAULT 'pending',status ENUM('enroute','resolved','cancelled') NOT NULL DEFAULT 'enroute',loot_metal BIGINT UNSIGNED NOT NULL DEFAULT 0,loot_crystal BIGINT UNSIGNED NOT NULL DEFAULT 0,loot_deuterium BIGINT UNSIGNED NOT NULL DEFAULT 0,attacker_losses INT UNSIGNED NOT NULL DEFAULT 0,defender_losses INT UNSIGNED NOT NULL DEFAULT 0,launched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resolves_at DATETIME NOT NULL,resolved_at DATETIME NULL,report TEXT NULL,PRIMARY KEY(battle_id),KEY idx_pvp_due(status,resolves_at,battle_id),KEY idx_pvp_attacker(attacker_uid,status,launched_at),KEY idx_pvp_defender(defender_uid,status,launched_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("ALTER TABLE pvp_battles ADD COLUMN IF NOT EXISTS fitting_json LONGTEXT NOT NULL DEFAULT '{}' AFTER fleet_json");
    $db->query("CREATE TABLE IF NOT EXISTS pvp_alerts (alert_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,uid INT NOT NULL,battle_id BIGINT UNSIGNED NOT NULL,alert_type ENUM('incoming_attack','battle_result','attack_launched') NOT NULL,title VARCHAR(160) NOT NULL,body VARCHAR(500) NOT NULL,is_read TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(alert_id),KEY idx_pvp_alert_uid(uid,is_read,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->query("INSERT IGNORE INTO pvp_player_state(uid,protected_until,attack_day) VALUES ($uid,DATE_ADD(NOW(),INTERVAL " . PvPPolicy::NEW_PLAYER_PROTECTION_HOURS . " HOUR),CURDATE())");
}
function pvp_alert(mysqli $db, int $uid, int $battleId, string $type, string $title, string $body): void { $s=$db->prepare('INSERT INTO pvp_alerts(uid,battle_id,alert_type,title,body) VALUES (?,?,?,?,?)'); if($s){$s->bind_param('iisss',$uid,$battleId,$type,$title,$body);$s->execute();} }
pvp_install($db, $uid); PvPResolver::resolveDue($db, 25);
$action = (string)($_POST['pvp_action'] ?? $_GET['pvp_action'] ?? '');
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($csrf, (string)($_POST['csrf'] ?? ''))) $error='Security validation failed. Refresh the PvP console and try again.';
    elseif ($action === 'queue' || $action === 'cancel_queue') {
        $season=PvPRankingPolicy::SEASON_CODE;
        if($action==='cancel_queue'){PvPMatchmakingService::cancel($db,$season,$uid);$notice='Matchmaking queue cancelled.';}
        else {$origin=(int)($_POST['origin_planet_id']??0);$target=(int)($_POST['target_planet_id']??0);$fleet=json_decode((string)($_POST['fleet_json']??''),true);$fitting=json_decode((string)($_POST['fitting_json']??'{}'),true);$originOwned=pvp_one($db,"SELECT pid FROM planets WHERE uid=$uid AND pid=$origin LIMIT 1");$ratingRow=pvp_one($db,"SELECT rating FROM pvp_rankings WHERE season_code='$season' AND uid=$uid LIMIT 1");$rating=(int)($ratingRow['rating']??PvPRankingPolicy::STARTING_RATING);if(!$originOwned||!is_array($fleet)||!PvPPolicy::validFleet($fleet)||!is_array($fitting)||!FleetPolicy::validateFitting($fleet,$fitting)['valid'])$error='Select an owned origin and valid fitted fleet for matchmaking.';else{PvPMatchmakingService::queue($db,$season,$uid,$rating,$origin,$target,$fleet,$fitting);$notice='Ranked matchmaking queue joined at '.PvPRankingPolicy::division($rating).' division ('.number_format($rating).' rating).';}}
    }
    elseif ($action === 'launch') {
        $defender=(int)($_POST['defender_uid']??0); $origin=(int)($_POST['origin_planet_id']??0); $target=(int)($_POST['target_planet_id']??0); $fleet=json_decode((string)($_POST['fleet_json']??''),true); $fitting=json_decode((string)($_POST['fitting_json']??'{}'),true);
        $targetOwner=PlayerActionCache::remember('planet_owner_'.$defender.'_'.$target,2,fn()=>pvp_one($db,"SELECT uid FROM planets WHERE uid=$defender AND pid=$target LIMIT 1")); $attacker=pvp_one($db,"SELECT uid FROM planets WHERE uid=$uid AND pid=$origin LIMIT 1");
        $state=pvp_one($db,"SELECT protected_until,last_attack_at FROM pvp_player_state WHERE uid=$uid LIMIT 1")??[]; $defenderState=pvp_one($db,"SELECT protected_until FROM pvp_player_state WHERE uid=$defender LIMIT 1")??[]; $recentRematch=pvp_one($db,"SELECT battle_id FROM pvp_battles WHERE ((attacker_uid=$uid AND defender_uid=$defender) OR (attacker_uid=$defender AND defender_uid=$uid)) AND launched_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND status IN ('enroute','resolved') LIMIT 1");
        $protection=strtotime((string)($state['protected_until']??'')); $cooldown=strtotime((string)($state['last_attack_at']??''))+PvPPolicy::ATTACK_COOLDOWN_MINUTES*60; $enemyProtection=strtotime((string)($defenderState['protected_until']??''));
        if($defender<=0||$defender===$uid||!$targetOwner||!$attacker)$error='Select a valid enemy commander, target world, and your origin planet.';
        elseif(!is_array($fleet)||!PvPPolicy::validFleet($fleet))$error='Fleet composition is invalid or exceeds deployment capacity.';
        elseif(!is_array($fitting)||!FleetPolicy::validateFitting($fleet,$fitting)['valid'])$error='Module fitting exceeds this hull\'s high, medium, low, CPU, power-grid, or capacitor limits.';
        elseif($protection>time())$error='Your civilization is still under newcomer protection.';
        elseif($cooldown>time())$error='Attack command is cooling down until '.date('H:i:s',$cooldown).'.';
        elseif($enemyProtection>time())$error='That civilization is currently protected and cannot be attacked.';
        elseif($recentRematch)$error='Ranked rematch cooldown active for this opponent. Wait 24 hours before attacking again.';
        else {
            $db->begin_transaction();
            try {
                $attack=0;$defense=0;$capacity=0;
                foreach($fleet as $ship=>$quantity){$quantity=(int)$quantity;$key=$db->real_escape_string((string)$ship);$row=pvp_one($db,"SELECT quantity FROM player_fleet_inventory WHERE uid=$uid AND planet_id=$origin AND ship_type='$key' FOR UPDATE");$available=(int)($row['quantity']??0);if(!FleetPolicy::valid((string)$ship)||$quantity<1||$available<$quantity)throw new RuntimeException('Insufficient fleet inventory.');$bp=FleetPolicy::BLUEPRINTS[$ship];$attack+=$bp['attack']*$quantity;$defense+=$bp['defense']*$quantity;$capacity+=$bp['capacity']*$quantity;}
                $fittedPower=FleetPolicy::fittedPower($fleet,$fitting); $attack=$fittedPower['attack']; $defense=$fittedPower['defense']; $capacity=$fittedPower['capacity'];
                if($attack<PvPPolicy::MIN_ATTACK_POWER||$capacity>PvPPolicy::MAX_FLEET_CAPACITY)throw new RuntimeException('Fleet is empty or exceeds deployment capacity.');
                $defenseRow=pvp_one($db,"SELECT COALESCE(SUM(quantity),0) AS fleet_defense FROM player_fleet_inventory WHERE uid=$defender AND planet_id=$target");$defenderPower=max(1,(int)($defenseRow['fleet_defense']??0));$fleetJson=json_encode($fleet,JSON_THROW_ON_ERROR);$eta=date('Y-m-d H:i:s',time()+PvPPolicy::TRAVEL_SECONDS);
                $fittingJson=json_encode(ModuleFittingPolicy::normalize($fitting),JSON_THROW_ON_ERROR);$s=$db->prepare('INSERT INTO pvp_battles(attacker_uid,defender_uid,target_planet_id,origin_planet_id,fleet_json,fitting_json,attack_power,defense_power,resolves_at) VALUES (?,?,?,?,?,?,?,?,?)');$s->bind_param('iiiissiis',$uid,$defender,$target,$origin,$fleetJson,$fittingJson,$attack,$defenderPower,$eta);if(!$s->execute())throw new RuntimeException('Unable to schedule battle.');$battleId=(int)$db->insert_id;
                foreach($fleet as $ship=>$quantity){$key=$db->real_escape_string((string)$ship);$db->query("UPDATE player_fleet_inventory SET quantity=quantity-".(int)$quantity." WHERE uid=$uid AND planet_id=$origin AND ship_type='$key' AND quantity>=".(int)$quantity." LIMIT 1");}
                $db->query("UPDATE pvp_player_state SET last_attack_at=NOW(),attacks_today=IF(attack_day=CURDATE(),attacks_today+1,1),attack_day=CURDATE() WHERE uid=$uid");
                pvp_alert($db,$defender,$battleId,'incoming_attack','Incoming PvP attack','A hostile fleet is approaching your world. Battle resolves at '.$eta.'.');pvp_alert($db,$uid,$battleId,'attack_launched','PvP attack launched','Your fleet is en route. Battle resolves at '.$eta.'.');$db->commit();$notice='PvP attack launched. Battle #'.$battleId.' resolves at '.$eta.'.';
            } catch(Throwable $e){$db->rollback();$error=$e->getMessage()?:'PvP launch failed.';}
        }
    } elseif ($action === 'read_alert') { $alert=(int)($_POST['alert_id']??0);$db->query("UPDATE pvp_alerts SET is_read=1 WHERE alert_id=$alert AND uid=$uid LIMIT 1");$notice='Alert marked read.'; }
}
$alerts=$db->query("SELECT alert_id,battle_id,alert_type,title,body,is_read,created_at FROM pvp_alerts WHERE uid=$uid ORDER BY alert_id DESC LIMIT 20");
$battles=$db->query("SELECT b.battle_id,b.attacker_uid,b.defender_uid,b.target_planet_id,b.attack_power,b.defense_power,b.outcome,b.status,b.loot_metal,b.loot_crystal,b.loot_deuterium,b.attacker_losses,b.defender_losses,b.launched_at,b.resolves_at,b.resolved_at,b.report,au.uname attacker_name,du.uname defender_name FROM pvp_battles b LEFT JOIN users au ON au.uid=b.attacker_uid LEFT JOIN users du ON du.uid=b.defender_uid WHERE b.attacker_uid=$uid OR b.defender_uid=$uid ORDER BY b.battle_id DESC LIMIT 30");
$planets=$db->query("SELECT pid,plnt_name FROM planets WHERE uid=$uid ORDER BY isHome DESC,pid");$queue=$db->query("SELECT status,queued_at,rating,division FROM pvp_matchmaking_queue WHERE season_code='".PvPRankingPolicy::SEASON_CODE."' AND uid=$uid ORDER BY queue_id DESC LIMIT 1");$queueState=$queue?$queue->fetch_assoc():null;$replays=$db->query("SELECT e.battle_id,e.sequence_no,e.phase,e.event_at_seconds,e.label,e.event_json FROM pvp_replay_events e INNER JOIN pvp_battles b ON b.battle_id=e.battle_id WHERE b.attacker_uid=$uid OR b.defender_uid=$uid ORDER BY e.battle_id DESC,e.sequence_no ASC LIMIT 90");$state=pvp_one($db,"SELECT protected_until,last_attack_at,attacks_today FROM pvp_player_state WHERE uid=$uid LIMIT 1")??[];
?>
<div class="comm-shell pvp-console"><div class="page-hub-head"><span class="rts-kicker">UNIVERSE CIVILIZATION // PLAYER WARFARE</span><h3>PvP Battle Command</h3><p>Launch timed fleet attacks, defend your worlds, review battle reports, and manage protection windows.</p></div>
<?php if($notice):?><div class="comm-alert"><?=pvp_h($notice)?></div><?php endif;?><?php if($error):?><div class="comm-alert comm-error"><?=pvp_h($error)?></div><?php endif;?>
<section class="comm-card"><h4>Command Status</h4><p>Protection: <?=!empty($state['protected_until'])&&strtotime($state['protected_until'])>time()?'Protected until '.pvp_h($state['protected_until']):'Open for warfare'?> · Last attack: <?=pvp_h($state['last_attack_at']??'Ready')?> · Attacks today: <?= (int)($state['attacks_today']??0)?></p></section>
<section class="comm-card"><h4>Launch Fleet Attack</h4><p>Attacks travel for <?=PvPPolicy::TRAVEL_SECONDS?> seconds and resolve automatically. Victories can loot up to <?=PvPPolicy::LOOT_RATE?>% of available basic resources.</p><form method="post" action="/modules/pvp.php?time=<?=time()?>" class="admin-form-grid"><input type="hidden" name="csrf" value="<?=pvp_h($csrf)?>"><input type="hidden" name="pvp_action" value="launch"><label>Enemy commander UID<input type="number" name="defender_uid" min="1" required></label><label>Your origin planet<select name="origin_planet_id" required><?php if($planets):while($planet=$planets->fetch_assoc()):?><option value="<?= (int)$planet['pid']?>">#<?= (int)$planet['pid']?> — <?=pvp_h($planet['plnt_name'])?></option><?php endwhile;endif;?></select></label><label>Enemy target planet ID<input type="number" name="target_planet_id" min="1" required></label><label>Module fitting JSON<input name="fitting_json" value="{}" required></label><label>Fleet JSON<input name="fleet_json" value="{&quot;scout&quot;:1}" required></label><button class="comm-btn">Launch PvP Attack</button></form></section>
<section class="comm-card"><h4>Battle Alerts</h4><div class="admin-table-wrap"><table><tr><th>Status</th><th>Alert</th><th>Message</th><th>Time</th><th>Action</th></tr><?php if($alerts):while($a=$alerts->fetch_assoc()):?><tr><td><?=$a['is_read']?'Read':'Unread'?></td><td><?=pvp_h($a['title'])?></td><td><?=pvp_h($a['body'])?></td><td><?=pvp_h($a['created_at'])?></td><td><?php if(!$a['is_read']):?><form method="post" action="/modules/pvp.php?time=<?=time()?>"><input type="hidden" name="csrf" value="<?=pvp_h($csrf)?>"><input type="hidden" name="pvp_action" value="read_alert"><input type="hidden" name="alert_id" value="<?= (int)$a['alert_id']?>"><button class="comm-btn">Mark Read</button></form><?php else:?>—<?php endif;?></td></tr><?php endwhile;endif;?></table></div></section>
<section class="comm-card"><h4>Battle Reports</h4><div class="admin-table-wrap"><table><tr><th>Battle</th><th>Opponent</th><th>Target</th><th>Power</th><th>Status</th><th>Outcome</th><th>Loot</th><th>Losses</th><th>Report</th></tr><?php if($battles):while($b=$battles->fetch_assoc()):$attacker=(int)$b['attacker_uid']===$uid;?><tr><td>#<?= (int)$b['battle_id']?></td><td><?=pvp_h($attacker?$b['defender_name']:$b['attacker_name'])?></td><td>#<?= (int)$b['target_planet_id']?></td><td><?= (int)$b['attack_power']?> / <?= (int)$b['defense_power']?></td><td><?=pvp_h($b['status'])?></td><td><?=pvp_h(str_replace('_',' ',$b['outcome']))?></td><td>M <?=number_format((int)$b['loot_metal'])?> · C <?=number_format((int)$b['loot_crystal'])?> · D <?=number_format((int)$b['loot_deuterium'])?></td><td><?= (int)$b['attacker_losses']?> / <?= (int)$b['defender_losses']?></td><td><?=pvp_h($b['report']??'Battle en route.')?></td></tr><?php endwhile;endif;?></table></div></section></div>
<?php $pagegen->stop();print('page generation time: '.$pagegen->gen()); ?>
