-- Territory resource production and taxation
ALTER TABLE guild_territories
  ADD COLUMN IF NOT EXISTS tax_rate TINYINT UNSIGNED NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS production_metal BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS production_crystal BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS production_energy BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_credits BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_accrued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE guilds
  ADD COLUMN IF NOT EXISTS shared_metal BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shared_crystal BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shared_energy BIGINT UNSIGNED NOT NULL DEFAULT 0;

UPDATE guild_territories SET tax_rate=LEAST(25, GREATEST(0, tax_rate));
