ALTER TABLE player_resources
  ADD COLUMN IF NOT EXISTS antimatter BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iridium BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tritanium BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS plasma BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exotic_matter BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dark_matter BIGINT NOT NULL DEFAULT 0;

ALTER TABLE player_resource_wallet
  ADD COLUMN IF NOT EXISTS antimatter BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iridium BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tritanium BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS plasma BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exotic_matter BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dark_matter BIGINT NOT NULL DEFAULT 0;

ALTER TABLE resource_structures
  ADD COLUMN IF NOT EXISTS antimatter_refinery INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS iridium_mine INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS tritanium_forge INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS plasma_harvester INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS exotic_matter_lab INT NOT NULL DEFAULT 1;

ALTER TABLE corporations
  ADD COLUMN IF NOT EXISTS shared_dark_matter BIGINT UNSIGNED NOT NULL DEFAULT 0;
