-- Legacy fleet dock mission outcomes for spy, raid, patrol, and expedition flows.
ALTER TABLE fleet_missions
  ADD COLUMN IF NOT EXISTS outcome VARCHAR(32) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS outcome_text VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS intel_json TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS loot_metal BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loot_crystal BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loot_deuterium BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS fleet_patrol_state (
  uid INT NOT NULL PRIMARY KEY,
  defense_bonus INT NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
