<?php
declare(strict_types=1);
require_once __DIR__.'/../config/config.php';
require_once __DIR__.'/../02_Gameplay/WorldService.php';
$pdo=db();if(!$pdo){fwrite(STDERR,"SKIP: database unavailable\n");exit(0);} $playerId=1;$svc=new WorldService($pdo);
$get=function(string $sql,array $args=[])use($pdo){$s=$pdo->prepare($sql);$s->execute($args);return $s->fetch(PDO::FETCH_ASSOC);};
$player=$get('SELECT glory,reputation,ascension_count,rank_level,rank_name FROM players WHERE id=?',[$playerId]);$prog=$get("SELECT * FROM progression_entities WHERE player_id=? AND entity_category='player' AND entity_key='player_core'",[$playerId]);$ast=$get('SELECT * FROM ascension_states WHERE player_id=?',[$playerId]);$gr=$get('SELECT * FROM glory_reputation WHERE player_id=?',[$playerId]);$cd=$get("SELECT * FROM player_cooldowns WHERE player_id=? AND cooldown_key='ascension'",[$playerId]);$tech=[];$q=$pdo->prepare("SELECT * FROM player_technologies WHERE player_id=? AND technology_key IN ('siege','fortification','infiltration','detection')");$q->execute([$playerId]);$tech=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$eventMax=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM game_events')->fetchColumn();$ascMax=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM ascensions')->fetchColumn();
try{
  $pdo->prepare("DELETE FROM player_cooldowns WHERE player_id=? AND cooldown_key='ascension'")->execute([$playerId]);
  $pdo->prepare('UPDATE players SET glory=5000,reputation=3000,ascension_count=0,rank_level=3,rank_name=\'Commander\' WHERE id=?')->execute([$playerId]);
  $pdo->prepare('INSERT INTO glory_reputation(player_id,glory,reputation) VALUES(?,5000,3000) ON DUPLICATE KEY UPDATE glory=5000,reputation=3000')->execute([$playerId]);
  $pdo->prepare("INSERT INTO progression_entities(player_id,entity_category,entity_key,tier_number,level_number,experience) VALUES(?, 'player','player_core',21,23,0) ON DUPLICATE KEY UPDATE tier_number=21,level_number=23,experience=0")->execute([$playerId]);
  foreach(['siege','fortification','infiltration','detection'] as $key)$pdo->prepare("INSERT INTO player_technologies(player_id,technology_key,technology_name,category,level,next_cost) VALUES(?,?,?,'unique',5,0) ON DUPLICATE KEY UPDATE level=5")->execute([$playerId,$key,ucwords($key)]);
  $snap=$svc->ascensionSnapshot($playerId);if(!$snap['eligible'])throw new RuntimeException('Maximum-tier fixture was not eligible: '.json_encode($snap));$expected=(int)$snap['reward']['ascension_points'];$svc->ascend($playerId,'Ascended Tau\'ri');
  $after=$svc->ascensionSnapshot($playerId);if(($after['progression']['tier']??0)!==1||($after['progression']['level']??0)!==1)throw new RuntimeException('Progression did not reset after ascension.');if(($after['ascension_state']['points']??0)!==$expected)throw new RuntimeException('Permanent ascension points were not persisted.');if(($after['cooldown']['state']??'')!=='cooldown')throw new RuntimeException('Ascension cooldown was not created.');
  echo "PASS: ascension eligibility, technology gate, reward, tier reset, permanent points, cooldown, and persistence verified\n";
}finally{
  $pdo->beginTransaction();$pdo->prepare('UPDATE players SET glory=?,reputation=?,ascension_count=?,rank_level=?,rank_name=? WHERE id=?')->execute([$player['glory'],$player['reputation'],$player['ascension_count'],$player['rank_level'],$player['rank_name'],$playerId]);
  $pdo->prepare('DELETE FROM player_cooldowns WHERE player_id=? AND cooldown_key=\'ascension\'')->execute([$playerId]);if($cd)$pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?)")->execute([$playerId,$cd['cooldown_key'],$cd['available_at']]);
  if($prog)$pdo->prepare("UPDATE progression_entities SET tier_number=?,level_number=?,experience=? WHERE player_id=? AND entity_category='player' AND entity_key='player_core'")->execute([$prog['tier_number'],$prog['level_number'],$prog['experience'],$playerId]);else $pdo->prepare("DELETE FROM progression_entities WHERE player_id=? AND entity_category='player' AND entity_key='player_core'")->execute([$playerId]);
  if($gr)$pdo->prepare('UPDATE glory_reputation SET glory=?,reputation=? WHERE player_id=?')->execute([$gr['glory'],$gr['reputation'],$playerId]);
  if($ast)$pdo->prepare('UPDATE ascension_states SET ascension_count=?,ascended_race=?,ascension_points=?,last_ascended_at=? WHERE player_id=?')->execute([$ast['ascension_count'],$ast['ascended_race'],$ast['ascension_points'],$ast['last_ascended_at'],$playerId]);
  $pdo->prepare("DELETE FROM player_technologies WHERE player_id=? AND technology_key IN ('siege','fortification','infiltration','detection')")->execute([$playerId]);foreach($tech as $row)$pdo->prepare('INSERT INTO player_technologies(id,player_id,technology_id,technology_key,technology_name,category,level,next_cost,updated_at) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$row['id'],$row['player_id'],$row['technology_id'],$row['technology_key'],$row['technology_name'],$row['category'],$row['level'],$row['next_cost'],$row['updated_at']]);
  $pdo->prepare('DELETE FROM ascensions WHERE id>? AND player_id=?')->execute([$ascMax,$playerId]);$pdo->prepare("DELETE FROM game_events WHERE id>? AND player_id=? AND event_type='ascended'")->execute([$eventMax,$playerId]);$pdo->commit();
}
