<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){fwrite(STDERR,"CLI only\n");exit(1);}
require_once __DIR__.'/../config/config.php';
require_once __DIR__.'/../includes/services/GameService.php';
require_once __DIR__.'/../includes/services/EconomyService.php';
$pdo=db();if(!$pdo){fwrite(STDERR,"SKIP: database unavailable\n");exit(0);}
$player=(int)$pdo->query("SELECT id FROM players WHERE username='demo' LIMIT 1")->fetchColumn();$col=$pdo->query("SELECT * FROM colonies WHERE player_id={$player} ORDER BY id LIMIT 1")->fetch(PDO::FETCH_ASSOC);if(!$player||!$col){fwrite(STDERR,"FAIL: demo fixture missing\n");exit(1);}
$resource=$pdo->query("SELECT * FROM player_resources WHERE player_id={$player}")->fetch(PDO::FETCH_ASSOC);$playerRow=$pdo->query("SELECT last_turn_at FROM players WHERE id={$player}")->fetch(PDO::FETCH_ASSOC);$checks=[];$fail=0;$check=function($n,$ok,$d='')use(&$checks,&$fail){$checks[]=['name'=>$n,'passed'=>(bool)$ok,'detail'=>$d];if(!$ok)$fail++;};
try{
  $pdo->prepare('UPDATE colonies SET food_stock=0,water_stock=0 WHERE id=?')->execute([$col['id']]);$zero=(new EconomyService($pdo))->settleColony($player,(int)$col['id'],1);$check('zero food remains non-negative',(int)$zero['food_after']===0);$check('zero water remains non-negative',(int)$zero['water_after']===0);$check('zero resources prevent growth',(int)$zero['population_after']===(int)$col['population']);$check('zero-resource morale responds',(float)$zero['morale']<(float)$col['morale']);
  $pdo->prepare('UPDATE player_resources SET untrained_units=0,miners=0,lifers=0,food=0,water=0,energy=0 WHERE player_id=?')->execute([$player]);$income=(new EconomyService($pdo))->incomeBreakdown($player);$check('negative income clamped',$income['net_settlement']>=0,(string)$income['net_settlement']);$pdo->prepare('UPDATE players SET last_turn_at=? WHERE id=?')->execute([(new DateTimeImmutable('now'))->modify('-3605 seconds')->format('Y-m-d H:i:s'),$player]);$turn=(new GameService($pdo))->processTurns($player);$check('turn income never negative',(int)$turn['income']>=0,(string)$turn['income']);
  $pdo->prepare('UPDATE colonies SET food_stock=1000000,water_stock=1000000,population=population_capacity WHERE id=?')->execute([$col['id']]);$capBefore=(int)$pdo->query("SELECT population_capacity FROM colonies WHERE id=".(int)$col['id'])->fetchColumn();$cap=(new EconomyService($pdo))->settleColony($player,(int)$col['id'],1);$check('maximum capacity prevents overflow',(int)$cap['population_after']===$capBefore,(int)$cap['population_after'].'/'.$capBefore);$check('capacity invariant holds',(int)$cap['population_after']<=$capBefore);
}catch(Throwable $e){$fail++;$checks[]=['name'=>'unexpected exception','passed'=>false,'detail'=>get_class($e).': '.$e->getMessage()];}
finally{$set=['food_stock','water_stock','population','population_capacity','morale','workforce'];$vals=[];foreach($set as $k)$vals[]=$col[$k];$pdo->prepare('UPDATE colonies SET food_stock=?,water_stock=?,population=?,population_capacity=?,morale=?,workforce=? WHERE id=?')->execute([...$vals,(int)$col['id']]);$fields=['attack_turns','unit_production','untrained_units','miners','lifers','food','water','energy','naquadah'];$vals=[];foreach($fields as $k)$vals[]=$resource[$k];$pdo->prepare('UPDATE player_resources SET '.implode('=?,',array_map(fn($x)=>"`$x`",$fields)).'=? WHERE player_id=?')->execute([...$vals,$player]);$pdo->prepare('UPDATE players SET last_turn_at=? WHERE id=?')->execute([$playerRow['last_turn_at'],$player]);}
$report=['status'=>$fail===0?'passed':'failed','checks'=>$checks];echo json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;exit($fail===0?0:1);
