<?php
declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/config/config.php';require_once $root.'/includes/services/UnitTrainingService.php';require_once $root.'/includes/services/UnitProductionService.php';
$pdo=db();$playerId=(int)$pdo->query("SELECT id FROM players WHERE username='demo' LIMIT 1")->fetchColumn();if($playerId<1){fwrite(STDERR,"demo_missing\n");exit(2);}
$r=$pdo->prepare('SELECT untrained_units,naquadah,unit_production FROM player_resources WHERE player_id=?');$r->execute([$playerId]);$before=$r->fetch(PDO::FETCH_ASSOC);$q=$pdo->prepare("SELECT id FROM training_queues WHERE player_id=? AND status IN ('queued','processing')");$q->execute([$playerId]);$trainingBefore=$q->fetchAll(PDO::FETCH_COLUMN);$q=$pdo->prepare("SELECT id FROM production_queues WHERE player_id=? AND status IN ('queued','processing')");$q->execute([$playerId]);$productionBefore=$q->fetchAll(PDO::FETCH_COLUMN);$checks=[];$newTraining=null;$newProduction=null;
try{$pdo->prepare("DELETE FROM player_cooldowns WHERE player_id=? AND cooldown_key IN ('training','production_upgrade')")->execute([$playerId]);$training=new UnitTrainingService($pdo);$type=$pdo->query("SELECT unit_key,recruit_cost FROM unit_types WHERE unit_key='miners' LIMIT 1")->fetch(PDO::FETCH_ASSOC);if(!$type)throw new RuntimeException('miners type missing');$result=$training->train($playerId,'miners',1);$newTraining=(int)$result['queue_id'];$checks['training_queued']=$newTraining>0&&$result['quantity']===1;$checks['training_cost']=(int)$result['cost']===(int)$type['recruit_cost'];$r->execute([$playerId]);$after=$r->fetch(PDO::FETCH_ASSOC);$checks['population_deducted']=(int)$after['untrained_units']===(int)$before['untrained_units']-1;$checks['resource_deducted']=(int)$after['naquadah']===(int)$before['naquadah']-(int)$result['cost'];
$automation=(int)$pdo->query("SELECT COALESCE(MAX(level),0) FROM player_technologies WHERE player_id={$playerId} AND technology_key='automation'")->fetchColumn();if($automation>0){$production=new UnitProductionService($pdo);$result2=$production->upgrade($playerId);$newProduction=(int)$result2['queue_id'];$checks['production_queued']=$newProduction>0&&$result2['level_after']===(int)$before['unit_production']+1;$checks['production_cost']=(int)$result2['cost']===(int)$before['unit_production']*5000+10000;}else{$checks['production_locked']=$automation===0;}
}catch(Throwable $e){$checks['mutation_error_free']=false;$checks['error']=$e->getMessage();}finally{$r->execute([$playerId]);$now=$r->fetch(PDO::FETCH_ASSOC);if($newTraining){$pdo->prepare('DELETE FROM training_queues WHERE id=? AND player_id=?')->execute([$newTraining,$playerId]);}$pdo->prepare('DELETE FROM training_queues WHERE player_id=? AND id NOT IN ('.($trainingBefore?implode(',',array_map('intval',$trainingBefore)):'0').')')->execute([$playerId]);if($newProduction){$pdo->prepare('DELETE FROM production_queues WHERE id=? AND player_id=?')->execute([$newProduction,$playerId]);}$pdo->prepare('DELETE FROM production_queues WHERE player_id=? AND id NOT IN ('.($productionBefore?implode(',',array_map('intval',$productionBefore)):'0').')')->execute([$playerId]);$pdo->prepare('UPDATE player_resources SET untrained_units=?,naquadah=?,unit_production=? WHERE player_id=?')->execute([(int)$before['untrained_units'],(int)$before['naquadah'],(int)$before['unit_production'],$playerId]);$pdo->prepare("DELETE FROM player_cooldowns WHERE player_id=? AND cooldown_key IN ('training','production_upgrade')")->execute([$playerId]);}
$failures=array_keys(array_filter($checks,static fn($value):bool=>$value===false));echo json_encode(['status'=>$failures?'failed':'passed','checks'=>$checks,'failures'=>$failures],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR).PHP_EOL;exit($failures?1:0);
