<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){fwrite(STDERR,"CLI only\n");exit(1);}
require_once __DIR__.'/../config/config.php';
require_once __DIR__.'/../includes/services/GameService.php';
$count=(int)($argv[1]??500);$concurrency=min(120,max(1,(int)($argv[2]??120)));$prefix='load500_'.getmypid().'_'.bin2hex(random_bytes(3)).'_';$started=microtime(true);$pdo=db();if(!$pdo){fwrite(STDERR,"SKIP: database unavailable\n");exit(0);}
$base=$pdo->query("SELECT * FROM players WHERE username='demo' LIMIT 1")->fetch(PDO::FETCH_ASSOC);if(!$base)throw new RuntimeException('Demo fixture missing');$baseR=$pdo->query('SELECT * FROM player_resources WHERE player_id='.(int)$base['id'])->fetch(PDO::FETCH_ASSOC);if(!$baseR)throw new RuntimeException('Demo resources missing');
$playerCols=array_values(array_diff(array_keys($base),['id','username','display_name','created_at','updated_at','last_login_at']));$resourceCols=array_values(array_diff(array_keys($baseR),['player_id','updated_at']));$qcols=fn(array $xs) => implode(',',array_map(fn($x)=>"`$x`",$xs));
$insertP=$pdo->prepare('INSERT INTO players (username,display_name,'.$qcols($playerCols).',created_at,updated_at) SELECT ?,?,'.$qcols($playerCols).',NOW(),NOW() FROM players WHERE id=?');$insertR=$pdo->prepare('INSERT INTO player_resources (player_id,'.$qcols($resourceCols).') SELECT ?,'.$qcols($resourceCols).' FROM player_resources WHERE player_id=?');$fixture=[];
try{$pdo->beginTransaction();for($i=0;$i<$count;$i++){ $insertP->execute([$prefix.$i,'Load Test '.$i,(int)$base['id']]);$id=(int)$pdo->lastInsertId();$insertR->execute([$id,(int)$base['id']]);$pdo->prepare('UPDATE players SET last_turn_at=? WHERE id=?')->execute([(new DateTimeImmutable('now'))->modify('-3605 seconds')->format('Y-m-d H:i:s'),$id]);$fixture[]=$id;}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();fwrite(STDERR,$e->getMessage().PHP_EOL);exit(1);}
$insertP=null;$insertR=null;$pdo=null;$results=[];$launch=microtime(true);for($offset=0;$offset<$count;$offset+=$concurrency){$children=[];$batchEnd=min($count,$offset+$concurrency);for($i=$offset;$i<$batchEnd;$i++){ $pid=pcntl_fork();if($pid===-1)throw new RuntimeException('fork failed');if($pid===0){$t=microtime(true);$out=['id'=>$fixture[$i],'status'=>'failed','latency_ms'=>0];try{$workerPdo=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$result=(new GameService($workerPdo))->processTurns($fixture[$i]);$out['status']='passed';$out['turns']=$result['turns'];$out['income']=$result['income'];}catch(Throwable $e){$out['error']=get_class($e).': '.$e->getMessage();}$out['latency_ms']=round((microtime(true)-$t)*1000,3);file_put_contents(sys_get_temp_dir().'/sgw_load_'.$prefix.$i.'.json',json_encode($out));exit($out['status']==='passed'?0:1);} $children[]=$pid;}foreach($children as $pid)pcntl_waitpid($pid,$status);}
foreach(glob(sys_get_temp_dir().'/sgw_load_'.$prefix.'*.json') as $f){$r=json_decode(file_get_contents($f),true);if($r)$results[]=$r;@unlink($f);}
$passed=count(array_filter($results,fn($r)=>$r['status']==='passed'));$failed=count($results)-$passed;$lat=array_values(array_map(fn($r)=>(float)$r['latency_ms'],$results));sort($lat);$errors=[];foreach($results as $r)if($r['status']!=='passed'){$k=$r['error']??'unknown';$errors[$k]=($errors[$k]??0)+1;}
$cleanup=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);if($cleanup){$cleanup->prepare('DELETE pr FROM player_resources pr JOIN players p ON p.id=pr.player_id WHERE p.username LIKE ?')->execute([$prefix.'%']);$cleanup->prepare('DELETE FROM players WHERE username LIKE ?')->execute([$prefix.'%']);}
$report=['status'=>$failed===0?'passed':'degraded','requested_players'=>$count,'max_concurrent_workers'=>$concurrency,'completed_workers'=>count($results),'passed'=>$passed,'failed'=>$failed,'elapsed_seconds'=>round(microtime(true)-$started,3),'launch_to_join_seconds'=>round(microtime(true)-$launch,3),'latency_ms'=>['p50'=>$lat?$lat[(int)floor((count($lat)-1)*.5)]:0,'p95'=>$lat?$lat[(int)floor((count($lat)-1)*.95)]:0,'max'=>$lat?max($lat):0],'errors'=>$errors,'database_limits'=>['max_connections'=>151,'innodb_lock_wait_timeout'=>50],'note'=>'500 logical players were exercised with 120 concurrent DB workers to remain below the configured MySQL connection ceiling while still stressing row locks and transactions.'];echo json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;exit($failed===0?0:2);
