<?php
declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/config/config.php';require_once $root.'/includes/services/WeaponMarketService.php';
$pdo=db();$seller=(int)$pdo->query("SELECT id FROM players WHERE username='demo' LIMIT 1")->fetchColumn();$buyer=(int)$pdo->query("SELECT id FROM players WHERE id<>$seller ORDER BY id LIMIT 1")->fetchColumn();
$type=(int)$pdo->query('SELECT weapon_type_id FROM player_weapons WHERE player_id='.$seller.' AND quantity>=1 ORDER BY id LIMIT 1')->fetchColumn();if($seller<1||$buyer<1||$type<1){fwrite(STDERR,"seed_market_participants_missing\n");exit(2);}
$resource=$pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=?');$resource->execute([$buyer]);$buyerBefore=(int)$resource->fetchColumn();$resource->execute([$seller]);$sellerNaquadahBefore=(int)$resource->fetchColumn();$inv=$pdo->prepare('SELECT quantity FROM player_weapons WHERE player_id=? AND weapon_type_id=?');$inv->execute([$seller,$type]);$sellerBefore=(int)$inv->fetchColumn();$pdo->prepare("DELETE FROM player_cooldowns WHERE player_id IN (?,?) AND cooldown_key IN ('market_list','market_buy')")->execute([$seller,$buyer]);
$service=new WeaponMarketService($pdo);$orderId=$service->listWeaponOrder($seller,$type,1,100,1);$order=$pdo->prepare('SELECT quantity,status,expires_at FROM market_orders WHERE id=? AND seller_id=?');$order->execute([$orderId,$seller]);$orderRow=$order->fetch(PDO::FETCH_ASSOC);$inv->execute([$seller,$type]);$sellerListed=(int)$inv->fetchColumn();$checks=['order_created'=>is_array($orderRow)&&$orderRow['status']==='open','inventory_reserved'=>$sellerListed===$sellerBefore-1];
$trade=$service->buyWeaponOrder($buyer,$orderId,1);$checks['trade_settled']=($trade['transaction_id']??0)>0&&($trade['quantity']??0)===1;$checkOrder=$pdo->prepare('SELECT quantity,status FROM market_orders WHERE id=?');$checkOrder->execute([$orderId]);$closed=$checkOrder->fetch(PDO::FETCH_ASSOC);$checks['order_filled']=is_array($closed)&&$closed['status']==='filled'&&(int)$closed['quantity']===0;$resource->execute([$buyer]);$buyerAfter=(int)$resource->fetchColumn();$checks['buyer_balance_charged']=$buyerAfter===$buyerBefore-100;$tx=$pdo->prepare('SELECT fee_amount,seller_net FROM market_transactions WHERE id=?');$tx->execute([(int)$trade['transaction_id']]);$txRow=$tx->fetch(PDO::FETCH_ASSOC);$checks['fee_recorded']=is_array($txRow)&&(int)$txRow['fee_amount']===5&&(int)$txRow['seller_net']===95;
$pdo->prepare('UPDATE player_resources SET naquadah=? WHERE player_id=?')->execute([$buyerBefore,$buyer]);$pdo->prepare('UPDATE player_resources SET naquadah=? WHERE player_id=?')->execute([$sellerNaquadahBefore,$seller]);$pdo->prepare('UPDATE player_weapons SET quantity=quantity+1 WHERE player_id=? AND weapon_type_id=?')->execute([$seller,$type]);$pdo->prepare('DELETE FROM market_transactions WHERE id=?')->execute([(int)$trade['transaction_id']]);$pdo->prepare('DELETE FROM game_events WHERE player_id=? AND event_type IN (\'market_weapon_listed\',\'market_weapon_bought\') AND created_at>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)')->execute([$seller]);$pdo->prepare('DELETE FROM game_events WHERE player_id=? AND event_type=\'market_weapon_bought\' AND created_at>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)')->execute([$buyer]);$pdo->prepare('DELETE FROM market_orders WHERE id=?')->execute([$orderId]);$failures=array_keys(array_filter($checks,static fn(bool $ok):bool=>!$ok));echo json_encode(['status'=>$failures?'failed':'passed','order_id'=>$orderId,'trade'=>$trade,'checks'=>$checks,'failures'=>$failures],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR).PHP_EOL;exit($failures?1:0);
