<?php
declare(strict_types=1);

/**
 * Universe Civilization: Empire at Wars — versioned design catalog.
 *
 * Catalog keys are server-owned. Client requests may reference keys, but all
 * costs, prerequisites, limits, and effects are resolved from this file or the
 * synchronized database catalog before a mutation is committed.
 */
return [
    'version' => 'UCEAW-CATALOG-2026.08.21',
    'resources' => [
        'metal' => ['label'=>'Metal','kind'=>'primary','storage'=>'metal_storage','uses'=>['buildings','ships','defenses','repairs']],
        'crystal' => ['label'=>'Crystal','kind'=>'primary','storage'=>'crystal_storage','uses'=>['research','electronics','ships','shields']],
        'deuterium' => ['label'=>'Deuterium','kind'=>'fuel','storage'=>'deuterium_tank','uses'=>['fleet_fuel','research','hyperspace']],
        'energy' => ['label'=>'Energy','kind'=>'capacity','storage'=>null,'uses'=>['production','life_support','infrastructure']],
        'food' => ['label'=>'Food','kind'=>'life_support','storage'=>'food_storage','uses'=>['population','troops','colony_growth']],
        'water' => ['label'=>'Water','kind'=>'life_support','storage'=>'water_reservoir','uses'=>['population','food','terraforming']],
        'population' => ['label'=>'Population','kind'=>'workforce','storage'=>'population_housing','uses'=>['workers','scientists','soldiers','engineers']],
        'fuel' => ['label'=>'Fuel','kind'=>'fleet','storage'=>'fuel_depot','uses'=>['fleet_travel','operations']],
        'dark_matter' => ['label'=>'Dark Matter','kind'=>'premium','storage'=>null,'uses'=>['officers','expeditions','special_actions']],
        'research_data' => ['label'=>'Research Data','kind'=>'science','storage'=>null,'uses'=>['advanced_research','anomalies']],
        'rare_minerals' => ['label'=>'Rare Minerals','kind'=>'strategic','storage'=>'rare_mineral_vault','uses'=>['megastructures','elite_ships']],
        'antimatter' => ['label'=>'Antimatter','kind'=>'strategic','storage'=>'antimatter_containment','uses'=>['reactors','jump_systems']],
        'nanites' => ['label'=>'Nanites','kind'=>'advanced','storage'=>'nanite_storage','uses'=>['construction','repairs','shipyards']],
    ],
    'biomes' => [
        'temperate'=>['food'=>1.15,'water'=>1.00,'metal'=>1.00,'crystal'=>1.00,'habitability'=>0.92],
        'desert'=>['food'=>0.70,'water'=>0.55,'metal'=>1.12,'crystal'=>1.08,'habitability'=>0.62],
        'oceanic'=>['food'=>1.05,'water'=>1.35,'metal'=>0.82,'crystal'=>1.02,'habitability'=>0.88],
        'arctic'=>['food'=>0.72,'water'=>1.12,'metal'=>0.92,'crystal'=>1.20,'habitability'=>0.58],
        'jungle'=>['food'=>1.32,'water'=>1.18,'metal'=>0.86,'crystal'=>0.94,'habitability'=>0.84],
        'volcanic'=>['food'=>0.48,'water'=>0.62,'metal'=>1.38,'crystal'=>1.18,'habitability'=>0.44],
        'toxic'=>['food'=>0.38,'water'=>0.46,'metal'=>1.25,'crystal'=>1.34,'habitability'=>0.30],
        'crystalline'=>['food'=>0.55,'water'=>0.70,'metal'=>0.92,'crystal'=>1.62,'habitability'=>0.52],
        'barren'=>['food'=>0.30,'water'=>0.40,'metal'=>1.18,'crystal'=>1.12,'habitability'=>0.24],
        'artificial'=>['food'=>0.90,'water'=>0.90,'metal'=>1.25,'crystal'=>1.25,'habitability'=>1.00],
    ],
    'buildings' => [
        'metal_mine'=>['category'=>'resource','base_cost'=>['metal'=>60,'crystal'=>15],'growth'=>1.50,'production'=>'metal'],
        'crystal_mine'=>['category'=>'resource','base_cost'=>['metal'=>48,'crystal'=>24],'growth'=>1.60,'production'=>'crystal'],
        'deuterium_synthesizer'=>['category'=>'resource','base_cost'=>['metal'=>225,'crystal'=>75],'growth'=>1.50,'production'=>'deuterium'],
        'food_farm'=>['category'=>'resource','base_cost'=>['metal'=>100,'crystal'=>40],'growth'=>1.45,'production'=>'food'],
        'water_extractor'=>['category'=>'resource','base_cost'=>['metal'=>120,'crystal'=>60],'growth'=>1.48,'production'=>'water'],
        'solar_plant'=>['category'=>'energy','base_cost'=>['metal'=>75,'crystal'=>30],'growth'=>1.50,'production'=>'energy'],
        'fusion_reactor'=>['category'=>'energy','base_cost'=>['metal'=>900,'crystal'=>360,'deuterium'=>180],'growth'=>1.55,'production'=>'energy'],
        'metal_storage'=>['category'=>'storage','base_cost'=>['metal'=>1000],'growth'=>1.60,'storage'=>'metal'],
        'crystal_storage'=>['category'=>'storage','base_cost'=>['metal'=>1000,'crystal'=>500],'growth'=>1.60,'storage'=>'crystal'],
        'deuterium_tank'=>['category'=>'storage','base_cost'=>['metal'=>1000,'crystal'=>1000],'growth'=>1.60,'storage'=>'deuterium'],
        'food_storage'=>['category'=>'storage','base_cost'=>['metal'=>700,'crystal'=>350],'growth'=>1.58,'storage'=>'food'],
        'water_reservoir'=>['category'=>'storage','base_cost'=>['metal'=>700,'crystal'=>500],'growth'=>1.58,'storage'=>'water'],
        'robotics_factory'=>['category'=>'infrastructure','base_cost'=>['metal'=>400,'crystal'=>120,'nanites'=>2],'growth'=>1.55],
        'nanite_factory'=>['category'=>'infrastructure','base_cost'=>['metal'=>1000000,'crystal'=>500000,'nanites'=>100],'growth'=>1.70],
        'research_laboratory'=>['category'=>'infrastructure','base_cost'=>['metal'=>200,'crystal'=>400,'deuterium'=>200],'growth'=>1.55],
        'shipyard'=>['category'=>'infrastructure','base_cost'=>['metal'=>400,'crystal'=>200,'deuterium'=>100],'growth'=>1.55],
        'terraformer'=>['category'=>'infrastructure','base_cost'=>['metal'=>50000,'crystal'=>25000,'deuterium'=>10000],'growth'=>1.65],
        'planetary_administration'=>['category'=>'infrastructure','base_cost'=>['metal'=>500,'crystal'=>300,'food'=>250,'water'=>250],'growth'=>1.55],
        'command_center'=>['category'=>'infrastructure','base_cost'=>['metal'=>1000,'crystal'=>500,'population'=>1000],'growth'=>1.60],
        'missile_silo'=>['category'=>'defense','base_cost'=>['metal'=>20000,'crystal'=>20000,'deuterium'=>1000],'growth'=>1.60],
        'shield_dome'=>['category'=>'defense','base_cost'=>['metal'=>10000,'crystal'=>10000,'deuterium'=>5000],'growth'=>1.60],
        'defense_grid'=>['category'=>'defense','base_cost'=>['metal'=>50000,'crystal'=>30000,'rare_minerals'=>10],'growth'=>1.65],
        'lunar_base'=>['category'=>'moon','base_cost'=>['metal'=>20000,'crystal'=>40000,'deuterium'=>20000],'growth'=>1.60],
        'sensor_phalanx'=>['category'=>'moon','base_cost'=>['metal'=>50000,'crystal'=>50000,'deuterium'=>20000],'growth'=>1.65],
        'jump_gate'=>['category'=>'moon','base_cost'=>['metal'=>2000000,'crystal'=>4000000,'deuterium'=>2000000],'growth'=>1.75],
    ],
    'technologies' => [
        'energy_technology'=>['category'=>'energy','base_cost'=>['metal'=>0,'crystal'=>800,'deuterium'=>400],'growth'=>1.50],
        'computer_technology'=>['category'=>'navigation','base_cost'=>['metal'=>0,'crystal'=>400,'deuterium'=>600],'growth'=>1.50],
        'hyperspace_technology'=>['category'=>'navigation','base_cost'=>['metal'=>0,'crystal'=>4000,'deuterium'=>2000],'growth'=>1.60],
        'combustion_drive'=>['category'=>'drive','base_cost'=>['metal'=>400,'crystal'=>0,'deuterium'=>600],'growth'=>1.50],
        'impulse_drive'=>['category'=>'drive','base_cost'=>['metal'=>2000,'crystal'=>4000,'deuterium'=>600],'growth'=>1.50],
        'hyperspace_drive'=>['category'=>'drive','base_cost'=>['metal'=>10000,'crystal'=>20000,'deuterium'=>6000],'growth'=>1.60],
        'weapons_technology'=>['category'=>'military','base_cost'=>['metal'=>800,'crystal'=>200,'deuterium'=>0],'growth'=>1.50],
        'shielding_technology'=>['category'=>'military','base_cost'=>['metal'=>200,'crystal'=>600,'deuterium'=>0],'growth'=>1.50],
        'armor_technology'=>['category'=>'military','base_cost'=>['metal'=>1000,'crystal'=>0,'deuterium'=>0],'growth'=>1.50],
        'espionage_technology'=>['category'=>'intelligence','base_cost'=>['metal'=>200,'crystal'=>1000,'deuterium'=>200],'growth'=>1.50],
        'astrophysics'=>['category'=>'navigation','base_cost'=>['metal'=>4000,'crystal'=>8000,'deuterium'=>4000],'growth'=>1.75],
        'fortification'=>['category'=>'defense','base_cost'=>['metal'=>1000,'crystal'=>1000,'deuterium'=>0],'growth'=>1.55],
    ],
    'ships' => [
        'small_cargo'=>['class'=>'civilian','role'=>'transport','base'=>['attack'=>5,'defense'=>20,'cargo'=>5000,'speed'=>5000,'fuel'=>10]],
        'large_cargo'=>['class'=>'civilian','role'=>'transport','base'=>['attack'=>5,'defense'=>60,'cargo'=>25000,'speed'=>7500,'fuel'=>50]],
        'colony_ship'=>['class'=>'civilian','role'=>'colonization','base'=>['attack'=>50,'defense'=>300,'cargo'=>7500,'speed'=>2500,'fuel'=>100]],
        'recycler'=>['class'=>'civilian','role'=>'recovery','base'=>['attack'=>1,'defense'=>160,'cargo'=>20000,'speed'=>2000,'fuel'=>300]],
        'espionage_probe'=>['class'=>'intelligence','role'=>'scout','base'=>['attack'=>0,'defense'=>1,'cargo'=>5,'speed'=>100000000,'fuel'=>1]],
        'solar_satellite'=>['class'=>'utility','role'=>'energy','base'=>['attack'=>0,'defense'=>200,'cargo'=>0,'speed'=>0,'fuel'=>0]],
        'light_fighter'=>['class'=>'combat','role'=>'interceptor','base'=>['attack'=>50,'defense'=>50,'cargo'=>50,'speed'=>12500,'fuel'=>20]],
        'heavy_fighter'=>['class'=>'combat','role'=>'escort','base'=>['attack'=>150,'defense'=>100,'cargo'=>100,'speed'=>10000,'fuel'=>75]],
        'cruiser'=>['class'=>'combat','role'=>'rapid_fire','base'=>['attack'=>400,'defense'=>270,'cargo'=>800,'speed'=>15000,'fuel'=>300]],
        'battleship'=>['class'=>'combat','role'=>'line_ship','base'=>['attack'=>1000,'defense'=>600,'cargo'=>1500,'speed'=>10000,'fuel'=>500]],
        'battlecruiser'=>['class'=>'combat','role'=>'anti_fleet','base'=>['attack'=>700,'defense'=>400,'cargo'=>750,'speed'=>10000,'fuel'=>250]],
        'bomber'=>['class'=>'combat','role'=>'planetary_attack','base'=>['attack'=>1000,'defense'=>500,'cargo'=>500,'speed'=>4000,'fuel'=>700]],
        'destroyer'=>['class'=>'combat','role'=>'capital_hunter','base'=>['attack'=>2000,'defense'=>1100,'cargo'=>2000,'speed'=>5000,'fuel'=>1000]],
        'deathstar'=>['class'=>'super_capital','role'=>'planet_breaker','base'=>['attack'=>200000,'defense'=>500000,'cargo'=>1000000,'speed'=>100,'fuel'=>1]],
        'mothership'=>['class'=>'command','role'=>'mobile_base','base'=>['attack'=>5000,'defense'=>10000,'cargo'=>100000,'speed'=>3000,'fuel'=>2000]],
    ],
    'defenses' => [
        'rocket_launcher'=>['class'=>'kinetic','attack'=>80,'defense'=>200,'cost'=>['metal'=>2000]],
        'light_laser'=>['class'=>'energy','attack'=>100,'defense'=>250,'cost'=>['metal'=>1500,'crystal'=>500]],
        'heavy_laser'=>['class'=>'energy','attack'=>250,'defense'=>600,'cost'=>['metal'=>6000,'crystal'=>2000]],
        'gauss_cannon'=>['class'=>'kinetic','attack'=>1100,'defense'=>500,'cost'=>['metal'=>20000,'crystal'=>15000,'deuterium'=>2000]],
        'ion_cannon'=>['class'=>'energy','attack'=>150,'defense'=>800,'cost'=>['metal'=>2000,'crystal'=>6000]],
        'plasma_turret'=>['class'=>'energy','attack'=>3000,'defense'=>1200,'cost'=>['metal'=>50000,'crystal'=>50000,'deuterium'=>30000]],
        'small_shield_dome'=>['class'=>'shield','attack'=>1,'defense'=>2000,'cost'=>['metal'=>10000,'crystal'=>10000]],
        'large_shield_dome'=>['class'=>'shield','attack'=>1,'defense'=>10000,'cost'=>['metal'=>50000,'crystal'=>50000]],
    ],
    'troops' => [
        'militia'=>['branch'=>'military','attack'=>8,'defense'=>10,'population'=>1],
        'infantry'=>['branch'=>'military','attack'=>18,'defense'=>16,'population'=>1],
        'marines'=>['branch'=>'military','attack'=>35,'defense'=>24,'population'=>1],
        'special_forces'=>['branch'=>'military','attack'=>70,'defense'=>45,'population'=>1],
        'engineers'=>['branch'=>'civilian','attack'=>3,'defense'=>10,'population'=>1],
        'scientists'=>['branch'=>'civilian','attack'=>2,'defense'=>6,'population'=>1],
        'administrators'=>['branch'=>'government','attack'=>1,'defense'=>4,'population'=>1],
        'security_guard'=>['branch'=>'government','attack'=>12,'defense'=>18,'population'=>1],
    ],
    'missions' => [
        'transport'=>['risk'=>0.02,'duration_factor'=>1.00],
        'deploy'=>['risk'=>0.04,'duration_factor'=>1.10],
        'attack'=>['risk'=>0.35,'duration_factor'=>1.20],
        'raid'=>['risk'=>0.48,'duration_factor'=>1.15],
        'espionage'=>['risk'=>0.22,'duration_factor'=>0.90],
        'colonize'=>['risk'=>0.28,'duration_factor'=>1.80],
        'recycle'=>['risk'=>0.18,'duration_factor'=>1.25],
        'expedition'=>['risk'=>0.40,'duration_factor'=>2.00],
    ],
    'officers' => [
        'administrator'=>['effect'=>'production','base'=>0.05],
        'engineer'=>['effect'=>'defense','base'=>0.05],
        'scientist'=>['effect'=>'research','base'=>0.05],
        'fleet_commander'=>['effect'=>'fleet','base'=>0.05],
        'spy_master'=>['effect'=>'espionage','base'=>0.05],
    ],
    'events' => [
        'meteor_storm'=>['risk'=>'medium','effects'=>['metal'=>0.08,'defense'=>-0.05]],
        'solar_flare'=>['risk'=>'high','effects'=>['energy'=>-0.12,'research'=>0.06]],
        'pirate_war'=>['risk'=>'high','effects'=>['combat'=>0.15,'trade'=>-0.10]],
        'ancient_gateway'=>['risk'=>'extreme','effects'=>['exploration'=>0.25,'dark_matter'=>0.10]],
        'resource_boom'=>['risk'=>'low','effects'=>['production'=>0.20]],
    ],
];
