<?php
declare(strict_types=1);
return [
 'dashboard'=>['loop'=>'read state → choose intent → authorize → transact → settle → feedback','features'=>['resource counters','colony life support','queue visibility','fleet ETAs','alerts','turn settlement'],'actions'=>['process_turns','choose_target','review_reports'],'tables'=>['players','player_resources','player_colonies','construction_queue','fleet_missions','rankings','game_events']],
 'economy'=>['loop'=>'production + modifiers - consumption = settlement','features'=>['Metal','Crystal','Naquadah','Energy','Dark Matter','food','water','vault transfers','capacity'],'actions'=>['deposit','withdraw','colony_turn'],'tables'=>['player_resources','player_colonies','dark_matter_transactions']],
 'technology'=>['loop'=>'prerequisites → cost → queue → completion → modifier','features'=>['offense technology','defense technology','covert technology','anti-covert technology','research queues'],'actions'=>['technology','queue_building','queue_research'],'tables'=>['technologies','technology_prerequisites','player_technologies','construction_queue']],
 'military'=>['loop'=>'target validation → power calculation → combat transaction → report','features'=>['attack','raid','conquest','casualties','loot','defense grids','weapon durability'],'actions'=>['combat','planet_defense','weapon_buy','weapon_repair'],'tables'=>['battles','battle_participants','battle_reports','attack_logs','planet_defenses','player_weapons']],
 'intelligence'=>['loop'=>'agent assignment → detection roll → information result → report','features'=>['reconnaissance','spying','sabotage','anti-covert defense','spy logs'],'actions'=>['covert','message_read'],'tables'=>['covert_missions','spy_missions','sabotage_missions','intelligence_reports']],
 'colonies'=>['loop'=>'population + production - food/water upkeep = colony state','features'=>['colonization','biomes','habitability','population','morale','buildings','life support'],'actions'=>['colonize_planet','colony_turn','queue_building','planet_defense'],'tables'=>['universe_planets','universe_moons','player_colonies','construction_queue']],
 'fleet'=>['loop'=>'fleet selection → payload validation → travel time → arrival → return','features'=>['transport','attack','raid','espionage','colonize','recycle','explore','return'],'actions'=>['launch_mission'],'tables'=>['fleet_types','colony_fleets','fleet_missions']],
 'universe'=>['loop'=>'coordinate lookup → inspect modifiers → discover → colonize','features'=>['galaxies','sectors','solar systems','planets','moons','coordinates','anomalies'],'actions'=>['explore','colonize_planet','record_discovery'],'tables'=>['universe_galaxies','universe_sectors','universe_solar_systems','universe_planets','universe_moons','universe_discoveries']],
 'social'=>['loop'=>'proposal or message → permission check → persistence → notification','features'=>['alliances','diplomacy','trades','messages','recruitment','rankings','world events'],'actions'=>['alliance_create','alliance_join','diplomacy_propose','trade_create','message','refresh_rankings','event_join'],'tables'=>['alliances','alliance_members','diplomacy_relations','trade_contracts','messages','rankings','game_world_events','world_event_participants']],
 'progression'=>['loop'=>'activity → experience → level → Glory/Reputation → ascension','features'=>['levels','Glory','Reputation','ranks','vacation mode','ascension'],'actions'=>['add_experience','ascend','vacation','change_race'],'tables'=>['player_progression','glory_reputation','rank_definitions','ascensions','protection_states']],
];
