<?php
declare(strict_types=1);
return [
 'colony-management'=>['label'=>'Colony Management','pages'=>['colonies'=>['title'=>'Colonies','controls'=>['Create colony','Rename','Abandon'],'actions'=>['colonize','colony_update'],'tables'=>['colonies']], 'food-water'=>['title'=>'Food & Water','controls'=>['Allocate production','Import supplies'],'actions'=>['colony_turn','transport'],'tables'=>['colonies','player_resource_balances','colony_turn_snapshots']], 'population'=>['title'=>'Population','controls'=>['View growth','Adjust morale'],'actions'=>['colony_update'],'tables'=>['colonies']]]],
 'buildings'=>['label'=>'Buildings','pages'=>['resource-buildings'=>['title'=>'Resource Buildings','controls'=>['Build','Upgrade','Cancel queue'],'actions'=>['queue_building'],'tables'=>['building_types','colony_buildings','construction_queue']], 'life-support'=>['title'=>'Life Support','controls'=>['Build farm','Build water processor'],'actions'=>['queue_building'],'tables'=>['building_types','colony_buildings']], 'shipyard'=>['title'=>'Shipyard','controls'=>['Build fleet','Queue ship'],'actions'=>['queue_fleet'],'tables'=>['fleet_types','colony_fleets','construction_queue']], 'defense-grid'=>['title'=>'Defense Grid','controls'=>['Build defense','Upgrade defense'],'actions'=>['queue_defense'],'tables'=>['defense_types','colony_defenses','construction_queue']]]],
 'research-lab'=>['label'=>'Research','pages'=>['research'=>['title'=>'Research Tree','controls'=>['Research technology','Cancel research'],'actions'=>['queue_research'],'tables'=>['research_types','player_research','construction_queue']], 'navigation'=>['title'=>'Navigation Research','controls'=>['Upgrade'],'actions'=>['queue_research'],'tables'=>['research_types','player_research']], 'energy'=>['title'=>'Energy Research','controls'=>['Upgrade'],'actions'=>['queue_research'],'tables'=>['research_types','player_research']]]],
 'fleets'=>['label'=>'Fleets','pages'=>['fleet-overview'=>['title'=>'Fleet Overview','controls'=>['View hangar','Split fleet'],'actions'=>[],'tables'=>['fleet_types','colony_fleets']], 'missions'=>['title'=>'Fleet Missions','controls'=>['Transport','Attack','Raid','Colonize','Explore','Return'],'actions'=>['launch_mission'],'tables'=>['fleet_missions','colonies']], 'mission-log'=>['title'=>'Mission Log','controls'=>['Open mission','Cancel mission'],'actions'=>['mission_cancel'],'tables'=>['fleet_missions']]]],
 'world-events'=>['label'=>'World Events','pages'=>['events'=>['title'=>'World Events','controls'=>['Open event','Join event'],'actions'=>['event_join'],'tables'=>['game_world_events']], 'event-history'=>['title'=>'Event History','controls'=>['View results'],'actions'=>[],'tables'=>['game_world_events','game_events']]]],
];
