<?php
declare(strict_types=1);

$make = static function (string $hero, array $panels, string $formula, array $controls, array $permissions, array $tables, array $states = ['ready','empty','protected','error']): array {
    return compact('hero','panels','formula','controls','permissions','tables','states');
};

return [
    'targets' => $make('Target Selection', ['Known realms','Protection status','Combat preview','Operation costs'], 'battle outcome = validated force comparison + technology + defense + deterministic resolver', ['Attack','Raid','Spy','Sabotage','Conquer planet','Message'], ['authenticated commander','attack turns available','target ownership checked'], ['target_realms','players','rankings','protection_states','battles'], ['ready','protected','insufficient-resource','cooldown','success','error']),
    'spy' => $make('Spy Operations', ['Agent allocation','Detection chance','Target intelligence','Mission result'], 'detection = defender counter-intelligence − attacker agents − covert technology', ['Reconnaissance','Spy mission','Abort mission'], ['authenticated commander','available agents','target validated'], ['covert_agents','anti_covert_agents','spy_missions','intelligence_reports'], ['ready','protected','insufficient-resource','cooldown','success','error']),
    'sabotage' => $make('Sabotage Operations', ['System selector','Damage ceiling','Detection risk','Mission result'], 'damage = agents × covert technology × target vulnerability, capped by system integrity', ['Choose system','Run sabotage','Review risk'], ['authenticated commander','available agents','system target validated'], ['covert_missions','sabotage_missions','intelligence_reports'], ['ready','protected','insufficient-resource','cooldown','success','error']),
    'attack-log' => $make('Attack Log & Reports', ['Unread reports','Battle outcomes','Loot and losses','Audit state'], 'report visibility = recipient ownership + classification + read status', ['Open report','Mark read','Filter outcomes'], ['authenticated report recipient','ownership verified'], ['battle_reports','attack_logs','battles','messages'], ['loading','ready','empty','success','error']),
    'weapons' => $make('Weapon Inventory', ['Owned weapons','Durability','Power profile','Loadout readiness'], 'effective weapon power = base power × condition × technology modifier', ['Inspect durability','Equip weapon','Buy weapon'], ['authenticated commander','weapon ownership','resource validation'], ['weapon_types','player_weapons','player_resources'], ['ready','empty','insufficient-resource','success','error']),
    'weapon-market' => $make('Weapon Market', ['Market listings','Order book','Price limits','Trade history'], 'trade settlement = validated order × market price − transaction fee', ['List order','Buy order','Cancel order'], ['authenticated commander','seller ownership','balance validation'], ['market_orders','weapon_types','market_transactions'], ['ready','empty','insufficient-resource','success','error']),
    'repair' => $make('Weapon Repair', ['Damaged inventory','Repair estimate','Queue time','Repair result'], 'repair cost = missing durability × weapon tier × repair multiplier', ['Select weapon','Repair weapon','Cancel repair'], ['authenticated commander','weapon ownership','resource validation'], ['player_weapons','weapon_types','player_resources','production_queues'], ['ready','empty','insufficient-resource','success','error']),
    'units' => $make('Unit Training', ['Training roster','Queue capacity','Recruitment cost','Readiness'], 'training output = queue time × academy level × population workforce', ['Train units','Pause queue','Cancel queue'], ['authenticated commander','population available','resource validation'], ['unit_types','player_unit_stats','training_queues','player_resources'], ['ready','empty','insufficient-resource','success','error']),
    'miners' => $make('Miners & Lifers', ['Civilian workforce','Miner allocation','Life-support load','Production effect'], 'workforce output = assigned population × role efficiency × morale', ['Train miners','Assign workforce','Rebalance roles'], ['authenticated commander','colony ownership','population capacity'], ['player_colonies','population_assignments','player_resources','races'], ['ready','empty','insufficient-resource','success','error']),
    'super-units' => $make('Super Units', ['Elite roster','Prerequisites','Strategic cost','Deployment readiness'], 'elite power = base power × tier mastery × technology × race modifier', ['Train elite units','Review prerequisites','Deploy unit'], ['authenticated commander','technology prerequisite','resource validation'], ['unit_types','player_unit_stats','technologies','player_resources'], ['ready','locked','insufficient-resource','success','error']),
    'unit-production' => $make('Unit Production', ['Upgrade tracks','Production modifiers','Queue slots','Upgrade result'], 'upgrade effect = level × tier coefficient × technology modifier', ['Upgrade UP','Queue production','Review costs'], ['authenticated commander','upgrade prerequisite','resource validation'], ['player_resources','unit_production','technologies','production_queues'], ['ready','locked','insufficient-resource','success','error']),
    'technology' => $make('Technology Tree', ['Research branches','Prerequisites','Research queue','Applied effects'], 'technology effect = base effect × level × tier coefficient', ['Upgrade offense','Upgrade defense','Upgrade covert','Upgrade anti-covert'], ['authenticated commander','research prerequisite','resource validation'], ['technologies','player_technologies','research_queues','player_resources'], ['ready','locked','insufficient-resource','success','error']),
    'tech-offense' => $make('Offense Technology', ['Weapon systems','Damage modifiers','Prerequisite chain','Research result'], 'offense effect = base damage × technology level × tier coefficient', ['Upgrade offense','Inspect prerequisite','Queue research'], ['authenticated commander','technology ownership','resource validation'], ['technologies','player_technologies','research_queues'], ['ready','locked','insufficient-resource','success','error']),
    'tech-defense' => $make('Defense Technology', ['Shield systems','Defense modifiers','Prerequisite chain','Research result'], 'defense effect = base defense × technology level × tier coefficient', ['Upgrade defense','Inspect prerequisite','Queue research'], ['authenticated commander','technology ownership','resource validation'], ['technologies','player_technologies','research_queues'], ['ready','locked','insufficient-resource','success','error']),
    'tech-covert' => $make('Covert Technology', ['Agent systems','Infiltration modifiers','Prerequisite chain','Research result'], 'covert effect = agent effectiveness × technology level × tier coefficient', ['Upgrade covert','Inspect prerequisite','Queue research'], ['authenticated commander','technology ownership','resource validation'], ['technologies','player_technologies','research_queues'], ['ready','locked','insufficient-resource','success','error']),
    'tech-anti-covert' => $make('Anti-Covert Technology', ['Counter-intelligence','Detection modifiers','Prerequisite chain','Research result'], 'counter-intelligence = base counter force × technology level × tier coefficient', ['Upgrade anti-covert','Inspect prerequisite','Queue research'], ['authenticated commander','technology ownership','resource validation'], ['technologies','player_technologies','research_queues'], ['ready','locked','insufficient-resource','success','error']),
    'spy-log' => $make('Spy Log', ['Recent missions','Detection outcomes','Intelligence payloads','Read state'], 'report visibility = recipient ownership + classification + read status', ['Open report','Mark read','Filter mission'], ['authenticated commander','report ownership'], ['covert_missions','spy_missions','intelligence_reports'], ['loading','ready','empty','success','error']),
    'enemy-intelligence' => $make('Enemy Intelligence', ['Known targets','Confidence scores','Last observation','Report classification'], 'intelligence confidence = observation quality × freshness × counter-intelligence adjustment', ['Open intelligence report','Refresh target'], ['authenticated commander','report classification permitted'], ['intelligence_reports','players','target_realms'], ['loading','ready','empty','protected','error']),
    'resource-exchange' => $make('Resource Exchange', ['Exchange rates','Available orders','Trade limits','Settlement preview'], 'exchange result = offered resource × rate − market fee', ['List order','Buy order','Cancel order'], ['authenticated commander','balance validation','market limits'], ['market_orders','player_resources','market_transactions'], ['ready','empty','insufficient-resource','success','error']),
    'mercenary-market' => $make('Mercenary Market', ['Mercenary roster','Contract terms','Hiring cost','Deployment status'], 'contract cost = unit tier × contract duration × scarcity modifier', ['Recruit','Sell','Review contract'], ['authenticated commander','population capacity','resource validation'], ['mercenary_types','player_mercenaries','player_resources'], ['ready','empty','insufficient-resource','success','error']),
    'rankings' => $make('Rankings', ['Commander ladder','Military score','Economy score','Season movement'], 'ranking score = economy + military + technology + glory − penalties', ['Refresh rankings','Open player','Compare commander'], ['authenticated commander','public ranking data'], ['rankings','rank_snapshots','players','glory_reputation'], ['loading','ready','empty','error']),
    'alliances' => $make('Alliances', ['Alliance identity','Membership roster','Diplomatic standing','Shared projects'], 'alliance capacity = command level × alliance technology × government modifier', ['Create alliance','Join alliance','Leave alliance'], ['authenticated commander','membership rules','role permission'], ['alliances','alliance_members','alliance_projects'], ['ready','empty','protected','success','error']),
    'messages' => $make('Messages', ['Inbox','Sent messages','Read state','Blacklist controls'], 'message visibility = recipient ownership + blacklist policy + read status', ['Send','Mark read','Blacklist'], ['authenticated commander','recipient validation','message rate limit'], ['messages','blacklists','players'], ['loading','ready','empty','success','error']),
    'planet-list' => $make('Planet List', ['Owned colonies','Life-support status','Production output','Fleet presence'], 'colony output = base production × biome × race × government × morale', ['Open colony','Explore','Conquer'], ['authenticated commander','colony ownership','target validation'], ['player_colonies','planet_bonuses','planet_explorations','player_resources'], ['ready','empty','protected','success','error']),
    'planet-bonuses' => $make('Planet Bonuses', ['Biome modifiers','Building bonuses','Colony morale','Applied production'], 'planet bonus = biome modifier + building bonus + morale adjustment', ['View bonuses','Compare colonies'], ['authenticated commander','colony ownership'], ['planet_bonuses','player_colonies','universe_planets'], ['ready','empty','error']),
    'planet-defenses' => $make('Planet Defenses', ['Defense grid','Shield integrity','Garrison units','Upgrade queue'], 'defense rating = structures × condition × technology × planet bonus', ['Upgrade defense','Repair defense','Review garrison'], ['authenticated commander','colony ownership','resource validation'], ['planet_defenses','player_unit_stats','player_resources','production_queues'], ['ready','empty','insufficient-resource','success','error']),
    'ship' => $make('Mothership', ['Hull integrity','Hangar capacity','Shield systems','Upgrade queue'], 'mothership capacity = hull tier + hangar modules + technology modifier', ['Upgrade hull','Upgrade hangars','Upgrade shields'], ['authenticated commander','mothership ownership','resource validation'], ['motherships','mothership_modules','player_resources'], ['ready','locked','insufficient-resource','success','error']),
    'modules' => $make('Mothership Modules', ['Installed modules','Power draw','Module effects','Upgrade queue'], 'module effect = module level × module coefficient × mothership technology', ['Upgrade module','Install module','Remove module'], ['authenticated commander','mothership ownership','module slot validation'], ['mothership_modules','motherships','player_resources'], ['ready','empty','insufficient-resource','success','error']),
    'exploration' => $make('Exploration', ['Available expeditions','Travel time','Discovery risk','Mission results'], 'exploration yield = distance × ship science × biome rarity', ['Explore planet','Recall expedition','Review discovery'], ['authenticated commander','mothership readiness','target validated'], ['motherships','planet_explorations','universe_planets'], ['ready','protected','insufficient-resource','cooldown','success','error']),
    'race' => $make('Race Selection', ['Available races','Faction bonuses','Compatibility rules','Selection result'], 'race modifier = selected race profile applied to production, combat, and growth', ['Select race','Compare race'], ['authenticated commander','selection cooldown','account eligibility'], ['races','players','race_modifiers'], ['ready','protected','cooldown','success','error']),
    'vacation' => $make('Vacation Mode', ['Current protection','Activation rules','Cooldown','Return schedule'], 'vacation protection = account lock + fleet lock + colony production pause', ['Enable vacation','Schedule return','Cancel request'], ['authenticated commander','no active combat','cooldown satisfied'], ['vacation_states','protection_states','players'], ['ready','protected','cooldown','success','error']),
    'ascension' => $make('Ascension', ['Eligibility','Glory balance','Tier transition','Permanent bonuses'], 'ascension reward = completed tier mastery × glory multiplier', ['Check eligibility','Ascend','Review rewards'], ['authenticated commander','tier maximum','glory requirement'], ['ascension_states','ascensions','glory_reputation','progression_states'], ['ready','locked','insufficient-resource','success','error']),
    'galaxies' => $make('Galaxy Map', ['Galaxy index','Sector distribution','Realm ownership','Map filters'], 'galaxy visibility = discovered sectors + scan permissions + coordinate scope', ['Select galaxy','Open sector','Refresh map'], ['authenticated commander','coordinate access'], ['universe_galaxies','universe_sectors','target_realms'], ['ready','empty','protected','error']),
    'sectors' => $make('Sector Map', ['Sector systems','Owner signals','Travel lanes','Scan results'], 'sector scan = sensor range × mothership science × scan technology', ['Select sector','Open system','Scan sector'], ['authenticated commander','sector visibility','scan cooldown'], ['universe_sectors','universe_solar_systems','motherships'], ['ready','empty','protected','cooldown','error']),
    'solar-systems' => $make('Solar Systems', ['System planets','Fleet lanes','Jump-gate status','Scan telemetry'], 'system access = coordinate validity + discovery state + gate availability', ['Open system','Scan system','Plot route'], ['authenticated commander','coordinate validation','fleet authority'], ['universe_solar_systems','universe_planets','universe_moons'], ['ready','empty','protected','error']),
    'universe-planets' => $make('Universe Planets', ['Planet catalogue','Biome profile','Colonization slots','Settlement preview'], 'colonization capacity = planet slots × infrastructure × life-support technology', ['Inspect planet','Colonize planet','Compare biome'], ['authenticated commander','colonization eligibility','resource validation'], ['universe_planets','player_colonies','planet_biomes','planet_bonuses'], ['ready','empty','protected','insufficient-resource','success','error']),
    'moons' => $make('Moon Registry', ['Known moons','Orbital bonuses','Jump-gate status','Construction options'], 'moon bonus = orbital class × infrastructure × gate technology', ['Inspect moon','Build jump gate','Compare orbit'], ['authenticated commander','moon ownership','resource validation'], ['universe_moons','universe_planets','mothership_modules'], ['ready','empty','protected','insufficient-resource','success','error']),
    'coordinates' => $make('Coordinate Search', ['Search form','Coordinate result','System ownership','Navigation actions'], 'coordinate lookup = validated galaxy : sector : system : slot tuple', ['Search coordinates','Open galaxy','Open sector','Open system'], ['authenticated commander','coordinate access','discovery filtering','ownership classification'], ['universe_galaxies','universe_sectors','universe_solar_systems','universe_planets','universe_discoveries','player_colonies'], ['ready','empty','error']),
];
