<?php
declare(strict_types=1);

$make = static function (
    string $purpose,
    array $workflow,
    array $validation,
    array $calculations,
    array $mutations,
    array $features,
    string $template,
    array $sections,
    array $components,
    string $responsive,
    array $services,
    array $reads,
    array $writes,
    array $actions
): array {
    return [
        'logic' => [
            'purpose' => $purpose,
            'workflow' => $workflow,
            'validation' => $validation,
            'calculations' => $calculations,
            'mutations' => $mutations,
        ],
        'features' => $features,
        'design' => [
            'template' => $template,
            'sections' => $sections,
            'components' => $components,
            'responsive' => $responsive,
        ],
        'systems' => [
            'services' => $services,
            'reads' => $reads,
            'writes' => $writes,
            'actions' => $actions,
        ],
    ];
};

$profiles = [
    'dashboard' => $make('Coordinate colony, economy, queues, fleets, alerts, and turn settlement.', ['load authoritative state','validate commander intent','settle bounded turn window','return refreshed state'], ['authenticated commander','CSRF token','RBAC permission','transaction boundary'], ['resource settlement','food and water upkeep','queue completion','fleet ETA'], ['player_resources','construction_queue','fleet_missions','game_events','rankings'], ['eight-resource HUD','colony life support','building and research queues','fleet mission board','universal progression','server feedback'], 'command-center', ['identity header','resource strip','colony overview','server actions','queues','life support','fleet control','progression','alerts'], ['resource-tile','metric-grid','action-panel','status-badge','data-table'], '12-column desktop grid collapses to stacked mobile panels', ['GameService','DashboardService','ProgressionService'], ['players','player_resources','player_colonies','construction_queue','fleet_missions','rankings','game_events'], ['player_resources','construction_queue','fleet_missions','rankings','game_events'], ['process_turns','choose_target','review_reports','progression_advance']),
    'details' => $make('Read commander identity, faction, rank, protection, and progression.', ['load commander','load faction and government','load rank and progression','render read-only profile'], ['authenticated commander','ownership scope'], ['combined faction modifier','rank score'], [], ['commander profile','race and government identity','rank summary','protection state','progression summary','session security'], 'account-details', ['profile','faction identity','progression','protection','security'], ['profile-metric','modifier-row','security-badge'], 'Two-column details collapse to one column', ['AccountService','ProgressionService'], ['players','races','government_types','rankings','player_progression','protection_states','glory_reputation'], [], ['read_profile','read_rank','read_protection']),
    'economy' => $make('Manage the eight-resource ledger and protected Naquadah vault.', ['load resource ledger','validate transfer amount','lock resource row','move balance transactionally','write audit event'], ['authenticated commander','CSRF token','positive amount','available or vault balance','RBAC permission'], ['available Naquadah','protected vault balance','eight-resource totals','transfer delta'], ['player_resources','game_audit_log'], ['eight-resource ledger','Naquadah vault','deposit','withdraw','balance validation','transaction feedback'], 'resource-vault', ['balance cards','resource ledger','transfer controls','server contract','feedback states'], ['resource-card','transfer-form','balance-row','validation-banner'], 'Resource cards flow from four columns to one column', ['GameService','EconomyService'], ['player_resources','game_settings'], ['player_resources','game_audit_log'], ['deposit','withdraw']),
    'breakdown' => $make('Explain production settlement by colony, faction, government, technology, biome, and upkeep.', ['load colony production','load modifiers','calculate gross output','calculate food water energy upkeep','render net settlement'], ['authenticated commander','owned colony scope'], ['base production × race modifier × government modifier × technology − upkeep','colony comparison','life-support efficiency'], [], ['income formula','modifier breakdown','colony comparison','food water energy upkeep','production forecast','read-only state'], 'income-breakdown', ['formula','modifier table','colony production','upkeep','feedback states'], ['formula-block','modifier-row','forecast-metric','comparison-table'], 'Formula and comparison sections stack on small screens', ['EconomyService','ColonyService'], ['player_resources','player_colonies','races','government_types','technologies','universe_planets'], [], ['read_income_breakdown','read_colony_comparison']),
    'stats' => $make('Aggregate military, defense, covert, anti-covert, readiness, and DefCon values.', ['load units and weapons','load technology and faction modifiers','calculate power totals','read protection and DefCon','render readiness'], ['authenticated commander','valid DefCon level for mutation'], ['units × base power × technology × race × government × planet bonus','readiness score','DefCon effect'], ['players','game_audit_log'], ['attack power','defense power','covert power','anti-covert power','readiness','DefCon control'], 'military-statistics', ['power totals','unit breakdown','technology modifiers','readiness','DefCon'], ['power-metric','modifier-table','defcon-selector','readiness-bar'], 'Stat grid reduces from four columns to one', ['MilitaryService','GameService'], ['player_resources','player_unit_stats','player_weapons','technologies','rankings','protection_states'], ['players','game_audit_log'], ['read_military_stats','set_defcon']),
    'targets' => $make('Select targets and preview combat, raid, covert, sabotage, and conquest operations.', ['load visible realms','verify protection','calculate operation cost','compare forces','submit chosen operation'], ['authenticated commander','attack turns','target ownership scope','protection rules','fleet or unit availability'], ['validated force comparison + technology + defense + deterministic resolver','operation cost','loot preview'], ['battles','battle_rounds','battle_reports','attack_logs','player_resources'], ['known realm search','protection badges','combat preview','operation cost','attack','raid','spy','sabotage'], 'target-board', ['filters','target rows','protection','combat preview','operation controls'], ['target-table','protection-badge','cost-preview','operation-buttons'], 'Target table becomes stacked target rows', ['CombatService','CovertService','TargetingService'], ['target_realms','players','rankings','protection_states','technologies'], ['battles','battle_rounds','battle_reports','attack_logs','player_resources'], ['combat','combat:raid','covert:spy','covert:sabotage']),
    'covert' => $make('Run reconnaissance, spy, and sabotage missions using agents and covert technology.', ['load agent pools','select mission type','calculate detection','resolve intelligence or damage','store report and cooldown'], ['authenticated commander','available agents','target visibility','cooldown','mission cost'], ['defender counter-intelligence − attacker agents − covert technology','detection chance','bounded sabotage damage'], ['covert_missions','spy_missions','sabotage_missions','intelligence_reports','game_events'], ['agent allocation','detection warning','target intelligence','reconnaissance','spy mission','sabotage mission','classified report'], 'covert-operations', ['agent allocation','detection meter','target intelligence','mission result'], ['mission-selector','agent-input','detection-meter','report-panel'], 'Mission controls and reports stack vertically', ['CovertService','IntelligenceService'], ['covert_agents','anti_covert_agents','target_realms','technologies'], ['covert_missions','spy_missions','sabotage_missions','intelligence_reports','game_events'], ['covert:recon','covert:spy','covert:sabotage']),
    'reports' => $make('Show battle, spy, sabotage, and system reports only to authorized recipients.', ['load recipient reports','classify payload','filter read state','open or mark report read','write audit state'], ['authenticated report recipient','recipient ownership','classification access'], ['recipient ownership + report classification + read status'], ['messages','game_audit_log'], ['unread count','battle outcomes','spy payloads','classified report view','mark read','report filters'], 'report-list', ['unread summary','report table','detail view','read state'], ['report-row','classification-badge','detail-panel','mark-read-button'], 'Report rows become expandable cards', ['ReportService','IntelligenceService'], ['battle_reports','attack_logs','intelligence_reports','messages'], ['messages','game_audit_log'], ['read_report','message_read']),
    'inventory' => $make('Manage owned weapons, quantities, durability, assignments, and effective power.', ['load catalogue','validate purchase or inspection','upsert inventory','calculate durability-adjusted power'], ['authenticated commander','weapon ownership','resource balance','positive quantity'], ['base power × durability × technology × race × government'], ['player_weapons','player_resources'], ['weapon catalogue','owned quantity','durability','assignment readiness','weapon purchase'], 'armory-inventory', ['catalogue','inventory','durability','assignment'], ['weapon-card','durability-meter','purchase-form','assignment-badge'], 'Weapon cards wrap into a single-column inventory', ['ArmoryService'], ['weapon_types','player_weapons','player_resources','technologies'], ['player_weapons','player_resources'], ['weapon_buy','read_weapon']),
    'market' => $make('List and buy resource, weapon, and mercenary market orders.', ['load orders','validate order fields','lock balance or order','settle trade','write market event'], ['authenticated trader','market turns','positive quantity','available balance','order ownership'], ['quantity × unit price + market fee'], ['market_orders','trade_contracts','player_resources','game_audit_log'], ['open orders','price history','order form','buy order','list order','settlement status'], 'market-exchange', ['orders','price history','order form','settlement'], ['order-table','price-badge','order-form','settlement-banner'], 'Market tables scroll or stack into order cards', ['MarketService'], ['market_orders','trade_contracts','player_resources','mercenary_types'], ['market_orders','trade_contracts','player_resources','game_audit_log'], ['market_list','market_buy','market_cancel']),
    'repair' => $make('Restore weapon durability using validated repair costs.', ['load damaged weapon','calculate missing durability','validate resources','lock weapon','restore durability transactionally'], ['weapon owner','positive durability gap','resource balance'], ['missing durability × weapon tier × maintenance factor'], ['player_weapons','player_resources','game_audit_log'], ['durability board','repair cost','resource check','repair result'], 'weapon-repair', ['damaged items','cost preview','confirmation','result'], ['durability-meter','repair-cost','confirmation-panel','result-banner'], 'Repair cards stack on mobile', ['ArmoryService'], ['player_weapons','weapon_types','player_resources'], ['player_weapons','player_resources','game_audit_log'], ['weapon_repair']),
    'training' => $make('Convert available population into specialized personnel and units.', ['load population pool','select unit category','validate quantity','deduct population and cost','update unit stats'], ['authenticated commander','untrained population','positive quantity','resource balance'], ['population conversion − training cost + production bonus'], ['player_resources','player_unit_stats','game_events'], ['unit categories','quantity input','training queue','population conversion','production upgrade'], 'training-board', ['unit pool','training controls','cost preview','queue/result'], ['unit-card','quantity-input','cost-preview','queue-row'], 'Training cards stack with full-width controls', ['TrainingService','GameService'], ['player_resources','player_unit_stats','technologies'], ['player_resources','player_unit_stats','game_events'], ['train','upgrade_up']),
    'upgrade' => $make('Increase unit production capacity and show next-level effects.', ['load current level','calculate next cost','validate resources','queue upgrade','apply completion effect'], ['authenticated commander','positive current level','resource balance','level cap'], ['base cost × growth rate ^ current level'], ['player_resources','construction_queue','game_audit_log'], ['current production','next-level cost','queue status','upgrade effects','production preview'], 'upgrade-card', ['current level','next cost','modifier preview','confirmation'], ['level-card','cost-table','effect-preview','queue-badge'], 'Upgrade card becomes full-width', ['TrainingService','QueueService'], ['player_resources','construction_queue','technologies'], ['player_resources','construction_queue','game_audit_log'], ['upgrade_up']),
    'technology' => $make('Research offense, defense, covert, and anti-covert technology branches.', ['load technology tree','check prerequisites','calculate cost','queue research','apply completed effect'], ['authenticated researcher','prerequisites','research queue','resource balance','level cap'], ['base cost × growth ^ current level'], ['player_technologies','construction_queue','player_resources'], ['technology tree','branch filters','prerequisites','level and cost','research queue','effect preview'], 'technology-tree', ['branch tabs','technology cards','prerequisites','cost','queue'], ['tech-card','branch-tabs','prerequisite-list','research-queue'], 'Branch tabs scroll and cards stack', ['TechnologyService','QueueService'], ['technologies','technology_prerequisites','player_technologies','player_resources','construction_queue'], ['player_technologies','construction_queue','player_resources'], ['technology']),
    'rankings' => $make('Compare economy, military, covert, progression, and colony scores.', ['load ranking snapshot','calculate or refresh scores','filter leaderboard','open public profile'], ['authenticated commander','public profile field policy'], ['weighted economy + military + covert + progression + colony value'], ['rankings','rank_snapshots'], ['overall leaderboard','military leaderboard','economy leaderboard','covert leaderboard','historical snapshots'], 'ranking-table', ['filters','leaderboard','score breakdown','snapshots'], ['ranking-table','score-badge','filter-tabs','snapshot-selector'], 'Leaderboard columns collapse into ranked cards', ['RankingService','AccountService'], ['rankings','rank_snapshots','players','player_resources'], ['rankings','rank_snapshots'], ['refresh_rankings','read_profile']),
    'social' => $make('Create alliances, manage members, and coordinate diplomacy.', ['load alliance state','validate role or invitation','create membership or proposal','notify participants'], ['authenticated commander','alliance role','membership rules','target ownership'], ['relation proposal lifecycle'], ['alliances','alliance_members','diplomacy_relations','diplomacy_actions','player_notifications'], ['alliance identity','member roles','join and leave','diplomacy proposals','shared activity'], 'social-command', ['alliance','members','diplomacy','activity'], ['member-table','role-badge','proposal-form','activity-feed'], 'Member table becomes stacked rows', ['AllianceService','DiplomacyService','NotificationService'], ['alliances','alliance_members','diplomacy_relations','diplomacy_actions','player_notifications'], ['alliances','alliance_members','diplomacy_relations','diplomacy_actions','player_notifications'], ['alliance_create','alliance_join','diplomacy_propose']),
    'messages' => $make('Send, receive, read, and block commander messages.', ['load inbox','validate sender and recipient','apply content policy','write message and notification','update read or blacklist state'], ['authenticated commander','recipient exists','blacklist policy','message ownership'], ['unread count'], ['messages','blacklists','player_notifications'], ['inbox','unread count','compose','mark read','blacklist','notifications'], 'message-center', ['inbox','compose','read state','blacklist'], ['message-list','compose-form','unread-badge','blacklist-control'], 'Message rows become conversation cards', ['MessageService','NotificationService'], ['messages','blacklists','player_notifications','players'], ['messages','blacklists','player_notifications'], ['message','message_read','blacklist']),
    'planets' => $make('Manage colonies, biomes, defenses, population, and life support.', ['load planet portfolio','load biome and bonuses','validate colony ownership','process exploration or defense action','render life support'], ['authenticated colony owner','planet occupancy','habitability','resource balance'], ['production − food/water upkeep + morale and habitability modifiers'], ['player_colonies','planet_defenses','universe_planets','game_events'], ['planet portfolio','biome modifiers','defenses','population','food and water','exploration','colonization'], 'colony-grid', ['planet selector','population','biome','life support','defenses'], ['planet-card','biome-badge','life-support-meter','defense-table'], 'Planet cards use one column on mobile', ['ColonyService','PlanetService','ExplorationService'], ['player_planets','player_colonies','planet_bonuses','planet_defenses','universe_planets'], ['player_colonies','planet_defenses','universe_planets','game_events'], ['explore','colonize_planet','planet_defense']),
    'ship' => $make('Command the mothership hull, hangars, shields, weapons, and modules.', ['load mothership','select upgrade','validate module prerequisite','lock resources','queue or apply upgrade'], ['mothership owner','module prerequisite','resource balance','capacity cap'], ['hull + modules + weapons + shields + fleet capacity'], ['motherships','mothership_modules','player_resources','construction_queue'], ['hull','weapons and shields','hangars','modules','capacity','upgrade queue'], 'mothership-command', ['hull','weapons','hangars','modules'], ['ship-stat','module-card','capacity-meter','upgrade-form'], 'Ship systems stack into full-width modules', ['MothershipService','QueueService'], ['motherships','mothership_modules','player_resources','construction_queue'], ['motherships','mothership_modules','player_resources','construction_queue'], ['mothership_upgrade']),
    'exploration' => $make('Explore systems, planets, moons, anomalies, and discovery rewards.', ['load sensor range','validate mission capacity','calculate travel risk','resolve anomaly','record discovery'], ['exploration-capable commander','mothership readiness','cooldown','target visibility'], ['exploration level + sensor bonus + anomaly rate − travel risk'], ['universe_discoveries','game_events'], ['discovery range','system scan','anomaly chance','discovery rewards','travel risk'], 'exploration-board', ['range','system scan','anomaly','rewards'], ['scan-form','risk-meter','discovery-card','mission-status'], 'Exploration panels stack vertically', ['ExplorationService','MothershipService'], ['motherships','universe_solar_systems','universe_planets','universe_moons'], ['universe_discoveries','game_events'], ['explore']),
    'account' => $make('Manage race, government, vacation, protection, and account security.', ['load faction options','validate selection','save faction history','apply protection state','render security controls'], ['authenticated commander','valid race and government','vacation rules','protection rules'], ['race modifier × government modifier'], ['players','player_government_history','vacation_states','protection_states'], ['race selection','government selection','vacation mode','protection','session security'], 'account-settings', ['race selector','government selector','vacation','protection','security'], ['faction-selector','modifier-preview','vacation-toggle','security-panel'], 'Settings sections stack on mobile', ['AccountService','ProtectionService'], ['players','races','government_types','protection_states','vacation_states'], ['players','player_government_history','vacation_states','protection_states'], ['select_registration_faction','change_race','vacation']),
    'progression' => $make('Track universal tier and level progression, Glory, Reputation, and ascension.', ['load progression state','check thresholds','calculate cost or eligibility','advance or ascend transactionally','write history'], ['authenticated commander','experience threshold','tier and level cap','resource or Glory cost'], ['experience thresholds','21 tiers × 23 levels','ascension eligibility'], ['player_progression','glory_reputation','ascension_states','ascensions','game_audit_log'], ['experience','tier and level','Glory','Reputation','ascension requirements','progression history'], 'progression-panel', ['requirements','tier and level','Glory/Reputation','ascension preview','history'], ['progress-bar','tier-badge','requirement-list','ascension-preview'], 'Progression metrics stack on mobile', ['ProgressionService','AscensionService'], ['player_progression','glory_reputation','rank_definitions','ascension_states','ascensions'], ['player_progression','glory_reputation','ascension_states','ascensions','game_audit_log'], ['progression_advance','ascend']),
    'galaxies' => $make('Browse galaxy density, sector overview, and travel risk.', ['select galaxy','load sectors','calculate density and risk','open sector'], ['authenticated commander','valid galaxy identifier'], ['sector danger × system volatility × distance modifier'], [], ['galaxy selector','star density','sector overview','travel risk'], 'galaxy-map', ['galaxy selector','density','sectors','risk'], ['selector','density-metric','sector-list','risk-badge'], 'Map lists become stacked rows', ['UniverseService'], ['universe_galaxies','universe_sectors'], [], ['universe_galaxies']),
    'sectors' => $make('Inspect sector class, danger, resource modifiers, and anomaly rate.', ['select sector','load systems','calculate sector output','filter by risk'], ['authenticated commander','valid sector identifier'], ['base output × resource modifier; anomaly rate drives events'], [], ['sector class','danger level','resource modifier','anomaly rate'], 'sector-map', ['sector selector','danger','resource modifier','anomalies'], ['sector-card','danger-meter','modifier-badge','system-list'], 'Sector cards stack on mobile', ['UniverseService'], ['universe_sectors','universe_solar_systems'], [], ['universe_sectors']),
    'solar-systems' => $make('Browse star class, orbit map, planet slots, and anomalies.', ['open system','load orbit map','scan anomaly','calculate travel'], ['authenticated commander','valid system identifier','exploration capacity'], ['base travel × system modifier × sector danger'], ['universe_discoveries','game_events'], ['star class','orbit map','planet slots','anomaly scan'], 'solar-system-map', ['star','orbits','planet slots','anomaly'], ['orbit-list','planet-slot','star-badge','scan-control'], 'Orbit list becomes stacked planets', ['UniverseService','ExplorationService'], ['universe_solar_systems','universe_planets','universe_discoveries'], ['universe_discoveries','game_events'], ['system_map','explore']),
    'universe-planets' => $make('Inspect planet class, biome, habitability, resource modifiers, and colony status.', ['inspect planet','load biome','calculate viability','validate colonization','create colony'], ['authenticated commander','colonization access','occupancy','habitability','resource balance'], ['habitability × biome × race × government × life support'], ['universe_planets','player_colonies','game_audit_log'], ['planet class','biome','habitability','resource modifiers','colony status','colonization'], 'universe-planet', ['planet identity','biome','habitability','resources','colony status'], ['planet-detail','biome-card','habitability-meter','colonize-form'], 'Planet details stack vertically', ['UniverseService','ColonyService'], ['universe_planets','universe_moons','player_colonies'], ['universe_planets','player_colonies','game_audit_log'], ['planet_details','colonize_planet']),
    'moons' => $make('Inspect moon class, sensor bonus, jump gate, and orbit relationship.', ['inspect moon','load parent planet','calculate utility','validate jump-gate upgrade'], ['authenticated commander','moon access','colony or mothership ownership'], ['sensor bonus + jump-gate level + moon resource modifiers'], ['universe_moons','mothership_modules','player_colonies'], ['moon registry','moon class','sensor bonus','jump-gate level','orbit relationship'], 'moon-registry', ['moon identity','sensor','jump gate','orbit','assignment'], ['moon-card','sensor-meter','gate-upgrade','orbit-badge'], 'Moon cards stack on mobile', ['UniverseService','MothershipService'], ['universe_moons','universe_planets','player_colonies','mothership_modules'], ['mothership_modules','player_colonies'], ['moon_details','mothership_upgrade']),
    'coordinates' => $make('Validate and resolve galaxy:sector:system:orbit coordinates.', ['validate coordinate input','find galaxy','find sector','find system','find planet or moon'], ['authenticated commander','coordinate format','coordinate bounds'], ['coordinate = galaxy:sector:system:orbit'], [], ['coordinate input','galaxy result','system result','planet result','moon result'], 'coordinate-search', ['input','galaxy','sector','system','planet/moon'], ['coordinate-form','result-path','coordinate-badge','detail-link'], 'Result path wraps into vertical steps', ['UniverseService'], ['universe_galaxies','universe_sectors','universe_solar_systems','universe_planets','universe_moons'], [], ['coordinate_lookup']),
];

return ['profiles' => $profiles];
