<?php
declare(strict_types=1);
return [
 'dashboard'=>['template'=>'command-center','sections'=>['resource strip','turn status','income summary','recent events'],'states'=>['loading','ready','empty','error'],'primary_action'=>'process_turns'],
 'economy'=>['template'=>'resource-management','sections'=>['balance cards','production rates','vault transfer','DefCon selector'],'states'=>['ready','insufficient-funds','cooldown'],'primary_action'=>'deposit'],
 'details'=>['template'=>'account-details','sections'=>['profile identity','rank and race','protection','audit history'],'states'=>['ready','restricted'],'primary_action'=>null],
 'breakdown'=>['template'=>'formula-breakdown','sections'=>['income formula','modifier table','forecast','event history'],'states'=>['ready','no-data'],'primary_action'=>null],
 'stats'=>['template'=>'statistics','sections'=>['attack','defense','covert','ranking delta'],'states'=>['ready','no-data'],'primary_action'=>null],
 'targets'=>['template'=>'target-table','sections'=>['filters','target rows','action buttons','protection badges'],'states'=>['loading','ready','protected','empty'],'primary_action'=>'combat'],
 'covert'=>['template'=>'mission-form','sections'=>['mission type','agent quantity','detection warning','result report'],'states'=>['ready','validation-error','detected','success'],'primary_action'=>'covert'],
 'reports'=>['template'=>'report-list','sections'=>['unread count','report table','detail drawer','mark-read control'],'states'=>['loading','ready','empty'],'primary_action'=>'message_read'],
 'inventory'=>['template'=>'inventory-table','sections'=>['weapon rows','durability','purchase form','repair action'],'states'=>['ready','insufficient-funds','broken'],'primary_action'=>'weapon_buy'],
 'market'=>['template'=>'market-board','sections'=>['order book','listing form','purchase form','transaction notice'],'states'=>['ready','empty','insufficient-funds','sold-out'],'primary_action'=>'market_list'],
 'repair'=>['template'=>'repair-panel','sections'=>['damaged items','repair cost','confirmation','result banner'],'states'=>['ready','no-damage','insufficient-funds'],'primary_action'=>'weapon_repair'],
 'training'=>['template'=>'training-board','sections'=>['unit pool','training controls','cost preview','queue/result'],'states'=>['ready','insufficient-units','invalid-quantity'],'primary_action'=>'train'],
 'upgrade'=>['template'=>'upgrade-card','sections'=>['current level','next cost','modifier preview','confirmation'],'states'=>['ready','insufficient-funds','max-level'],'primary_action'=>'upgrade_up'],
 'technology'=>['template'=>'technology-tree','sections'=>['category tabs','technology cards','level and cost','upgrade result'],'states'=>['ready','locked','insufficient-funds'],'primary_action'=>'technology'],
 'planets'=>['template'=>'planet-grid','sections'=>['planet cards','bonuses','defenses','exploration controls'],'states'=>['ready','unknown-planet','protected'],'primary_action'=>'explore'],
 'settlement'=>['template'=>'settlement-power-grid','sections'=>['field grid','power output','power consumption','construction queue','building catalog'],'states'=>['ready','empty','insufficient-resource','success','error'],'primary_action'=>'settlement_build'],
 'ship'=>['template'=>'mothership-grid','sections'=>['hull stats','module cards','upgrade costs','exploration status'],'states'=>['ready','insufficient-funds','cooldown'],'primary_action'=>'mothership_upgrade'],
 'exploration'=>['template'=>'exploration-panel','sections'=>['coordinates','scan result','planet card','mission history'],'states'=>['ready','scanning','success','failure'],'primary_action'=>'explore'],
 'social'=>['template'=>'social-workspace','sections'=>['alliance summary','member table','join/create forms','activity log'],'states'=>['ready','no-alliance','permission-denied'],'primary_action'=>'alliance_join'],
 'messages'=>['template'=>'message-center','sections'=>['inbox','compose form','read state','blacklist controls'],'states'=>['ready','empty','validation-error'],'primary_action'=>'message'],
 'rankings'=>['template'=>'ranking-table','sections'=>['ranking tabs','player rows','score delta','refresh status'],'states'=>['ready','refreshing','no-data'],'primary_action'=>'refresh_rankings'],
 'account'=>['template'=>'account-settings','sections'=>['race selector','vacation controls','protection','supporter status'],'states'=>['ready','restricted','cooldown'],'primary_action'=>'change_race'],
 'progression'=>['template'=>'progression-panel','sections'=>['requirements','Glory/Reputation','Ascension preview','confirmation'],'states'=>['ready','ineligible','success'],'primary_action'=>'ascend'],
 'colonies'=>['template'=>'colony-grid','sections'=>['colony selector','population','food/water','morale'],'states'=>['ready','shortage','empty'],'primary_action'=>'colony_turn'],
 'life-support'=>['template'=>'life-support','sections'=>['food meter','water meter','hourly formula','shortage banner'],'states'=>['ready','shortage','capacity-full'],'primary_action'=>'colony_turn'],
 'buildings'=>['template'=>'construction-queue','sections'=>['building cards','cost preview','active queue','completion timers'],'states'=>['ready','queued','insufficient-funds'],'primary_action'=>'queue_building'],
 'research'=>['template'=>'research-queue','sections'=>['research tree','level cards','active queue','completion timers'],'states'=>['ready','locked','queued'],'primary_action'=>'queue_research'],
 'fleet-overview'=>['template'=>'fleet-hangar','sections'=>['fleet inventory','cargo','power totals','mission shortcut'],'states'=>['ready','empty'],'primary_action'=>null],
 'missions'=>['template'=>'fleet-dispatch','sections'=>['source selector','target selector','mission type','payload and travel time'],'states'=>['ready','invalid-target','launched','blocked'],'primary_action'=>'launch_mission'],
 'mission-log'=>['template'=>'mission-log','sections'=>['status filters','mission rows','ETA','cancel/return controls'],'states'=>['ready','empty','failed'],'primary_action'=>null],
 'events'=>['template'=>'world-events','sections'=>['active banners','event details','join controls','reward summary'],'states'=>['active','scheduled','ended'],'primary_action'=>'event_join'],
 'galaxies'=>['template'=>'galaxy-map','sections'=>['galaxy selector','sector list','danger and density','discovery status'],'states'=>['ready','loading','empty'],'primary_action'=>'universe_galaxies'],
 'sectors'=>['template'=>'sector-map','sections'=>['sector overview','system list','resource modifier','anomaly rate'],'states'=>['ready','locked','empty'],'primary_action'=>'universe_sectors'],
 'solar-systems'=>['template'=>'solar-system-map','sections'=>['star profile','orbital lanes','planet slots','scan controls'],'states'=>['ready','scanning','undiscovered'],'primary_action'=>'system_map'],
 'universe-planets'=>['template'=>'universe-planet-detail','sections'=>['coordinate header','biome and class','habitability and slots','resource modifiers','moon list','colonization form'],'states'=>['ready','occupied','uninhabitable','colonizable'],'primary_action'=>'planet_details'],
 'moons'=>['template'=>'moon-detail','sections'=>['parent planet','moon classification','sensor and gate stats','moon facilities'],'states'=>['ready','unoccupied','gate-locked'],'primary_action'=>'moon_details'],
 'coordinates'=>['template'=>'coordinate-search','sections'=>['coordinate form','galaxy result','system result','planet result'],'states'=>['ready','invalid-coordinate','not-found'],'primary_action'=>'coordinate_lookup'],
];
