<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/auth.php';
require_once __DIR__ . '/../config/settings.php';
require_once __DIR__ . '/FormulaService.php';
require_once __DIR__ . '/Rules.php';

final class GameService {
    private PDO $pdo;
    public function __construct(?PDO $pdo = null) { $this->pdo = $pdo ?? db() ?? throw new RuntimeException('Database unavailable'); }
    private function setting(string $key, int $fallback): int { $stmt=$this->pdo->prepare('SELECT setting_value FROM game_settings WHERE setting_key=?'); $stmt->execute([$key]); $value=$stmt->fetchColumn(); return $value !== false ? (int)$value : $fallback; }
    private function resources(int $playerId, bool $lock = false): array {
        $sql='SELECT * FROM player_resources WHERE player_id=?' . ($lock ? ' FOR UPDATE' : ''); $stmt=$this->pdo->prepare($sql); $stmt->execute([$playerId]); $row=$stmt->fetch(); if (!$row) throw new RuntimeException('Player resources not found'); return $row;
    }
    private function player(int $playerId, bool $lock = false): array {
        $sql='SELECT p.*,r.name AS race FROM players p JOIN races r ON r.id=p.race_id WHERE p.id=?' . ($lock ? ' FOR UPDATE' : ''); $stmt=$this->pdo->prepare($sql); $stmt->execute([$playerId]); $row=$stmt->fetch(); if (!$row) throw new RuntimeException('Player not found'); return $row;
    }
    private function event(int $playerId, string $type, ?string $entityType, ?int $entityId, array $payload): void { $stmt=$this->pdo->prepare('INSERT INTO game_events (player_id,event_type,entity_type,entity_id,payload) VALUES (?,?,?,?,?)'); $stmt->execute([$playerId,$type,$entityType,$entityId,json_encode($payload,JSON_THROW_ON_ERROR)]); }
    public function processTurns(int $playerId, ?DateTimeImmutable $now=null): array {
        $now=$now ?? new DateTimeImmutable('now'); $this->pdo->beginTransaction();
        try {
            $player=$this->player($playerId,true); $resources=$this->resources($playerId,true); $interval=$this->setting('turn_interval_seconds',1800); $threshold=$this->setting('turn_generation_threshold',4000); $max=$this->setting('turn_max_storage',10000);
            $last=$player['last_turn_at'] ? new DateTimeImmutable($player['last_turn_at']) : $now; $elapsed=max(0,$now->getTimestamp()-$last->getTimestamp()); $due=intdiv($elapsed,$interval); $turns=min($due,max(0,$max-(int)$resources['attack_turns']));
            if ($turns>0 && (int)$resources['attack_turns'] < $threshold) {
                $untrained=(int)$resources['untrained_units'] + ((int)$resources['unit_production']*$turns);
                $income=((int)$resources['untrained_units']*20 + ((int)$resources['miners']+(int)$resources['lifers'])*80) * $turns;
                if ($player['race']==='Goa\'uld') $income=(int)round($income*1.25);
                $income=(int)round($income*(1-([0=>0,1=>.10,2=>.20,3=>.40,4=>.70][(int)$player['defcon_level']] ?? 0)));
                $this->pdo->prepare('UPDATE player_resources SET attack_turns=LEAST(?,attack_turns+?),untrained_units=untrained_units+?,naquadah=naquadah+? WHERE player_id=?')->execute([$max,$turns,$untrained,$income,$playerId]);
                $newLast=$last->modify('+' . ($due*$interval) . ' seconds')->format('Y-m-d H:i:s'); $this->pdo->prepare('UPDATE players SET last_turn_at=? WHERE id=?')->execute([$newLast,$playerId]); $this->event($playerId,'turn_processed',null,null,['turns'=>$turns,'income'=>$income]);
            }
            $this->pdo->commit(); return ['turns'=>$turns,'income'=>$income ?? 0];
        } catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
    public function deposit(int $playerId,int $amount):void{$this->moveBank($playerId,$amount,true);}
    public function withdraw(int $playerId,int $amount):void{$this->moveBank($playerId,$amount,false);}
    private function moveBank(int $playerId,int $amount,bool $deposit):void{if($amount<1)throw new InvalidArgumentException('Amount must be positive');$this->pdo->beginTransaction();try{$r=$this->resources($playerId,true);if($deposit){if((int)$r['naquadah']<$amount)throw new RuntimeException('Not enough available Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-?,banked_naquadah=banked_naquadah+? WHERE player_id=?')->execute([$amount,$amount,$playerId]);}else{if((int)$r['banked_naquadah']<$amount)throw new RuntimeException('Not enough banked Naquadah');$this->pdo->prepare('UPDATE player_resources SET banked_naquadah=banked_naquadah-?,naquadah=naquadah+? WHERE player_id=?')->execute([$amount,$amount,$playerId]);}$this->event($playerId,$deposit?'naquadah_deposited':'naquadah_withdrawn','player_resources',$playerId,['amount'=>$amount]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function changeRace(int $playerId,int $raceId):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT name FROM races WHERE id=?');$s->execute([$raceId]);if(!$s->fetch())throw new RuntimeException('Race not found');$this->pdo->prepare('UPDATE players SET race_id=? WHERE id=?')->execute([$raceId,$playerId]);$this->event($playerId,'race_changed','race',$raceId,['race_id'=>$raceId]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function train(int $playerId,string $type,int $quantity): void {
        if ($quantity<1) throw new InvalidArgumentException('Quantity must be positive'); $allowed=['miners','attack_units','defense_units','spies','anti_spies']; if(!in_array($type,$allowed,true)) throw new InvalidArgumentException('Invalid training type');
        $this->pdo->beginTransaction(); try{$r=$this->resources($playerId,true);if((int)$r['untrained_units']<$quantity)throw new RuntimeException('Not enough untrained units');$this->pdo->prepare("UPDATE player_resources SET untrained_units=untrained_units-?,{$type}={$type}+? WHERE player_id=?")->execute([$quantity,$quantity,$playerId]);$this->event($playerId,'units_trained','player_resources', $playerId,['type'=>$type,'quantity'=>$quantity]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
    public function upgradeUnitProduction(int $playerId): int {
        $this->pdo->beginTransaction(); try{$r=$this->resources($playerId,true);$cost=((int)$r['unit_production']*5000)+10000;if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-?,unit_production=unit_production+1 WHERE player_id=?')->execute([$cost,$playerId]);$this->event($playerId,'unit_production_upgraded','player_resources',$playerId,['cost'=>$cost]);$this->pdo->commit();return $cost;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
    public function buyTechnology(int $playerId,string $key): int {
        $this->pdo->beginTransaction(); try{$stmt=$this->pdo->prepare('SELECT * FROM technologies WHERE technology_key=? FOR UPDATE');$stmt->execute([$key]);$tech=$stmt->fetch();if(!$tech)throw new RuntimeException('Technology not found');$stmt=$this->pdo->prepare('SELECT * FROM player_technologies WHERE player_id=? AND technology_key=? FOR UPDATE');$stmt->execute([$playerId,$key]);$owned=$stmt->fetch();$level=(int)($owned['level']??0);$cost=(int)round((int)$tech['base_cost']*pow((float)$tech['cost_growth'],$level));$r=$this->resources($playerId,true);if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah');if($owned)$this->pdo->prepare('UPDATE player_technologies SET level=level+1,next_cost=? WHERE id=?')->execute([$cost,$owned['id']]);else$this->pdo->prepare('INSERT INTO player_technologies (player_id,technology_key,technology_name,category,level,next_cost,technology_id) VALUES (?,?,?,?,?,?,?)')->execute([$playerId,$key,$tech['name'],$tech['category'],1,$cost,$tech['id']]);$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->event($playerId,'technology_upgraded','technology',$tech['id'],['key'=>$key,'level'=>$level+1,'cost'=>$cost]);$this->pdo->commit();return $cost;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
    public function buyWeapon(int $playerId,int $weaponTypeId,int $quantity):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT price,max_durability FROM weapon_types WHERE id=?');$s->execute([$weaponTypeId]);$weapon=$s->fetch();if(!$weapon||$quantity<1)throw new RuntimeException('Weapon not found');$cost=(int)$weapon['price']*$quantity;$r=$this->resources($playerId,true);if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO player_weapons(player_id,weapon_type_id,quantity,durability) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity),durability=VALUES(durability)')->execute([$playerId,$weaponTypeId,$quantity,$weapon['max_durability']]);$this->event($playerId,'weapon_purchased','weapon_type',$weaponTypeId,['quantity'=>$quantity,'cost'=>$cost]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function repairWeapons(int $playerId,int $weaponId):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT pw.quantity,pw.durability,wt.max_durability FROM player_weapons pw JOIN weapon_types wt ON wt.id=pw.weapon_type_id WHERE pw.id=? AND pw.player_id=? FOR UPDATE');$s->execute([$weaponId,$playerId]);$w=$s->fetch();if(!$w)throw new RuntimeException('Weapon inventory not found');$damage=max(0,(int)$w['max_durability']-(int)$w['durability']);$cost=$damage*10;$r=$this->resources($playerId,true);if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('UPDATE player_weapons SET durability=? WHERE id=?')->execute([(int)$w['max_durability'],$weaponId]);$this->event($playerId,'weapons_repaired','player_weapons',$weaponId,['cost'=>$cost]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function upgradeMothership(int $playerId,string $module):int{$allowed=['hull_level','volley_bays','shield_bays','fleet_hangars','weapons_power','shields_power','exploration_level'];if(!in_array($module,$allowed,true))throw new InvalidArgumentException('Invalid mothership module');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM motherships WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);$ship=$s->fetch();if(!$ship)throw new RuntimeException('Mothership not found');$current=(int)$ship[$module];$cost=25000+($current*10000);$r=$this->resources($playerId,true);if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare("UPDATE motherships SET {$module}={$module}+1 WHERE player_id=?")->execute([$playerId]);$this->event($playerId,'mothership_upgraded','mothership',$ship['id'],['module'=>$module,'cost'=>$cost]);$this->pdo->commit();return $cost;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function resolveCombat(int $attackerId,int $defenderId,string $action,int $turns): array {
        if($turns<1||$turns>15)throw new InvalidArgumentException('Invalid combat request');Rules::cannotFarm($this->pdo,$attackerId,$defenderId);$this->pdo->beginTransaction();try{$a=$this->player($attackerId,true);$d=$this->player($defenderId,true);$ar=$this->resources($attackerId,true);$dr=$this->resources($defenderId,true);$now=new DateTimeImmutable('now');foreach([$a,$d] as $p){if(($p['vacation_until']&&new DateTimeImmutable($p['vacation_until'])>$now)||($p['protected_until']&&new DateTimeImmutable($p['protected_until'])>$now))throw new RuntimeException('Target is protected');}$scoreA=((int)$ar['attack_units']*5)+(int)$ar['spies'];$scoreD=((int)$dr['defense_units']*5)+(int)$dr['anti_spies'];$scoreA=(int)round($scoreA*(1+($a['race']==='Tau\'ri'?.25:0)));$scoreD=(int)round($scoreD*(1+($d['race']==='Asgard'?.25:0)));$scoreA*=max(1,$turns);$win=$scoreA>$scoreD;$loot=$win?min((int)$dr['naquadah'],(int)round($dr['naquadah']*.10)):0;$ac=$win?max(1,(int)round((int)$ar['attack_units']*.03)):max(1,(int)round((int)$ar['attack_units']*.06));$dc=$win?max(1,(int)round((int)$dr['defense_units']*.06)):max(1,(int)round((int)$dr['defense_units']*.03));$this->pdo->prepare('UPDATE player_resources SET attack_turns=attack_turns-?,attack_units=GREATEST(0,attack_units-?) WHERE player_id=?')->execute([$turns,$ac,$attackerId]);$this->pdo->prepare('UPDATE player_resources SET defense_units=GREATEST(0,defense_units-?),naquadah=naquadah-? WHERE player_id=?')->execute([$dc,$loot,$defenderId]);if($loot)$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah+? WHERE player_id=?')->execute([$loot,$attackerId]);$winner=$win?$attackerId:$defenderId;$stmt=$this->pdo->prepare("INSERT INTO battles (attacker_id,defender_id,action_type,turns_spent,attacker_score,defender_score,winner_id,loot,attacker_casualties,defender_casualties) VALUES (?,?,?,?,?,?,?,?,?,?)");$stmt->execute([$attackerId,$defenderId,$action,$turns,$scoreA,$scoreD,$winner,$loot,$ac,$dc]);$battleId=(int)$this->pdo->lastInsertId();$text=$win?'Victory':'Defeat';$report=$this->pdo->prepare('INSERT INTO battle_reports (battle_id,recipient_id,report_text) VALUES (?,?,?)');$report->execute([$battleId,$attackerId,$text.' — loot: '.$loot]);$report->execute([$battleId,$defenderId,($win?'Realm attacked successfully':'Realm defended successfully').' — casualties: '.$dc]);$this->event($attackerId,'combat_resolved','battle',$battleId,['action'=>$action,'winner_id'=>$winner,'loot'=>$loot]);$this->pdo->commit();return ['battle_id'=>$battleId,'winner_id'=>$winner,'loot'=>$loot,'attacker_casualties'=>$ac,'defender_casualties'=>$dc];}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
    public static function defconCooldownState(?string $availableAt, ?DateTimeImmutable $now = null): array { $now=$now??new DateTimeImmutable('now'); if(!$availableAt)return ['state'=>'ready','available_at'=>null,'remaining_seconds'=>0]; $available=new DateTimeImmutable($availableAt); $remaining=max(0,$available->getTimestamp()-$now->getTimestamp()); return $remaining>0?['state'=>'cooldown','available_at'=>$available->format('Y-m-d H:i:s'),'remaining_seconds'=>$remaining]:['state'=>'ready','available_at'=>null,'remaining_seconds'=>0]; }
    public function setDefcon(int $playerId,int $level):void{$level=max(0,min(4,$level));$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);$cooldown=$this->pdo->prepare("SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key='defcon_change' FOR UPDATE");$cooldown->execute([$playerId]);$cooldownState=self::defconCooldownState($cooldown->fetchColumn());if($cooldownState['state']==='cooldown')throw new RuntimeException('DefCon change is on cooldown for '.$cooldownState['remaining_seconds'].' seconds.');$cost=$level*5000;if((int)$s->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah for DefCon change');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('UPDATE players SET defcon_level=? WHERE id=?')->execute([$level,$playerId]);$availableAt=(new DateTimeImmutable('now'))->modify('+300 seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns (player_id,cooldown_key,available_at) VALUES (?, 'defcon_change', ?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,$availableAt]);$this->event($playerId,'defcon_changed','player',$playerId,['level'=>$level,'cost'=>$cost,'cooldown_until'=>$availableAt]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function covertMission(int $attackerId,int $defenderId,string $type,int $agents): array {
        if($attackerId===$defenderId||$agents<1||!in_array($type,['recon','spy','sabotage'],true))throw new InvalidArgumentException('Invalid covert request');$this->pdo->beginTransaction();try{$a=$this->player($attackerId,true);$d=$this->player($defenderId,true);$ar=$this->resources($attackerId,true);$dr=$this->resources($defenderId,true);if((int)$ar['spies']<$agents)throw new RuntimeException('Not enough covert agents');$attack=(int)$ar['spies']*((int)($a['covert_level']??1));$def=(int)$dr['anti_spies']*((int)($d['anti_covert_level']??1));$success=$attack>($def+random_int(0,max(1,$def)));$detected=!$success&&random_int(0,100)<50;$result=$success?($type==='recon'?'Recon report acquired':($type==='spy'?'Spy operation succeeded':'Sabotage succeeded')):'Operation failed';$this->pdo->prepare('UPDATE player_resources SET spies=spies-? WHERE player_id=?')->execute([$agents,$attackerId]);$stmt=$this->pdo->prepare('INSERT INTO covert_missions (attacker_id,defender_id,mission_type,agents_sent,success,detected,result_text) VALUES (?,?,?,?,?,?,?)');$stmt->execute([$attackerId,$defenderId,$type,$agents,$success?1:0,$detected?1:0,$result]);$id=(int)$this->pdo->lastInsertId();if($success&&$type==='recon'){$this->pdo->prepare('INSERT INTO intelligence_reports (player_id,target_player_id,report_type,payload) VALUES (?,?,?,?)')->execute([$attackerId,$defenderId,'recon',json_encode(['defense_units'=>$dr['defense_units'],'attack_units'=>$dr['attack_units'],'naquadah'=>$dr['naquadah']])]);}$this->event($attackerId,'covert_mission','covert_mission',$id,['type'=>$type,'success'=>$success]);$this->pdo->commit();return ['mission_id'=>$id,'success'=>$success,'detected'=>$detected,'result'=>$result];}catch(Throwable $e){$this->pdo->rollBack();throw $e;}
    }
}
?>
