from pathlib import Path

path = Path('/home/ubuntu/stargatewars/game.php')
text = path.read_text()
if 'function coordinateSearchPage()' in text:
    print('coordinate renderer already present')
    raise SystemExit(0)
marker = 'function genericPage(){'
insert_at = text.index(marker)
new = r'''function coordinateSearchPage(){
const x=state.coordinate_search||{};const r=x.result||{};const n=x.navigation||{};const csrf=state.csrf||'';const visible=x.state==='ready';
document.getElementById('section').textContent='UNIVERSE';document.getElementById('title').textContent='Coordinate Search';document.getElementById('description').textContent='Coordinate Search — '+(x.formula||'coordinate lookup = validated galaxy : sector : system : slot tuple');
const result=visible?'<div class="card wide"><div class="eyebrow">COORDINATE RESULT</div><h2>'+esc(r.planet_name||'Planet found')+' <span class="badge good">VISIBLE</span></h2><div class="metric-grid"><div class="metric"><span>Coordinate</span><strong>'+esc(r.coordinate||x.coordinate||'—')+'</strong><small>Validated galaxy : sector : system : orbit tuple</small></div><div class="metric"><span>System ownership</span><strong>'+esc(r.ownership||'—')+'</strong><small>'+esc(r.system_name||'')+'</small></div><div class="metric"><span>Planet profile</span><strong>'+esc((r.planet_class||'—')+' / '+(r.biome||r.planet_type||'—'))+'</strong><small>Habitability '+fmt(r.habitability||0)+'</small></div></div><div class="row"><span>Galaxy / sector</span><strong>'+esc((r.galaxy_name||'—')+' / '+(r.sector_name||'—'))+'</strong></div><div class="row"><span>Navigation actions</span><span><button class="button coordinate-intent" data-route="galaxies">Open galaxy</button> <button class="button coordinate-intent" data-route="sectors">Open sector</button> <button class="button coordinate-intent" data-route="solar-systems">Open system</button></span></div></div>':x.state==='protected'?'<div class="card wide"><div class="eyebrow">COORDINATE RESULT</div><h2>'+esc(r.coordinate||x.coordinate||'—')+' <span class="badge warn">PROTECTED</span></h2><p class="permission">The tuple is structurally valid, but discovery or coordinate access does not permit detailed planet disclosure.</p><div class="row"><span>Galaxy / sector / system</span><strong>'+esc((r.galaxy_name||'—')+' / '+(r.sector_name||'—')+' / '+(r.system_name||'—'))+'</strong></div><div class="row"><span>Ownership signal</span><strong>'+esc(r.ownership||'CLASSIFIED')+'</strong></div></div>':x.state==='empty'?'<div class="card wide"><div class="eyebrow">COORDINATE RESULT</div><div class="empty"><strong>No planet found.</strong><p>No active universe planet matches the validated tuple '+esc(x.coordinate||'')+'.</p></div></div>':'';
document.getElementById('content').innerHTML='<div class="cc-grid"><div class="card side-card"><div class="eyebrow">SEARCH FORM</div><h2>Find coordinate</h2><form method="post" action="actions/game.php" class="action-form">'+csrf+'<input type="hidden" name="action" value="coordinate_lookup"><input type="hidden" name="redirect" value="coordinates"><label>Galaxy : Sector : System : Orbit<input name="coordinate" inputmode="numeric" pattern="[1-9][0-9]*:[1-9][0-9]*:[1-9][0-9]*:[1-9][0-9]*" placeholder="1:1:1:3" value="'+esc(x.coordinate||'')+'" required></label><button class="button dark" type="submit">Search coordinates</button></form><p class="permission">Only positive numeric tuples are accepted. Each hierarchy level is checked server-side before any result is returned.</p></div>'+result+'<div class="card wide"><div class="eyebrow">SYSTEM OWNERSHIP</div><h2>Visibility policy</h2><div class="row"><span>Coordinate scope</span><strong>'+esc(n.galaxy?('galaxy:'+n.galaxy+':sector:'+n.sector):'validated tuple')+'</strong></div><div class="row"><span>Discovery rule</span><strong>Owned colony or discovered system</strong></div><div class="row"><span>Server action</span><span class="badge">coordinate_lookup</span></div></div><div class="card wide"><div class="eyebrow">FEEDBACK STATES</div><h2>Result handling</h2>'+['ready','empty','error'].map(s=>'<div class="row"><span>'+s+'</span><span class="badge">HANDLED</span></div>').join('')+'</div><div class="card wide"><div class="eyebrow">NAVIGATION STATUS</div><h2>Coordinate route ready</h2><p class="permission">Enter a galaxy, sector, system, and orbit to locate a known world. The navigation system checks each level and returns only information your commander is allowed to see.</p><span class="badge good">SERVER VERIFIED</span> <span class="badge">DISCOVERY FILTER ACTIVE</span><details style="margin-top:14px"><summary>Technical details</summary><p class="permission">Action: <code>coordinate_lookup</code>. Parsing, hierarchy validation, discovery filtering, ownership classification, and navigation identifiers are server-authoritative.</p>'+['universe_galaxies','universe_sectors','universe_solar_systems','universe_planets','universe_discoveries','player_colonies'].map(t=>'<span class="badge">'+t+'</span> ').join('')+'</details></div></div>';document.querySelectorAll('.coordinate-intent').forEach(b=>b.onclick=()=>{selected=b.dataset.route;render()})}
'''
path.write_text(text[:insert_at] + new + text[insert_at:])
print('coordinate renderer inserted')
