<?php
declare(strict_types=1);
$root=dirname(__DIR__);$registry=require $root.'/config/page_registry.php';
$templates=[
'command-center'=>['formula'=>'state summary = authenticated commander telemetry + queued operations + unread events','functions'=>['open state summary','inspect server-calculated values','review queues and dependencies','surface alerts'],'features'=>['live status strip','priority alerts','objective progress','operation timeline'],'tables'=>['players','player_resources','game_events']],
'overview'=>['formula'=>'overview state = subsystem telemetry + pending operations + permission scope','functions'=>['open overview','filter operational state','review alerts','navigate to subsystem'],'features'=>['summary metrics','status badges','related-page navigation','empty-state guidance'],'tables'=>['players','player_resources','game_events']],
'empire'=>['formula'=>'empire output = colony production × biome × race × government × morale','functions'=>['inspect colonies','compare output','manage specialization','review population capacity'],'features'=>['colony telemetry','production forecast','capacity warnings','ownership scope'],'tables'=>['player_colonies','universe_planets','player_resources']],
'resources'=>['formula'=>'resource balance = production + income − upkeep − queue costs','functions'=>['inspect balances','review income','forecast storage','identify deficits'],'features'=>['resource counters','income breakdown','storage limits','deficit warnings'],'tables'=>['player_resources','resource_production','game_events']],
'construction'=>['formula'=>'construction state = validated design + prerequisites + resources + queue capacity','functions'=>['inspect catalogue','queue construction','review prerequisites','process due work'],'features'=>['design catalogue','queue timeline','power draw','field placement'],'tables'=>['construction_queue','settlement_construction_queues','player_resources']],
'research'=>['formula'=>'research effect = technology level × tier coefficient × branch modifier','functions'=>['inspect technology tree','validate prerequisites','queue research','track branch effects'],'features'=>['branch navigation','prerequisite graph','queue slots','effect telemetry'],'tables'=>['technologies','technology_prerequisites','research_queues','player_resources']],
'fleet'=>['formula'=>'fleet readiness = hull integrity × shield condition × armor condition × propulsion modifier','functions'=>['manage fleet','fit ships','form formations','launch and review missions'],'features'=>['loadout readiness','fleet movement','fuel forecast','arrival processing'],'tables'=>['fleets','fleet_ships','fleet_missions','player_resources']],
'military'=>['formula'=>'combat power = units × equipment × technology × formation × condition','functions'=>['inspect forces','train units','simulate combat','review war operations'],'features'=>['force summary','damage profile','defense coverage','combat reports'],'tables'=>['player_unit_stats','unit_types','battles','battle_reports']],
'galaxy'=>['formula'=>'visibility = discovered coordinates + scan permission + sensor range','functions'=>['select coordinate scope','scan sectors','open systems','review anomalies'],'features'=>['coordinate map','owner signals','travel lanes','anomaly telemetry'],'tables'=>['universe_galaxies','universe_sectors','universe_solar_systems','universe_planets']],
'economy'=>['formula'=>'trade settlement = validated order × market price − transaction fee','functions'=>['inspect market','create order','review trade history','manage risk'],'features'=>['order book','price limits','fee preview','escrow state'],'tables'=>['market_orders','market_transactions','player_resources']],
'crafting'=>['formula'=>'crafted effect = blueprint base × material quality × skill rank × augmentation','functions'=>['inspect blueprints','validate materials','craft item','dismantle and augment'],'features'=>['recipe catalogue','material inventory','quality tiers','crafting queue'],'tables'=>['blueprints','crafting_recipes','crafting_queue','player_resources']],
'alliance'=>['formula'=>'alliance capacity = command level × alliance technology × government modifier','functions'=>['manage membership','propose diplomacy','coordinate warfare','share logistics'],'features'=>['roster controls','role permissions','shared projects','diplomatic map'],'tables'=>['alliances','alliance_members','alliance_projects','game_events']],
'lifeforms'=>['formula'=>'lifeform output = population × trait modifier × building level × morale','functions'=>['inspect lifeform state','assign traits','upgrade buildings','research civilization tiers'],'features'=>['trait matrix','civilization tier','lifeform bonuses','population telemetry'],'tables'=>['lifeforms','lifeform_traits','lifeform_buildings','player_resources']],
'activities'=>['formula'=>'activity reward = validated objective progress × difficulty × season modifier','functions'=>['start activity','resolve expedition','claim reward','review achievements'],'features'=>['objective tracker','reward preview','cooldown state','event history'],'tables'=>['quests','quest_progress','achievements','game_events']],
'prestige'=>['formula'=>'prestige total = glory + reputation + ascension effects − penalties','functions'=>['inspect glory','manage reputation','advance ascension','activate permanent bonus'],'features'=>['progression ladder','title unlocks','race effects','permanent modifiers'],'tables'=>['glory_reputation','ascension','player_progression','game_events']],
'rankings'=>['formula'=>'ranking score = economy + military + technology + glory − penalties','functions'=>['view ladder','filter ranking','inspect public profile','refresh snapshot'],'features'=>['rank movement','category scores','season snapshot','public visibility'],'tables'=>['rankings','rank_snapshots','players','glory_reputation']],
'premium'=>['formula'=>'premium state = wallet balance + entitlement state + bounded service effects','functions'=>['inspect wallet','claim eligible reward','activate entitlement','review audit history'],'features'=>['wallet telemetry','season pass','officer effects','service credits'],'tables'=>['premium_catalog','player_premium','premium_transactions','game_events']],
];
$groupAliases=['military'=>'military','galaxy'=>'galaxy','economy'=>'economy','alliance'=>'alliance','lifeforms'=>'lifeforms','activities'=>'activities','prestige'=>'prestige','rankings'=>'rankings','premium'=>'premium'];
$routes=[];foreach($registry as $group=>$block){foreach(($block['pages']??[]) as $route=>$page){$key=$groupAliases[$group]??($group==='command-center'?'command-center':($route==='dashboard'?'overview':$group));$t=$templates[$key]??$templates['overview'];$title=(string)($page['title']??ucwords(str_replace('-',' ',$route)));$buttons=[];foreach(array_slice($t['functions'],0,4) as $i=>$fn){$label=ucwords($fn);$buttons[$label]=['action'=>'inspect_page','logic'=>$fn.'; server validates authentication, CSRF, RBAC, ownership, cooldown, and transaction context.','permission'=>'authenticated commander','reads'=>$t['tables'],'writes'=>[],'states'=>['ready','empty','error']];}$routes[]=['route'=>$route,'group'=>$group,'group_label'=>$block['label']??ucwords(str_replace('-',' ',$group)),'title'=>$title,'purpose'=>$title.' subsystem console with server-authoritative state, controls, dependencies, and feedback.','mechanic'=>$t['formula'],'functions'=>$t['functions'],'features'=>$t['features'],'sub_features'=>['loading and refresh state','permission-aware controls','related-page navigation','filter and sort state','empty-state explanation','audit and feedback detail'],'information_sections'=>['commander context','current state','available controls','dependencies and prerequisites','server contract','database scope','feedback states','related pages'],'controls'=>array_keys($buttons),'buttons'=>$buttons,'server_actions'=>['inspect_page','refresh_page'],'database_tables'=>$t['tables'],'tables'=>$t['tables'],'permissions'=>['authenticated commander','CSRF token','RBAC policy','ownership scope','cooldown validation','transaction boundary'],'permission'=>'authenticated commander · CSRF · RBAC · ownership scope','feedback_states'=>['ready','empty','protected','cooldown','insufficient-resource','success','error'],'states'=>['ready','empty','protected','cooldown','insufficient-resource','success','error'],'layout'=>$page['layout']??'dashboard'];}
}
$byKey=[];foreach($routes as $spec){$byKey[$spec['route']]=$spec;}$out="<?php\nreturn ".var_export(['generated_at'=>gmdate('c'),'page_count'=>count($routes),'routes'=>$routes,'by_key'=>$byKey],true).";\n";file_put_contents($root.'/config/detailed_page_specs.php',$out);echo 'Generated '.count($routes).' detailed submenu specs'.PHP_EOL;
