<?php
declare(strict_types=1);
$root = dirname(__DIR__);
$registry = require $root . '/config/page_registry.php';
$families = [
    'overview' => ['purpose' => 'Command overview, alerts, objectives, and active operations.', 'mechanic' => 'state summary = authenticated colony telemetry + queued operations + unread events', 'functions' => ['summarize commander state','surface alerts','track objectives','open operational detail'], 'features' => ['live status strip','priority alerts','objective progress','operation timeline'], 'subfeatures' => ['filter by severity','sort by completion','acknowledge read-only alerts']],
    'empire' => ['purpose' => 'Manage owned planets, colonies, moons, facilities, storage, and population.', 'mechanic' => 'empire output = colony production × biome × race × government × morale', 'functions' => ['inspect owned worlds','compare colonies','open settlement control','review population capacity'], 'features' => ['colony roster','life-support summary','specialization profile','capacity warnings'], 'subfeatures' => ['world filters','morale indicators','ownership scope','queue visibility']],
    'resources' => ['purpose' => 'Inspect balances, production, consumption, and energy distribution.', 'mechanic' => 'net resource change = production + income − upkeep − queue costs', 'functions' => ['read balances','compare income','inspect resource history','review energy grid'], 'features' => ['resource tiles','income breakdown','production forecast','deficit warnings'], 'subfeatures' => ['per-turn view','per-colony view','resource filters','shortfall states']],
    'construction' => ['purpose' => 'Plan and queue buildings, facilities, shipyards, defenses, and infrastructure.', 'mechanic' => 'queue eligibility = ownership + prerequisite + resource balance + queue capacity + cooldown', 'functions' => ['inspect catalogue','calculate cost','queue construction','review completion'], 'features' => ['building catalogue','queue timeline','prerequisite matrix','power impact'], 'subfeatures' => ['level preview','cancel policy','field placement','capacity validation']],
    'research' => ['purpose' => 'Advance technology branches and queue research with prerequisite validation.', 'mechanic' => 'research cost = base cost × growth ^ current level; completion applies effect', 'functions' => ['inspect technology tree','check prerequisites','queue research','review applied effects'], 'features' => ['branch tree','research queue','effect preview','locked-state explanation'], 'subfeatures' => ['offense','defense','covert','anti-covert','propulsion','astrophysics']],
    'fleet' => ['purpose' => 'Manage ships, motherships, formations, missions, expeditions, saves, and ACS.', 'mechanic' => 'mission readiness = ownership + fleet availability + fuel + route validation + cooldown', 'functions' => ['inspect fleet','compose formation','launch mission','review movement and return'], 'features' => ['fleet roster','loadout view','mission planner','fuel estimate'], 'subfeatures' => ['speed calculation','risk preview','arrival timing','formation modifiers']],
    'military' => ['purpose' => 'Train units, manage officers, defenses, campaigns, and combat readiness.', 'mechanic' => 'combat power = units × equipment × technology × morale − penalties', 'functions' => ['inspect forces','train units','assign officers','simulate combat','review campaigns'], 'features' => ['force roster','training queue','defense grid','combat simulator'], 'subfeatures' => ['shield','armor','penetration','casualty preview','readiness state']],
    'intelligence' => ['purpose' => 'Run reconnaissance, espionage, counter-espionage, sabotage, and sensor operations.', 'mechanic' => 'detection = defender counter-intelligence − attacker agents − covert technology', 'functions' => ['scan target','estimate detection','run covert mission','read classified report'], 'features' => ['covert pool','target profile','detection forecast','report classification'], 'subfeatures' => ['low-risk scan','spy mission','sabotage','sensor phalanx','fleet activity']],
    'galaxy' => ['purpose' => 'Navigate galaxies, sectors, systems, stargates, anomalies, factions, and calendar events.', 'mechanic' => 'visibility = discovered scope + scan permission + coordinate hierarchy + sensor power', 'functions' => ['select coordinate','open map','scan sector','inspect route','review discovery'], 'features' => ['coordinate navigator','map layers','sensor scope','travel lanes'], 'subfeatures' => ['galaxy filter','sector filter','system orbit','anomaly status','NPC signal']],
    'economy' => ['purpose' => 'Trade resources, manage markets, routes, auctions, insurance, and black-market risk.', 'mechanic' => 'settlement = validated order × market price − fee − risk adjustment', 'functions' => ['inspect market','create order','review trade route','settle transaction'], 'features' => ['order book','price limits','trade history','insurance status'], 'subfeatures' => ['buy','sell','route capacity','expiry','fee preview']],
    'crafting' => ['purpose' => 'Craft equipment, process materials, dismantle items, apply augmentations, and manage blueprints.', 'mechanic' => 'craft output = blueprint tier × material quality × skill modifier × station efficiency', 'functions' => ['inspect blueprint','calculate materials','start craft','review durability','dismantle item'], 'features' => ['blueprint library','materials inventory','craft queue','augmentation panel'], 'subfeatures' => ['quality tier','success chance','durability','salvage yield','artifact effects']],
    'alliance' => ['purpose' => 'Manage alliance identity, members, diplomacy, wars, ACS, logistics, stargates, and intelligence.', 'mechanic' => 'alliance capacity = command level × alliance technology × government modifier', 'functions' => ['inspect roster','invite member','propose diplomacy','coordinate defense','review projects'], 'features' => ['member roster','role permissions','diplomacy map','shared projects'], 'subfeatures' => ['officer roles','war state','ACS readiness','logistics capacity','alliance reports']],
    'lifeforms' => ['purpose' => 'Develop population, food, lifeform buildings, research, traits, tiers, and bonuses.', 'mechanic' => 'lifeform output = population × role efficiency × morale × tier modifier', 'functions' => ['inspect population','assign roles','research lifeform','review traits','apply bonus'], 'features' => ['population profile','food balance','lifeform tree','trait matrix'], 'subfeatures' => ['tier progress','civilization level','bonus stacking','workforce allocation']],
    'activities' => ['purpose' => 'Run quests, expeditions, pirate hunts, bounties, bosses, campaigns, achievements, and seasons.', 'mechanic' => 'activity reward = validated objective completion × difficulty × season modifier', 'functions' => ['browse activities','start activity','resolve outcome','claim reward','track achievement'], 'features' => ['activity board','progress tracker','reward preview','season timeline'], 'subfeatures' => ['eligibility','cooldown','risk','reward state','completion audit']],
    'prestige' => ['purpose' => 'Track glory, reputation, ascension, titles, races, and permanent bonuses.', 'mechanic' => 'prestige score = glory + reputation + ascension milestones − penalties', 'functions' => ['inspect prestige','review reputation','preview ascension','select title','review bonuses'], 'features' => ['prestige summary','milestone ladder','title library','permanent modifiers'], 'subfeatures' => ['thresholds','locked states','season movement','bonus application']],
    'rankings' => ['purpose' => 'Compare empire, economy, fleet, research, defense, covert, alliance, lifeform, and galactic control scores.', 'mechanic' => 'ranking score = economy + military + technology + glory − penalties', 'functions' => ['read rankings','filter ladder','open public profile','refresh snapshot'], 'features' => ['leaderboard','movement indicators','score breakdown','season snapshot'], 'subfeatures' => ['universe filter','category filter','rank movement','public visibility']],
    'premium' => ['purpose' => 'Manage store items, officers, commander services, and premium account features.', 'mechanic' => 'purchase eligibility = authenticated account + catalogue availability + balance + entitlement rules', 'functions' => ['browse store','inspect entitlement','purchase item','review duration','manage service'], 'features' => ['catalogue','entitlement panel','expiry state','purchase confirmation'], 'subfeatures' => ['price display','inventory grant','renewal','service limits']],
    'account' => ['purpose' => 'Manage commander profile, settings, support, security, and logout.', 'mechanic' => 'account mutation = authenticated session + CSRF + policy permission + audit event', 'functions' => ['read profile','update preferences','review security','open support','sign out'], 'features' => ['profile card','theme selector','security controls','support channels'], 'subfeatures' => ['density','theme','reduced motion','session review','logout']],
];
$default = ['purpose' => 'Authenticated game operations and server-verified state.', 'mechanic' => 'state = authenticated read scope + validated intent + transaction result', 'functions' => ['inspect state','review controls','open related system'], 'features' => ['page overview','control panel','server contract'], 'subfeatures' => ['loading','ready','empty','error']];
$specs = [];
foreach ($registry as $groupKey => $group) {
    $family = $families[$groupKey] ?? $default;
    foreach (($group['pages'] ?? []) as $route => $page) {
        $title = (string)($page['title'] ?? ucwords(str_replace('-', ' ', $route)));
        $actions = array_values(array_unique(array_filter((array)($page['actions'] ?? []))));
        $tables = array_values(array_unique(array_filter((array)($page['tables'] ?? []))));
        $specs[$route] = [
            'route' => $route,
            'group' => $groupKey,
            'title' => $title,
            'purpose' => $family['purpose'],
            'mechanic' => $family['mechanic'],
            'functions' => $family['functions'],
            'features' => $family['features'],
            'sub_features' => $family['subfeatures'],
            'controls' => $page['controls'] ?? ['Open overview', 'Review status'],
            'buttons' => $actions ? array_map(fn($a) => ['label' => ucwords(str_replace('_', ' ', $a)), 'action' => $a, 'behavior' => 'Submit commander intent; server validates before mutation.'], $actions) : [['label' => 'Inspect page', 'action' => 'inspect_page', 'behavior' => 'Read authenticated page contract.'], ['label' => 'Refresh state', 'action' => 'refresh_page', 'behavior' => 'Refresh authenticated page metadata.']],
            'server_actions' => $actions ?: ['read-only'],
            'database_tables' => $tables ?: ['game_events'],
            'permissions' => ['authenticated commander', 'CSRF protection', 'RBAC policy', 'ownership scope', 'transaction validation'],
            'feedback_states' => ['loading', 'ready', 'empty', 'locked', 'protected', 'cooldown', 'insufficient-resource', 'success', 'error'],
            'information_sections' => ['Page overview', 'Current state', 'Controls and sub-controls', 'Server contract', 'Database scope', 'Feedback states', 'Related pages'],
            'layout' => $page['layout'] ?? 'generic',
        ];
    }
}
$out = $root . '/config/detailed_page_specs.php';
file_put_contents($out, "<?php\ndeclare(strict_types=1);\nreturn " . var_export($specs, true) . ";\n");
echo 'Generated detailed specifications for ' . count($specs) . " routes.\n";
