<?php
declare(strict_types=1);
$root=dirname(__DIR__);$registry=require $root.'/config/page_registry.php';$contracts=require $root.'/config/page_contracts.php';$details=require $root.'/config/dashboard_page_details.php';$interactions=require $root.'/config/player_interaction_contracts.php';
$out="# Universe Civilization: Empire at Wars API and Dashboard Endpoint Reference\n\nGenerated from the authoritative route registry and server-side contracts. The browser submits intent only; mutations are validated by authentication, CSRF, RBAC, ownership, cooldown, resource, and transaction rules before commit.\n\n## Base endpoints\n\n| Method | Endpoint | Purpose |\n|---|---|---|\n| GET | `/game.php?page=<route>` | Render an authenticated dashboard panel without a full navigation reload. |\n| POST | `/actions/game.php` | Submit a server-side mutation or read intent using the session CSRF token. |\n| GET | `/pages/<group>/subpages/<route>.php` | Standalone authenticated entrypoint that redirects to the route-aware dashboard panel. |\n| GET | `/actions/login.php` | Compatibility login endpoint delegating to `login.php`. |\n| GET/POST | `/actions/register.php` | Compatibility registration endpoint delegating to `register.php`. |\n| GET | `/actions/logout.php` | Secure session teardown and redirect to login. |\n\n## Request and response conventions\n\nMutating requests use `POST /actions/game.php` with `action`, the required route-specific fields, and the session CSRF token. Successful actions set a flash result and redirect to the requested dashboard route. Read intents are authenticated and scoped to the commander. Errors are normalized into feedback states such as `ready`, `empty`, `protected`, `insufficient-resource`, `cooldown`, `success`, `invalid-input`, and `error`.\n\n## Route reference\n\n";
$scalar=function($v):string{if(is_bool($v))return $v?'true':'false';if($v===null)return 'null';if(is_scalar($v))return (string)$v;return '';};$list=function($v)use($scalar):string{if(!is_array($v)||!$v)return '—';$out=[];foreach($v as $k=>$x){if(is_scalar($x))$out[]='`'.($scalar($x)===''?(string)$k:$scalar($x)).'`';elseif(is_array($x)&&isset($x['action']))$out[]='`'.(string)$x['action'].'`';}return $out?implode(', ',$out):'—';};$routeCount=0;
foreach($registry as $groupKey=>$group){foreach(($group['pages']??[]) as $route=>$page){$routeCount++;$title=(string)($page['title']??ucwords(str_replace('-',' ',$route)));$contract=$contracts[$route]??[];$detail=$details[$route]??[];$actions=$page['actions']??($contract['actions']??[]);$tables=$page['tables']??($contract['tables']??[]);$states=$contract['states']??($detail['states']??[]);$formula=$contract['formula']??($detail['formula']??'');$permission=$contract['permission']??($detail['permission']??'Authenticated commander.');$out.="### ".$routeCount.". ".$title." (`".$route."`)\n\n"; $out.="**Group:** ".($group['label']??$groupKey)."  \n**Dashboard endpoint:** `GET /game.php?page=".$route."`  \n**Standalone entrypoint:** `GET /pages/".$groupKey."/subpages/".$route.".php`  \n**Mutation endpoint:** `POST /actions/game.php`  \n**Access:** ".$permission."\n\n";if($formula)$out.="**Server formula:** `".str_replace('`','\\`',(string)$formula)."`\n\n";$out.="| Contract item | Value |\n|---|---|\n| Actions / intents | ".$list($actions)." |\n| Tables / data sources | ".$list($tables)." |\n| Feedback states | ".$list($states)." |\n\n";if($actions){$out.="**Action request notes.** Each listed action is submitted as `action=<name>` with route-specific validated fields. No client-provided resource balance, ownership, combat outcome, cooldown, or permission value is trusted.\n\n";} }
}
$out.="## Security and operational rules\n\nEvery mutation must pass session authentication, CSRF verification, RBAC and ownership checks, input bounds, cooldown checks, resource validation, and a database transaction. Server-side services are authoritative for resource balances, population, queue state, combat resolution, report visibility, and turn settlement. Failed transactions must roll back all related writes and return a normalized feedback state.\n\n## Coverage\n\nThis reference contains **".$routeCount." active dashboard routes** from `config/page_registry.php`. Regenerate it with `php tools/generate_api_reference.php` whenever the route registry or contracts change.\n";
file_put_contents($root.'/docs/API_ENDPOINT_REFERENCE.md',$out);echo "Generated $routeCount route entries.\n";
