from pathlib import Path
path = Path('/home/ubuntu/stargatewars/game.php')
s = path.read_text()
s = s.replace("$interactionContracts = require __DIR__ . '/config/player_interaction_contracts.php';\n", "$interactionContracts = require __DIR__ . '/config/player_interaction_contracts.php';\n$pageContractManifest = require __DIR__ . '/config/page_contracts.php';\n")
s = s.replace("$interactionJson = json_encode($interactionContracts, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP);\n", "$interactionJson = json_encode($interactionContracts, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP);\n$pageContractJson = json_encode($pageContractManifest, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP);\n")
s = s.replace("const registry=<?=$registryJson?>,details=<?=$pageDetailsJson?>,interactions=<?=$interactionJson?>,state=", "const registry=<?=$registryJson?>,details=<?=$pageDetailsJson?>,interactions=<?=$interactionJson?>,pageContracts=<?=$pageContractJson?>,state=")
start = s.index('function genericPage(){')
end = s.index('\nfunction render(){', start)
new_function = r'''function contractPanel(c){const logic=c.logic||{},design=c.design||{},systems=c.systems||{},features=c.features||[];const list=(items)=>((items||[]).map(x=>'<span class="badge">'+esc(x)+'</span> ').join('')||'<span class="permission">None declared</span>');return '<div class="card wide"><div class="eyebrow">GAME LOGIC / FEATURES</div><h2>'+esc(logic.purpose||c.title||'Page system')+'</h2><div class="row"><div><strong>Workflow</strong><small>'+esc((logic.workflow||[]).join(' → '))+'</small></div><span class="badge">SERVER</span></div><div class="row"><div><strong>Validation</strong><small>'+esc((logic.validation||[]).join(' · '))+'</small></div><span class="badge good">GUARDED</span></div><div class="row"><div><strong>Calculations</strong><small>'+esc((logic.calculations||[]).join(' · ')||'Read-only state')</small></div><span class="badge">RULES</span></div><div class="row"><div><strong>Features</strong><small>'+list(features)+'</small></div><span class="badge">ENABLED</span></div></div><div class="card side-card"><div class="eyebrow">DESIGN SYSTEM</div><h2>'+esc(design.template||'generic-page')+'</h2><div class="row"><div><strong>Sections</strong><small>'+esc((design.sections||[]).join(' · '))+'</small></div></div><div class="row"><div><strong>Components</strong><small>'+list(design.components)+'</small></div></div><p class="permission">'+esc(design.responsive||'Responsive layout enabled')+'</p></div><div class="card wide"><div class="eyebrow">SYSTEMS / SERVICES</div><h2>Page-specific backend mapping</h2><div class="row"><div><strong>Services</strong><small>'+list(systems.services)+'</small></div></div><div class="row"><div><strong>Reads</strong><small>'+list(systems.reads)+'</small></div></div><div class="row"><div><strong>Writes</strong><small>'+list(systems.writes)+'</small></div></div><div class="row"><div><strong>Actions</strong><small>'+list(systems.actions)+'</small></div></div></div>'}
function genericPage(){const p=all.find(x=>x.key===selected)||all[0],d=details[p.layout]||{hero:p.title,panels:['Overview','Controls','Activity'],formula:'Validated server-side state transition',controls:p.controls||[],action:(p.actions||[])[0]||null,tables:p.tables||[],permission:'authenticated commander',states:['ready','empty','error']},ic=interactions[p.layout]||{page:p.title,purpose:d.hero,buttons:{}},c=(pageContracts.routes||{})[p.key]||{};document.getElementById('section').textContent=(p.group||'SYSTEM').toUpperCase();document.getElementById('title').textContent=p.title;document.getElementById('description').textContent=d.hero+' — '+d.formula;const panels=(d.panels||[]).map((x,i)=>'<div class="row"><div><strong>'+esc(x)+'</strong><small>'+esc(d.formula)+'</small></div><span class="badge">STATE '+(i+1)+'</span></div>').join('');const controlHtml=Object.entries(ic.buttons||{}).map(([label,b])=>'<div class="action"><div><strong>'+esc(label)+'</strong><small>'+esc(b.logic)+'</small></div><span class="badge">'+esc(b.action)+'</span></div>').join('')||'<div class="empty">Read-only information view</div>';document.getElementById('content').innerHTML='<div class="cc-grid"><div class="card wide"><div class="eyebrow">PAGE DETAILS</div><h2>'+esc(d.hero)+'</h2>'+panels+'</div><div class="card side-card"><div class="eyebrow">PAGE CONTROLS</div><h2>Buttons and forms</h2>'+controlHtml+'<p class="permission">'+esc(d.permission)+'</p></div><div class="card wide"><div class="eyebrow">SERVER ACTIONS / DATABASE</div><h2>Backend contract</h2><p class="permission">Action: <b>'+esc(d.action||((p.actions||[]).join(', ')||'read-only'))+'</b></p>'+((d.tables||p.tables||[]).map(x=>'<span class="badge">'+esc(x)+'</span> ').join(''))+'<p class="permission">Writes are transactional and guarded by authentication, CSRF, RBAC, ownership, cooldown, and resource validation.</p></div><div class="card side-card"><div class="eyebrow">FEEDBACK STATES</div><h2>Result handling</h2>'+((d.states||[]).map(x=>'<div class="row"><span>'+esc(x)+'</span><span class="badge">HANDLED</span></div>').join(''))+'</div>'+contractPanel(c)+'</div>'}
'''
s = s[:start] + new_function + s[end:]
path.write_text(s)
print('patched game.php with global page contract rendering')
