from pathlib import Path

path = Path('/home/ubuntu/stargatewars/game.php')
text = path.read_text()
start = text.index('function genericPage(){')
end = text.index('function submitIntent(', start)
new = r'''function genericPage(){
const s=detailedSpecs[selected]||{};const p=all.find(x=>x.key===selected)||all[0]||{};const d=routeDetails[selected]||details[p.layout]||{};
const title=s.title||p.title||selected;const hero=s.purpose||d.hero||'Server-authoritative subsystem console';
const mechanic=s.mechanic||d.formula||'Validated server-side state transition';
const arr=v=>Array.isArray(v)?v:[];const controls=arr(s.controls||d.controls||p.controls);const features=arr(s.features||d.features);const subs=arr(s.sub_features||d.sub_features);const info=arr(s.information_sections||d.information_sections);const actions=arr(s.server_actions||p.actions);const tables=arr(s.database_tables||s.tables||p.tables);const states=arr(s.feedback_states||s.states||['ready','empty','protected','cooldown','success','error']);
const btns=s.buttons||{};const controlMarkup=controls.length?controls.map(label=>{const b=btns[label]||{};const action=b.action||actions[0]||'inspect_page';return '<button class="button dark generated-intent" data-action="'+esc(action)+'" data-redirect="'+esc(selected)+'" data-feedback="generic-feedback">'+esc(label)+'</button>'}).join(' '):'<span class="badge">READ ONLY</span>';
const list=items=>items.length?'<ul class="spec-list">'+items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="permission">No additional entries are configured.</p>';
const stateRows=states.map(x=>'<div class="row"><span>'+esc(x)+'</span><span class="badge">HANDLED</span></div>').join('');
document.getElementById('section').textContent=String(p.group_label||s.group_label||'SYSTEM').toUpperCase();document.getElementById('title').textContent=title;document.getElementById('description').textContent=hero;document.getElementById('content').innerHTML='<div class="cc-grid generated-page"><div class="card wide"><div class="eyebrow">SYSTEM CONSOLE</div><h2>'+esc(title)+'</h2><p class="permission">'+esc(hero)+'</p><div class="metric-grid"><div class="metric"><span>Mechanic</span><strong>SERVER VERIFIED</strong><small>'+esc(mechanic)+'</small></div><div class="metric"><span>Controls</span><strong>'+fmt(controls.length)+'</strong><small>Validated page operations</small></div><div class="metric"><span>Actions</span><strong>'+fmt(actions.length)+'</strong><small>Authenticated contracts</small></div><div class="metric"><span>Data scope</span><strong>'+fmt(tables.length)+'</strong><small>Scoped database tables</small></div></div></div><div class="card side-card"><div class="eyebrow">PAGE CONTROLS</div><h2>Available operations</h2><div class="button-stack">'+controlMarkup+'</div><div id="generic-feedback" class="feedback" style="display:none"></div></div><div class="card wide"><div class="eyebrow">FEATURES</div><h2>Subsystem capabilities</h2>'+list(features)+'</div><div class="card wide"><div class="eyebrow">SUB-FEATURES</div><h2>Operational detail</h2>'+list(subs)+'</div><div class="card side-card"><div class="eyebrow">SYSTEM DESIGN</div><h2>Server contract</h2><p class="permission">'+esc(mechanic)+'</p><div class="row"><span>Permission</span><strong>'+esc(s.permission||d.permission||'authenticated commander')+'</strong></div><div class="row"><span>Actions</span><strong>'+esc(actions.join(' · ')||'read-only')+'</strong></div><div class="row"><span>Tables</span><strong>'+esc(tables.join(' · ')||'none')+'</strong></div></div><div class="card wide"><div class="eyebrow">INFORMATION</div><h2>Commander reference</h2>'+list(info)+'</div><div class="card wide"><div class="eyebrow">FEEDBACK STATES</div><h2>Result handling</h2>'+stateRows+'</div></div>';bindIntentButtons('.generated-intent',selected)}
'''
path.write_text(text[:start] + new + text[end:])
print('generic renderer upgraded')
