<?php
/** Seed a complete disposable beta profile. Local/development only. */
$env=strtolower((string)(getenv('APP_ENV')?:'local'));if(!in_array($env,['local','development'],true)&&getenv('ALLOW_BETA_SEED')!=='1'){fwrite(STDERR,"Refusing beta seed outside local/development. Set APP_ENV=local or ALLOW_BETA_SEED=1.\n");exit(1);}
require_once __DIR__.'/../../config.php';
$g=new Game();$db=$g->db_link;if(!$db||$db->connect_errno){fwrite(STDERR,"Database connection failed.\n");exit(1);}
foreach(['player_resource_wallet','player_fleet_inventory','player_equipment','shipyard_queue','fleet_deployments'] as $requiredTable){$check=$db->query("SHOW TABLES LIKE '".$db->real_escape_string($requiredTable)."'");if(!$check||$check->num_rows===0){fwrite(STDERR,"Missing required table {$requiredTable}; apply migrations 28-30 first.\n");exit(1);}}
$username=(string)(getenv('SGW_BETA_USERNAME')?:'beta_tester');$st=$db->prepare('SELECT uid FROM users WHERE uname=? LIMIT 1');$st->bind_param('s',$username);$st->execute();$row=$st->get_result()->fetch_assoc();if(!$row){fwrite(STDERR,"Beta user not found: {$username}\n");exit(1);}$uid=(int)$row['uid'];$pq=$db->query("SELECT uid FROM planets WHERE uid={$uid} LIMIT 1");if(!$pq||!($planet=$pq->fetch_assoc())){fwrite(STDERR,"Beta home planet not found.\n");exit(1);}$planetId=$uid;
$db->query("INSERT INTO player_resource_wallet(uid,metal,crystal,energy) VALUES({$uid},5000000,3000000,1500000) ON DUPLICATE KEY UPDATE metal=GREATEST(metal,5000000),crystal=GREATEST(crystal,3000000),energy=GREATEST(energy,1500000)");
$inventory=['scout'=>40,'frigate'=>12,'destroyer'=>4,'carrier'=>1];foreach($inventory as $type=>$qty){$safe=$db->real_escape_string($type);$db->query("INSERT INTO player_fleet_inventory(uid,planet_id,ship_type,quantity) VALUES({$uid},{$planetId},'{$safe}',{$qty}) ON DUPLICATE KEY UPDATE quantity=GREATEST(quantity,{$qty})");}
$equipment=['reinforced_hull'=>3,'targeting_array'=>3,'shield_matrix'=>2,'cargo_frame'=>2];foreach($equipment as $key=>$level){$safe=$db->real_escape_string($key);$db->query("INSERT INTO player_equipment(uid,equipment_key,level,quantity) VALUES({$uid},'{$safe}',{$level},1) ON DUPLICATE KEY UPDATE level=GREATEST(level,{$level}),quantity=GREATEST(quantity,1)");}
$jobs=[['scout',10,12000,6000,1000,5],['frigate',2,10000,5000,1600,15]];foreach($jobs as $job){[$type,$qty,$metal,$crystal,$energy,$minutes]=$job;$safe=$db->real_escape_string($type);$exists=$db->query("SELECT queue_id FROM shipyard_queue WHERE uid={$uid} AND planet_id={$planetId} AND ship_type='{$safe}' AND status='building' LIMIT 1");if(!$exists||!$exists->num_rows){$db->query("INSERT INTO shipyard_queue(uid,planet_id,ship_type,quantity,metal_cost,crystal_cost,energy_cost,completes_at,status) VALUES({$uid},{$planetId},'{$safe}',{$qty},{$metal},{$crystal},{$energy},DATE_ADD(NOW(),INTERVAL {$minutes} MINUTE),'building')");}}
$remoteId=$planetId+1;$fleetJson=$db->real_escape_string(json_encode($inventory,JSON_UNESCAPED_SLASHES));$exists=$db->query("SELECT deployment_id FROM fleet_deployments WHERE uid={$uid} AND status='enroute' LIMIT 1");if(!$exists||!$exists->num_rows){$db->query("INSERT INTO fleet_deployments(uid,origin_planet_id,destination_planet_id,fleet_json,attack_power,defense_power,status,arrive_at) VALUES({$uid},{$planetId},{$remoteId},'{$fleetJson}',10200,7660,'enroute',DATE_ADD(NOW(),INTERVAL 30 MINUTE))");}
echo "Beta data seeded for {$username} (uid {$uid}).\nResources: 5000000 metal / 3000000 crystal / 1500000 energy\nFleet: 40 scouts / 12 frigates / 4 destroyers / 1 carrier\nEquipment: reinforced hull 3 / targeting array 3 / shield matrix 2 / cargo frame 2\nShipyard: scout and frigate jobs queued\nDeployment: sample fleet enroute\n";
