<?php
if (PHP_SAPI !== 'cli') { fwrite(STDERR, "CLI only\n"); exit(1); }
if (!in_array(strtolower((string)(getenv('APP_ENV') ?: 'local')), ['local','development'], true) && getenv('ALLOW_EMAIL_TEST') !== '1') { fwrite(STDERR, "Set APP_ENV=local/development or ALLOW_EMAIL_TEST=1.\n"); exit(1); }
require_once __DIR__ . '/../../config.php';
$db=new mysqli($conf['db_server'],$conf['db_username'],$conf['db_password'],$conf['db_name']);if($db->connect_error){fwrite(STDERR,"Database connection failed.\n");exit(1);}
$from=(int)(getenv('SGW_EMAIL_FROM_UID')?:0);$to=(int)(getenv('SGW_EMAIL_TO_UID')?:0);if($from<=0||$to<=0){$q=$db->query('SELECT uid FROM users ORDER BY uid ASC LIMIT 2');$ids=[];while($q&&($r=$q->fetch_assoc()))$ids[]=(int)$r['uid'];$from=$from?:($ids[0]??0);$to=$to?:($ids[1]??0);}if($from<=0||$to<=0||$from===$to){fwrite(STDERR,"Two distinct player UIDs are required. Set SGW_EMAIL_FROM_UID and SGW_EMAIL_TO_UID.\n");exit(1);}
$db->query("CREATE TABLE IF NOT EXISTS game_email_messages (email_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,from_uid INT NULL,from_address VARCHAR(190) NOT NULL,to_uid INT NULL,to_address VARCHAR(190) NOT NULL,subject VARCHAR(190) NOT NULL,body TEXT NOT NULL,email_type VARCHAR(16) NOT NULL DEFAULT 'player',is_read TINYINT(1) NOT NULL DEFAULT 0,is_deleted TINYINT(1) NOT NULL DEFAULT 0,delivery_status VARCHAR(16) NOT NULL DEFAULT 'inbox',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,sent_at DATETIME NULL,KEY idx_game_email_recipient(to_uid,is_deleted,created_at),KEY idx_game_email_sender(from_uid,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$fq=$db->query("SELECT uname,email FROM users WHERE uid=$from LIMIT 1");$tq=$db->query("SELECT uname,email FROM users WHERE uid=$to LIMIT 1");$f=$fq?$fq->fetch_assoc():null;$t=$tq?$tq->fetch_assoc():null;if(!$f||!$t){fwrite(STDERR,"Selected player UID does not exist.\n");exit(1);}$fromAddress=filter_var((string)$f['email'],FILTER_VALIDATE_EMAIL)?$f['email']:'player'.$from.'@universecivilization.game';$toAddress=filter_var((string)$t['email'],FILTER_VALIDATE_EMAIL)?$t['email']:'player'.$to.'@universecivilization.game';$subject='Player Direct Message Integration Test';$body='Direct player-to-player inbox delivery test.';$stmt=$db->prepare("INSERT INTO game_email_messages(from_uid,from_address,to_uid,to_address,subject,body,email_type,delivery_status,sent_at) VALUES(?,?,?,?,?,?, 'player','inbox',NOW())");$stmt->bind_param('isisss',$from,$fromAddress,$to,$toAddress,$subject,$body);if(!$stmt->execute()){fwrite(STDERR,"Direct message insert failed.\n");exit(1);}$id=(int)$db->insert_id;$verify=$db->query("SELECT email_id,from_uid,to_uid,subject,is_read FROM game_email_messages WHERE email_id=$id AND from_uid=$from AND to_uid=$to LIMIT 1");if(!$verify||!$verify->fetch_assoc()){fwrite(STDERR,"Direct message inbox verification failed.\n");exit(1);}echo "Player email test passed: email_id=$id from UID $from ({$f['uname']}) to UID $to ({$t['uname']}).\n";
?>
