<?php
declare(strict_types=1);

final class AllianceService
{
    public function __construct(private PDO $pdo) {}

    private function setting(string $key,int $default=0): int
    {
        $s=$this->pdo->prepare('SELECT setting_value FROM game_settings WHERE setting_key=?');$s->execute([$key]);$v=$s->fetchColumn();return $v===false?$default:max(0,(int)$v);
    }

    private function event(int $playerId,string $type,?int $entityId,array $payload): void
    {
        $s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)');$s->execute([$playerId,$type,'alliance',$entityId,json_encode($payload,JSON_THROW_ON_ERROR)]);
    }

    private function capacityFor(int $playerId,array $player): array
    {
        $s=$this->pdo->prepare("SELECT COALESCE(level,0) FROM player_technologies WHERE player_id=? AND technology_key IN ('alliance','diplomacy','mercenary') ORDER BY level DESC LIMIT 1");$s->execute([$playerId]);$technologyLevel=(int)($s->fetchColumn()?:0);$g=$this->pdo->prepare('SELECT COALESCE(diplomacy_modifier,1.000) FROM government_types WHERE id=?');$g->execute([(int)($player['government_id']??0)]);$government=(float)($g->fetchColumn()?:1.0);$commandLevel=max(1,(int)($player['rank_level']??1));$technology=max(1,$technologyLevel+1);$capacity=max(10,(int)floor($commandLevel*$technology*$government));return ['command_level'=>$commandLevel,'technology_level'=>$technologyLevel,'technology_multiplier'=>$technology,'government_modifier'=>$government,'capacity'=>$capacity];
    }

    public function snapshot(int $playerId): array
    {
        if($playerId<1)throw new InvalidArgumentException('Invalid alliance request.');$s=$this->pdo->prepare('SELECT id,display_name,username,rank_level,government_id,alliance_id FROM players WHERE id=?');$s->execute([$playerId]);$viewer=$s->fetch(PDO::FETCH_ASSOC);if(!$viewer)throw new RuntimeException('Commander not found.');$rows=$this->pdo->query('SELECT a.id,a.name,a.tag,a.founder_id,a.description,a.created_at,COUNT(am.player_id) member_count FROM alliances a LEFT JOIN alliance_members am ON am.alliance_id=a.id GROUP BY a.id ORDER BY member_count DESC,a.name')->fetchAll(PDO::FETCH_ASSOC);$roster=[];$current=null;if($viewer['alliance_id']){$q=$this->pdo->prepare('SELECT a.id,a.name,a.tag,a.description,am.role,am.joined_at FROM alliances a JOIN alliance_members am ON am.alliance_id=a.id WHERE a.id=? ORDER BY am.role,am.joined_at');$q->execute([(int)$viewer['alliance_id']]);$current=$q->fetch(PDO::FETCH_ASSOC);if($current){$m=$this->pdo->prepare('SELECT p.id,p.display_name,p.title,am.role,am.joined_at FROM alliance_members am JOIN players p ON p.id=am.player_id WHERE am.alliance_id=? ORDER BY FIELD(am.role,\'leader\',\'officer\',\'member\'),am.joined_at');$m->execute([(int)$viewer['alliance_id']]);$roster=$m->fetchAll(PDO::FETCH_ASSOC);}}$cap=$this->capacityFor($playerId,$viewer);return ['state'=>$rows?'ready':'empty','alliances'=>$rows,'current'=>$current,'roster'=>$roster,'capacity'=>$cap,'formula'=>'alliance capacity = command level × alliance technology × government modifier','states'=>['ready','empty','protected','success','error']];
    }

    public function create(int $playerId,string $name,string $tag,string $description=''): int
    {
        if($playerId<1)throw new InvalidArgumentException('Invalid alliance creator.');$name=trim($name);$tag=strtoupper(trim($tag));$description=trim($description);if(!preg_match('/^[A-Za-z0-9][A-Za-z0-9 ._-]{2,79}$/',$name))throw new InvalidArgumentException('Alliance name must be 3–80 safe characters.');if(!preg_match('/^[A-Z0-9]{2,12}$/',$tag))throw new InvalidArgumentException('Alliance tag must be 2–12 letters or numbers.');if(strlen($description)>4000)throw new InvalidArgumentException('Alliance description is too long.');$this->pdo->beginTransaction();try{$c=$this->setting('alliance_create_cooldown_seconds');$cool=$this->pdo->prepare("SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key='alliance_create' FOR UPDATE");$cool->execute([$playerId]);$available=$cool->fetchColumn();if($available!==false&&new DateTimeImmutable((string)$available)>new DateTimeImmutable('now'))throw new RuntimeException('Alliance creation is on cooldown.');$p=$this->pdo->prepare('SELECT id,rank_level,government_id,alliance_id FROM players WHERE id=? FOR UPDATE');$p->execute([$playerId]);$player=$p->fetch(PDO::FETCH_ASSOC);if(!$player)throw new RuntimeException('Commander not found.');if($player['alliance_id']!==null)throw new RuntimeException('Commander is already in an alliance.');$this->pdo->prepare('INSERT INTO alliances(name,tag,founder_id,description) VALUES(?,?,?,?)')->execute([$name,$tag,$playerId,$description]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare("INSERT INTO alliance_members(alliance_id,player_id,role) VALUES(?,?, 'leader')")->execute([$id,$playerId]);$this->pdo->prepare('UPDATE players SET alliance_id=? WHERE id=?')->execute([$id,$playerId]);if($c>0){$next=(new DateTimeImmutable('now'))->modify('+'.$c.' seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,'alliance_create',$next]);}$cap=$this->capacityFor($playerId,$player);$this->event($playerId,'alliance_created',$id,['name'=>$name,'tag'=>$tag,'capacity'=>$cap['capacity'],'cooldown_seconds'=>$c]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }

    public function join(int $playerId,int $allianceId): array
    {
        if($playerId<1||$allianceId<1)throw new InvalidArgumentException('Invalid alliance membership request.');$this->pdo->beginTransaction();try{$c=$this->setting('alliance_join_cooldown_seconds');$cool=$this->pdo->prepare("SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key='alliance_join' FOR UPDATE");$cool->execute([$playerId]);$available=$cool->fetchColumn();if($available!==false&&new DateTimeImmutable((string)$available)>new DateTimeImmutable('now'))throw new RuntimeException('Alliance joining is on cooldown.');$a=$this->pdo->prepare('SELECT id,name,tag,founder_id FROM alliances WHERE id=? FOR UPDATE');$a->execute([$allianceId]);$alliance=$a->fetch(PDO::FETCH_ASSOC);if(!$alliance)throw new RuntimeException('Alliance not found.');$p=$this->pdo->prepare('SELECT id,rank_level,government_id,alliance_id FROM players WHERE id=? FOR UPDATE');$p->execute([$playerId]);$player=$p->fetch(PDO::FETCH_ASSOC);if(!$player)throw new RuntimeException('Commander not found.');if($player['alliance_id']!==null)throw new RuntimeException('Commander is already in an alliance.');$s=$this->pdo->prepare('SELECT COUNT(*) FROM alliance_members WHERE alliance_id=?');$s->execute([$allianceId]);$members=(int)$s->fetchColumn();$cap=$this->capacityFor($playerId,$player);if($members>=$cap['capacity'])throw new RuntimeException('Alliance capacity is full.');$this->pdo->prepare("INSERT INTO alliance_members(alliance_id,player_id,role) VALUES(?,?, 'member')")->execute([$allianceId,$playerId]);$this->pdo->prepare('UPDATE players SET alliance_id=? WHERE id=?')->execute([$allianceId,$playerId]);if($c>0){$next=(new DateTimeImmutable('now'))->modify('+'.$c.' seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,'alliance_join',$next]);}$this->event($playerId,'alliance_joined',$allianceId,['name'=>$alliance['name'],'tag'=>$alliance['tag'],'member_count'=>$members+1,'capacity'=>$cap['capacity'],'cooldown_seconds'=>$c]);$this->pdo->commit();return ['state'=>'success','alliance_id'=>$allianceId,'name'=>$alliance['name'],'member_count'=>$members+1,'capacity'=>$cap['capacity'],'cooldown_seconds'=>$c];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }
}
