<?php
declare(strict_types=1);

final class FactionService
{
    public function __construct(private PDO $pdo) {}
    private function setting(string $key,int $default):int{$s=$this->pdo->prepare('SELECT setting_value FROM game_settings WHERE setting_key=?');$s->execute([$key]);$v=$s->fetchColumn();return $v===false?$default:max(0,(int)$v);}
    private function cooldown(int $playerId,string $key,int $defaultSeconds):array{$s=$this->pdo->prepare('SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key=? FOR UPDATE');$s->execute([$playerId,$key]);$v=$s->fetchColumn();if($v===false||$v===null)return ['state'=>'ready','available_at'=>null,'remaining_seconds'=>0];$remaining=max(0,(new DateTimeImmutable((string)$v))->getTimestamp()-(new DateTimeImmutable('now'))->getTimestamp());return $remaining>0?['state'=>'cooldown','available_at'=>(string)$v,'remaining_seconds'=>$remaining]:['state'=>'ready','available_at'=>null,'remaining_seconds'=>0];}
    private function setCooldown(int $playerId,string $key,int $seconds):?string{if($seconds<1)return null;$until=(new DateTimeImmutable('now'))->modify('+'.$seconds.' seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,$key,$until]);return $until;}
    private function event(int $playerId,string $type,array $payload):void{$s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)');$s->execute([$playerId,$type,'player',$playerId,json_encode($payload,JSON_THROW_ON_ERROR)]);}
    public function options():array{$races=$this->pdo->query('SELECT id,name,bonus_label,bonus_percent,bank_name,attack_modifier,defense_modifier,income_modifier,covert_modifier FROM races ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)?:[];$governments=$this->pdo->query('SELECT id,government_key,name,description,economy_modifier,research_modifier,military_modifier,defense_modifier,covert_modifier,diplomacy_modifier,colony_modifier,fleet_modifier,population_modifier,dark_matter_modifier FROM government_types WHERE is_active=1 ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)?:[];return ['races'=>$races,'governments'=>$governments];}
    public function snapshot(int $playerId):array{if($playerId<1)throw new InvalidArgumentException('Invalid faction request.');$s=$this->pdo->prepare("SELECT p.id,p.race_id,p.government_id,p.registration_completed_at,p.vacation_until,r.name race_name,r.bonus_label,r.bonus_percent,r.bank_name,r.attack_modifier AS race_attack_modifier,r.defense_modifier AS race_defense_modifier,r.income_modifier AS race_income_modifier,r.covert_modifier AS race_covert_modifier,g.name government_name,g.description government_description,g.economy_modifier AS government_economy_modifier,g.research_modifier AS government_research_modifier,g.military_modifier AS government_military_modifier,g.defense_modifier AS government_defense_modifier,g.covert_modifier AS government_covert_modifier,g.diplomacy_modifier AS government_diplomacy_modifier,g.colony_modifier AS government_colony_modifier,g.fleet_modifier AS government_fleet_modifier,g.population_modifier AS government_population_modifier,g.dark_matter_modifier AS government_dark_matter_modifier FROM players p LEFT JOIN races r ON r.id=p.race_id LEFT JOIN government_types g ON g.id=p.government_id WHERE p.id=?");$s->execute([$playerId]);$p=$s->fetch(PDO::FETCH_ASSOC);if(!$p)throw new RuntimeException('Player not found.');$race=(float)($p['race_income_modifier']??1);$gov=(float)($p['government_economy_modifier']??1);$states=['ready','protected','cooldown','success','error'];return ['state'=>'ready','player'=>['id'=>$playerId,'race_id'=>(int)($p['race_id']??0),'government_id'=>(int)($p['government_id']??0),'registration_complete'=>$p['registration_completed_at']!==null,'vacation_until'=>$p['vacation_until']], 'current'=>['race_name'=>$p['race_name']??'Unassigned','government_name'=>$p['government_name']??'Unassigned','bonus_label'=>$p['bonus_label']??'No race selected','bonus_percent'=>(float)($p['bonus_percent']??0),'bank_name'=>$p['bank_name']??'Unassigned','attack_modifier'=>(float)($p['race_attack_modifier']??1)*(float)($p['government_military_modifier']??1),'defense_modifier'=>(float)($p['race_defense_modifier']??1)*(float)($p['government_defense_modifier']??1),'income_modifier'=>$race*$gov,'covert_modifier'=>(float)($p['race_covert_modifier']??1)*(float)($p['government_covert_modifier']??1),'research_modifier'=>(float)($p['government_research_modifier']??1),'population_modifier'=>(float)($p['government_population_modifier']??1)],'options'=>$this->options(),'cooldowns'=>['race_change'=>$this->readCooldown($playerId,'race_change'),'government_reform'=>$this->readCooldown($playerId,'government_reform')],'formula'=>'race modifier = selected race profile applied to production, combat, and growth','states'=>$states];}
    private function readCooldown(int $playerId,string $key):array{$s=$this->pdo->prepare('SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key=?');$s->execute([$playerId,$key]);$v=$s->fetchColumn();if($v===false||$v===null)return ['state'=>'ready','available_at'=>null,'remaining_seconds'=>0];$remaining=max(0,(new DateTimeImmutable((string)$v))->getTimestamp()-(new DateTimeImmutable('now'))->getTimestamp());return $remaining>0?['state'=>'cooldown','available_at'=>(string)$v,'remaining_seconds'=>$remaining]:['state'=>'ready','available_at'=>null,'remaining_seconds'=>0];}
    public function selectRegistration(int $playerId, int $raceId, int $governmentId): array
    {
        if ($playerId < 1 || $raceId < 1 || $governmentId < 1) {
            throw new InvalidArgumentException('Invalid faction selection.');
        }
        $ownsTransaction = !$this->pdo->inTransaction();
        if ($ownsTransaction) {
            $this->pdo->beginTransaction();
        }
        try {
            $r = $this->pdo->prepare('SELECT id,name FROM races WHERE id=?');
            $r->execute([$raceId]);
            $race = $r->fetch(PDO::FETCH_ASSOC);
            if (!$race) {
                throw new RuntimeException('Race unavailable.');
            }
            $g = $this->pdo->prepare('SELECT id,name FROM government_types WHERE id=? AND is_active=1');
            $g->execute([$governmentId]);
            $gov = $g->fetch(PDO::FETCH_ASSOC);
            if (!$gov) {
                throw new RuntimeException('Government unavailable.');
            }
            $p = $this->pdo->prepare('SELECT race_id,government_id,registration_completed_at FROM players WHERE id=? FOR UPDATE');
            $p->execute([$playerId]);
            $player = $p->fetch(PDO::FETCH_ASSOC);
            if (!$player) {
                throw new RuntimeException('Player not found.');
            }
            if ($player['registration_completed_at'] !== null && ((int)$player['race_id'] !== $raceId || (int)$player['government_id'] !== $governmentId)) {
                throw new RuntimeException('Registration is complete; use race change or government reform.');
            }
            $this->pdo->prepare('UPDATE players SET race_id=?,government_id=?,registration_completed_at=COALESCE(registration_completed_at,NOW()) WHERE id=?')->execute([$raceId,$governmentId,$playerId]);
            $this->pdo->prepare("INSERT INTO player_government_history(player_id,government_id,reason) VALUES(?,?, 'registration')")->execute([$playerId,$governmentId]);
            $this->event($playerId, 'faction_selected', ['race_id'=>$raceId, 'government_id'=>$governmentId]);
            if ($ownsTransaction) {
                $this->pdo->commit();
            }
            return ['state'=>'success','race_id'=>$raceId,'government_id'=>$governmentId,'race'=>$race['name'],'government'=>$gov['name']];
        } catch (Throwable $e) {
            if ($ownsTransaction && $this->pdo->inTransaction()) {
                $this->pdo->rollBack();
            }
            throw $e;
        }
    }
    public function changeRace(int $playerId,int $raceId):array{if($playerId<1||$raceId<1)throw new InvalidArgumentException('Invalid race selection.');$this->pdo->beginTransaction();try{$r=$this->pdo->prepare('SELECT id,name FROM races WHERE id=?');$r->execute([$raceId]);$race=$r->fetch(PDO::FETCH_ASSOC);if(!$race)throw new RuntimeException('Race unavailable.');$p=$this->pdo->prepare('SELECT race_id,registration_completed_at FROM players WHERE id=? FOR UPDATE');$p->execute([$playerId]);$player=$p->fetch(PDO::FETCH_ASSOC);if(!$player)throw new RuntimeException('Player not found.');if($player['registration_completed_at']===null)throw new RuntimeException('Complete initial faction registration first.');if((int)$player['race_id']===$raceId)throw new RuntimeException('Race is already selected.');$cd=$this->cooldown($playerId,'race_change',3600);if($cd['state']==='cooldown')throw new RuntimeException('Race selection is on cooldown for '.$cd['remaining_seconds'].' seconds.');$seconds=$this->setting('race_change_cooldown_seconds',3600);$this->pdo->prepare('UPDATE players SET race_id=? WHERE id=?')->execute([$raceId,$playerId]);$until=$this->setCooldown($playerId,'race_change',$seconds);$this->event($playerId,'race_changed',['race_id'=>$raceId,'cooldown_until'=>$until]);$this->pdo->commit();return ['state'=>'success','race_id'=>$raceId,'race'=>$race['name'],'cooldown_until'=>$until,'cooldown_seconds'=>$seconds];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function reformGovernment(int $playerId,int $governmentId):array{if($playerId<1||$governmentId<1)throw new InvalidArgumentException('Invalid government.');$this->pdo->beginTransaction();try{$g=$this->pdo->prepare('SELECT id,name FROM government_types WHERE id=? AND is_active=1');$g->execute([$governmentId]);$gov=$g->fetch(PDO::FETCH_ASSOC);if(!$gov)throw new RuntimeException('Government unavailable.');$p=$this->pdo->prepare('SELECT government_id,registration_completed_at FROM players WHERE id=? FOR UPDATE');$p->execute([$playerId]);$player=$p->fetch(PDO::FETCH_ASSOC);if(!$player)throw new RuntimeException('Player not found.');if($player['registration_completed_at']===null)throw new RuntimeException('Complete initial faction registration first.');if((int)$player['government_id']===$governmentId)throw new RuntimeException('Government is already active.');$cd=$this->cooldown($playerId,'government_reform',3600);if($cd['state']==='cooldown')throw new RuntimeException('Government reform is on cooldown for '.$cd['remaining_seconds'].' seconds.');$seconds=$this->setting('government_reform_cooldown_seconds',3600);$this->pdo->prepare('UPDATE players SET government_id=? WHERE id=?')->execute([$governmentId,$playerId]);$this->pdo->prepare("INSERT INTO player_government_history(player_id,government_id,reason) VALUES(?,?, 'reform')")->execute([$playerId,$governmentId]);$until=$this->setCooldown($playerId,'government_reform',$seconds);$this->event($playerId,'government_reformed',['government_id'=>$governmentId,'cooldown_until'=>$until]);$this->pdo->commit();return ['state'=>'success','government_id'=>$governmentId,'government'=>$gov['name'],'cooldown_until'=>$until,'cooldown_seconds'=>$seconds];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function bonuses(int $playerId):array{$s=$this->pdo->prepare('SELECT r.name race_name,r.attack_modifier race_attack,r.defense_modifier race_defense,r.income_modifier race_income,r.covert_modifier race_covert,g.name government_name,g.* FROM players p JOIN races r ON r.id=p.race_id LEFT JOIN government_types g ON g.id=p.government_id WHERE p.id=?');$s->execute([$playerId]);$row=$s->fetch(PDO::FETCH_ASSOC)?:[];if(!$row)throw new RuntimeException('Player faction state not found.');return ['race'=>$row['race_name']??null,'government'=>$row['government_name']??null,'attack'=>(float)($row['race_attack']??1)*(float)($row['military_modifier']??1),'defense'=>(float)($row['race_defense']??1)*(float)($row['defense_modifier']??1),'income'=>(float)($row['race_income']??1)*(float)($row['economy_modifier']??1),'research'=>(float)($row['research_modifier']??1),'covert'=>(float)($row['race_covert']??1)*(float)($row['covert_modifier']??1),'diplomacy'=>(float)($row['diplomacy_modifier']??1),'colony'=>(float)($row['colony_modifier']??1),'fleet'=>(float)($row['fleet_modifier']??1),'population'=>(float)($row['population_modifier']??1),'dark_matter'=>(float)($row['dark_matter_modifier']??1)];}
}
