<?php
declare(strict_types=1);
final class MMORPGService {
    public function __construct(private PDO $pdo) {}
    private function event(int $playerId,string $type,?int $entityId,array $payload):void{$s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)');$s->execute([$playerId,$type,'mmorpg',$entityId,json_encode($payload,JSON_THROW_ON_ERROR)]);}
    public function addExperience(int $playerId,int $amount):array{if($amount<1)throw new InvalidArgumentException('Experience must be positive');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM player_progression WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);$p=$s->fetch();if(!$p){$this->pdo->prepare('INSERT INTO player_progression(player_id) VALUES(?)')->execute([$playerId]);$p=['experience'=>0,'level'=>1];}$xp=(int)$p['experience']+$amount;$level=(int)$p['level'];while($xp>=$level*1000){$xp-=$level*1000;$level++;}$this->pdo->prepare('UPDATE player_progression SET experience=?,level=? WHERE player_id=?')->execute([$xp,$level,$playerId]);$this->event($playerId,'progression_updated',$playerId,['experience'=>$xp,'level'=>$level]);$this->pdo->commit();return ['experience'=>$xp,'level'=>$level];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function setCooldown(int $playerId,string $key,int $seconds):void{if($seconds<1)throw new InvalidArgumentException('Cooldown must be positive');$this->pdo->prepare('INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL ? SECOND)) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)')->execute([$playerId,$key,$seconds]);}
    public function assertAvailable(int $playerId,string $key):void{$s=$this->pdo->prepare('SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key=?');$s->execute([$playerId,$key]);$at=$s->fetchColumn();if($at!==false&&strtotime((string)$at)>time())throw new RuntimeException('Action is on cooldown');}
    public function proposeDiplomacy(int $worldId,int $proposer,int $target,string $type):int{if($proposer===$target||!in_array($type,['nap','trade','alliance','war','ceasefire'],true))throw new InvalidArgumentException('Invalid diplomatic proposal');$this->pdo->prepare('INSERT INTO diplomacy_relations(world_id,proposer_player_id,target_player_id,relation_type) VALUES(?,?,?,?)')->execute([$worldId,$proposer,$target,$type]);$id=(int)$this->pdo->lastInsertId();$this->event($proposer,'diplomacy_proposed',$id,['target'=>$target,'relation_type'=>$type]);return $id;}
    public function createTrade(int $worldId,int $seller,int $buyer,string $resource,int $quantity,int $unitPrice):int{if($quantity<1||$unitPrice<1)throw new InvalidArgumentException('Invalid trade values');$this->pdo->beginTransaction();try{$this->pdo->prepare('INSERT INTO trade_contracts(world_id,seller_player_id,buyer_player_id,resource_key,quantity,unit_price) VALUES(?,?,?,?,?,?)')->execute([$worldId,$seller,$buyer,$resource,$quantity,$unitPrice]);$id=(int)$this->pdo->lastInsertId();$this->event($seller,'trade_contract_created',$id,['buyer'=>$buyer,'resource'=>$resource,'quantity'=>$quantity,'unit_price'=>$unitPrice]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function notify(int $playerId,string $type,string $title,string $body):int{$this->pdo->prepare('INSERT INTO player_notifications(player_id,notification_type,title,body) VALUES(?,?,?,?)')->execute([$playerId,$type,$title,$body]);return (int)$this->pdo->lastInsertId();}
    public function beginTurnBatch(int $worldId):int{$this->pdo->prepare('INSERT INTO turn_batches(world_id,started_at) VALUES(?,NOW())')->execute([$worldId]);return (int)$this->pdo->lastInsertId();}
    public function finishTurnBatch(int $batchId,int $players,int $colonies,int $missions):void{$this->pdo->prepare("UPDATE turn_batches SET completed_at=NOW(),players_processed=?,colonies_processed=?,missions_processed=?,status='completed' WHERE id=?")->execute([$players,$colonies,$missions,$batchId]);}
}
