<?php
declare(strict_types=1);
require_once __DIR__ . '/../auth.php';
require_once __DIR__ . '/Rules.php';

final class OGameService {
    public function __construct(private PDO $pdo) {}
    private function colony(int $playerId,int $colonyId,bool $lock=false):array{$sql='SELECT * FROM colonies WHERE id=? AND player_id=?'.($lock?' FOR UPDATE':'');$s=$this->pdo->prepare($sql);$s->execute([$colonyId,$playerId]);$r=$s->fetch();if(!$r)throw new RuntimeException('Colony not found');return $r;}
    private function event(int $playerId,string $type,?int $entityId,array $payload):void{$s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)');$s->execute([$playerId,$type,'ogame_system',$entityId,json_encode($payload,JSON_THROW_ON_ERROR)]);}
    public function processColonyTurn(int $playerId,int $colonyId,int $elapsedSeconds):array{
        if($elapsedSeconds<0||$elapsedSeconds>86400)throw new InvalidArgumentException('Invalid elapsed time');
        $this->pdo->beginTransaction();try{$c=$this->colony($playerId,$colonyId,true);$hours=$elapsedSeconds/3600;
            $s=$this->pdo->prepare("SELECT resource_key,production_per_hour,consumption_per_hour,amount,capacity FROM player_resource_balances WHERE player_id=?");$s->execute([$playerId]);$balances=$s->fetchAll();$delta=[];
            foreach($balances as $r){$change=(float)$r['production_per_hour']*$hours-(float)$r['consumption_per_hour']*$hours;$next=min((float)$r['capacity'],max(0,(float)$r['amount']+$change));$delta[$r['resource_key']]=['before'=>(float)$r['amount'],'after'=>$next];$this->pdo->prepare('UPDATE player_resource_balances SET amount=? WHERE player_id=? AND resource_key=?')->execute([$next,$playerId,$r['resource_key']]);}
            $population=(int)$c['population'];$foodCost=(int)ceil($population*.25*$hours);$waterCost=(int)ceil($population*.20*$hours);$foodAfter=max(0,(int)$c['food_stock']-$foodCost);$waterAfter=max(0,(int)$c['water_stock']-$waterCost);$shortage=($foodAfter===0||$waterAfter===0);$growth=$shortage?0:(int)floor(max(0,$population*(.01*$hours)*((float)$c['morale'])));$populationAfter=min((int)$c['population_capacity'],$population+$growth);$this->pdo->prepare('UPDATE colonies SET food_stock=?,water_stock=?,population=? WHERE id=? AND player_id=?')->execute([$foodAfter,$waterAfter,$populationAfter,$colonyId,$playerId]);$payload=['hours'=>$hours,'food_cost'=>$foodCost,'water_cost'=>$waterCost,'shortage'=>$shortage,'resource_delta'=>$delta];$this->pdo->prepare('INSERT INTO colony_turn_snapshots(colony_id,processed_at,elapsed_seconds,food_before,food_after,water_before,water_after,population_before,population_after,payload) VALUES(?,NOW(),?,?,?,?,?,?,?,?)')->execute([$colonyId,$elapsedSeconds,$c['food_stock'],$foodAfter,$c['water_stock'],$waterAfter,$population,$populationAfter,json_encode($payload,JSON_THROW_ON_ERROR)]);$this->event($playerId,'colony_turn_processed',$colonyId,$payload);$this->pdo->commit();return ['colony_id'=>$colonyId,'food_after'=>$foodAfter,'water_after'=>$waterAfter,'population_after'=>$populationAfter,'shortage'=>$shortage];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function queueBuilding(int $playerId,int $colonyId,string $buildingKey,int $level):int{$this->pdo->beginTransaction();try{$c=$this->colony($playerId,$colonyId,true);$s=$this->pdo->prepare('SELECT * FROM building_types WHERE building_key=?');$s->execute([$buildingKey]);$b=$s->fetch();if(!$b||$level<1)throw new RuntimeException('Building not found');$cost=(int)round((float)$b['base_naquadah']*pow((float)$b['growth_factor'],$level-1));$this->pdo->prepare('INSERT INTO construction_queue(player_id,colony_id,queue_type,item_key,quantity,level_before,starts_at,completes_at) VALUES(?,?,?,?,?,?,NOW(),DATE_ADD(NOW(),INTERVAL ? SECOND))')->execute([$playerId,$colonyId,'building',$buildingKey,1,$level-1,(int)$b['build_seconds']]);$id=(int)$this->pdo->lastInsertId();$this->event($playerId,'building_queued',$id,['colony_id'=>$colonyId,'building'=>$buildingKey,'level'=>$level,'cost'=>$cost]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function launchMission(int $playerId,int $sourceColonyId,?int $targetColonyId,string $type,array $payload,int $travelSeconds):int{$allowed=['transport','attack','raid','espionage','colonize','recycle','explore'];if(!in_array($type,$allowed,true)||$travelSeconds<1)throw new InvalidArgumentException('Invalid fleet mission');$this->colony($playerId,$sourceColonyId);if($targetColonyId)$this->colony($playerId,$targetColonyId);$this->pdo->beginTransaction();try{$this->pdo->prepare('INSERT INTO fleet_missions(player_id,source_colony_id,target_colony_id,mission_type,payload,departure_at,arrival_at,status) VALUES(?,?,?,?,?,NOW(),DATE_ADD(NOW(),INTERVAL ? SECOND),\'outbound\')')->execute([$playerId,$sourceColonyId,$targetColonyId,$type,json_encode($payload,JSON_THROW_ON_ERROR),$travelSeconds]);$id=(int)$this->pdo->lastInsertId();$this->event($playerId,'fleet_mission_launched',$id,['type'=>$type,'source'=>$sourceColonyId,'target'=>$targetColonyId]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
}
