<?php
declare(strict_types=1);

final class PlanetService
{
    public function __construct(private PDO $pdo) {}

    private function setting(string $key,int $default=0): int
    {
        $s=$this->pdo->prepare('SELECT setting_value FROM game_settings WHERE setting_key=?');$s->execute([$key]);$v=$s->fetchColumn();return $v===false?$default:max(0,(int)$v);
    }

    private function event(int $playerId,string $type,?int $entityId,array $payload): void
    {
        $s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)');$s->execute([$playerId,$type,'planet',$entityId,json_encode($payload,JSON_THROW_ON_ERROR)]);
    }

    public function list(int $playerId): array
    {
        if($playerId<1)throw new InvalidArgumentException('Invalid planet-list request.');$sql="SELECT c.id,c.player_id,c.planet_id,c.moon_id,c.colony_name,c.is_homeworld,c.population,c.food,c.water,c.morale,c.colony_level,p.name planet_name,p.coordinate_label,p.planet_class,p.planet_type,p.biome,p.size_class,p.habitability,p.slots,p.metal_modifier,p.food_modifier,p.water_modifier,p.energy_modifier,COALESCE(r.income_modifier,1.000) race_modifier,COALESCE(g.economy_modifier,1.000) government_modifier,COALESCE(r.name,'Unassigned') race_name,COALESCE(g.name,'Unassigned') government_name,COALESCE(pr.attack_units,0) fleet_presence FROM player_colonies c JOIN universe_planets p ON p.id=c.planet_id JOIN players pl ON pl.id=c.player_id LEFT JOIN races r ON r.id=pl.race_id LEFT JOIN government_types g ON g.id=pl.government_id LEFT JOIN player_resources pr ON pr.player_id=c.player_id WHERE c.player_id=? ORDER BY c.is_homeworld DESC,c.id";$s=$this->pdo->prepare($sql);$s->execute([$playerId]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row){$base=1000*max(1,(int)$row['colony_level']);$biome=(float)$row['metal_modifier'];$race=(float)$row['race_modifier'];$government=(float)$row['government_modifier'];$morale=(float)$row['morale'];$output=$base*$biome*$race*$government*$morale;$row['base_production']=$base;$row['biome_modifier']=$biome;$row['production_output']=(int)round($output);$row['food_ratio']=min(1.0,(int)$row['food']/max(1,(int)$row['population']));$row['water_ratio']=min(1.0,(int)$row['water']/max(1,(int)$row['population']));$row['life_support_state']=($row['food_ratio']>=1&&$row['water_ratio']>=1)?'stable':'strained';$row['fleet_presence']=(int)$row['fleet_presence'];$row['population']=(int)$row['population'];$row['habitability']=(float)$row['habitability'];}unset($row);return ['state'=>$rows?'ready':'empty','colonies'=>$rows,'formula'=>'colony output = base production × biome × race × government × morale','states'=>['ready','empty','protected','success','error']];
    }

    public function explore(int $playerId,string $name,string $type): array
    {
        if($playerId<1)throw new InvalidArgumentException('Invalid explorer.');$name=trim($name);$type=trim($type);if($name===''||strlen($name)>100||$type===''||strlen($type)>60)throw new InvalidArgumentException('Invalid exploration details.');$this->pdo->beginTransaction();try{$cost=25000;$cooldown=$this->setting('planet_explore_cooldown_seconds');$c=$this->pdo->prepare("SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key='planet_explore' FOR UPDATE");$c->execute([$playerId]);$available=$c->fetchColumn();if($available!==false&&new DateTimeImmutable((string)$available)>new DateTimeImmutable('now'))throw new RuntimeException('Planet exploration is on cooldown.');$r=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$r->execute([$playerId]);if((int)$r->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah.');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$payload=['anomaly_roll'=>0.05,'reward'=>'exploration_intelligence','cost'=>$cost];$this->pdo->prepare("INSERT INTO planet_explorations(player_id,name,discovery_type,status,result_json,completed_at) VALUES(?,?,?,'completed',?,NOW())")->execute([$playerId,$name,$type,json_encode($payload,JSON_THROW_ON_ERROR)]);$id=(int)$this->pdo->lastInsertId();if($cooldown>0){$next=(new DateTimeImmutable('now'))->modify('+'.$cooldown.' seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,'planet_explore',$next]);}$this->event($playerId,'planet_explored',$id,['name'=>$name,'type'=>$type,'cost'=>$cost,'cooldown_seconds'=>$cooldown]);$this->pdo->commit();return ['state'=>'success','exploration_id'=>$id,'cost'=>$cost,'reward'=>$payload['reward'],'cooldown_seconds'=>$cooldown];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }

    public function colonize(int $playerId,int $planetId,string $colonyName): array
    {
        if($playerId<1||$planetId<1)throw new InvalidArgumentException('Invalid colonization request.');$colonyName=trim($colonyName);if($colonyName===''||strlen($colonyName)>120)throw new InvalidArgumentException('Invalid colony name.');$this->pdo->beginTransaction();try{$cost=50000;$cooldown=$this->setting('planet_colonize_cooldown_seconds');$c=$this->pdo->prepare("SELECT available_at FROM player_cooldowns WHERE player_id=? AND cooldown_key='planet_colonize' FOR UPDATE");$c->execute([$playerId]);$available=$c->fetchColumn();if($available!==false&&new DateTimeImmutable((string)$available)>new DateTimeImmutable('now'))throw new RuntimeException('Colonization is on cooldown.');$p=$this->pdo->prepare('SELECT id,name,habitability,is_colonizable,is_occupied FROM universe_planets WHERE id=? FOR UPDATE');$p->execute([$planetId]);$planet=$p->fetch(PDO::FETCH_ASSOC);if(!$planet)throw new RuntimeException('Planet not found.');if(!(int)$planet['is_colonizable'])throw new RuntimeException('Planet is not colonizable.');if((int)$planet['is_occupied'])throw new RuntimeException('Planet is occupied.');if((float)$planet['habitability']<0.25)throw new RuntimeException('Planet is not habitable enough.');$max=$this->setting('max_planets',10);$count=$this->pdo->prepare('SELECT COUNT(*) FROM player_colonies WHERE player_id=?');$count->execute([$playerId]);if((int)$count->fetchColumn()>=$max)throw new RuntimeException('Colony limit reached.');$r=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$r->execute([$playerId]);if((int)$r->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah.');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO player_colonies(player_id,planet_id,colony_name,is_homeworld,population,food,water,morale,colony_level) VALUES(?,?,?,0,0,0,0,1.000,1)')->execute([$playerId,$planetId,$colonyName]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare('UPDATE universe_planets SET is_occupied=1 WHERE id=?')->execute([$planetId]);if($cooldown>0){$next=(new DateTimeImmutable('now'))->modify('+'.$cooldown.' seconds')->format('Y-m-d H:i:s');$this->pdo->prepare("INSERT INTO player_cooldowns(player_id,cooldown_key,available_at) VALUES(?,?,?) ON DUPLICATE KEY UPDATE available_at=VALUES(available_at)")->execute([$playerId,'planet_colonize',$next]);}$this->event($playerId,'planet_colonized',$id,['planet_id'=>$planetId,'cost'=>$cost,'habitability'=>(float)$planet['habitability'],'cooldown_seconds'=>$cooldown]);$this->pdo->commit();return ['state'=>'success','colony_id'=>$id,'planet_id'=>$planetId,'cost'=>$cost,'cooldown_seconds'=>$cooldown];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }

    public function upgradeDefense(int $playerId,int $planetId,string $defenseType): array
    {
        if($playerId<1||$planetId<1||!preg_match('/^[A-Za-z0-9_-]{2,80}$/',$defenseType))throw new InvalidArgumentException('Invalid defense request.');$this->pdo->beginTransaction();try{$cost=10000;$maxLevel=25;$p=$this->pdo->prepare('SELECT id FROM player_planets WHERE id=? AND player_id=? FOR UPDATE');$p->execute([$planetId,$playerId]);if(!$p->fetch())throw new RuntimeException('Planet not owned.');$r=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$r->execute([$playerId]);if((int)$r->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah.');$d=$this->pdo->prepare('SELECT level FROM planet_defenses WHERE planet_id=? AND defense_type=? FOR UPDATE');$d->execute([$planetId,$defenseType]);$level=$d->fetchColumn();$before=$level===false?0:(int)$level;if($before>=$maxLevel)throw new RuntimeException('Defense level cap reached.');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO planet_defenses(planet_id,defense_type,level,strength) VALUES(?,?,1,100) ON DUPLICATE KEY UPDATE level=level+1,strength=strength+100')->execute([$planetId,$defenseType]);$this->event($playerId,'planet_defense_upgraded',$planetId,['defense_type'=>$defenseType,'level_before'=>$before,'level_after'=>$before+1,'cost'=>$cost]);$this->pdo->commit();return ['state'=>'success','planet_id'=>$planetId,'defense_type'=>$defenseType,'level_after'=>$before+1,'cost'=>$cost];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }
}
