<?php
declare(strict_types=1);
final class ProgressionService {
    public function __construct(private PDO $pdo) {}
    public function tiers(): array { return $this->pdo->query('SELECT * FROM progression_tiers ORDER BY tier_number')->fetchAll(PDO::FETCH_ASSOC) ?: []; }
    public function level(int $tier,int $level): array { if($tier<1||$tier>21||$level<1||$level>23)throw new InvalidArgumentException('Tier must be 1-21 and level must be 1-23');$global=(($tier-1)*23)+$level;$s=$this->pdo->prepare('SELECT pl.*,pt.tier_number,pt.tier_name FROM progression_levels pl JOIN progression_tiers pt ON pt.id=pl.tier_id WHERE pt.tier_number=? AND pl.level_number=?');$s->execute([$tier,$level]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('Progression level unavailable');return $row; }
    public function entity(int $playerId,string $category,string $key): array { if($playerId<1||!preg_match('/^[a-z0-9_:-]{1,100}$/',$category.'_'.$key))throw new InvalidArgumentException('Invalid progression entity');$s=$this->pdo->prepare('SELECT * FROM progression_entities WHERE player_id=? AND entity_category=? AND entity_key=?');$s->execute([$playerId,$category,$key]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row){$this->pdo->prepare('INSERT INTO progression_entities(player_id,entity_category,entity_key) VALUES(?,?,?)')->execute([$playerId,$category,$key]);$row=['player_id'=>$playerId,'entity_category'=>$category,'entity_key'=>$key,'tier_number'=>1,'level_number'=>1,'experience'=>0];}return $row; }
    public function cost(int $tier,int $level): array { $row=$this->level($tier,$level);return ['metal'=>(int)$row['metal_cost'],'crystal'=>(int)$row['crystal_cost'],'naquadah'=>(int)$row['naquadah_cost'],'food'=>(int)$row['food_cost'],'water'=>(int)$row['water_cost'],'energy'=>(int)$row['energy_cost'],'dark_matter'=>(int)$row['dark_matter_cost'],'experience'=>(int)$row['xp_cost'],'build_seconds'=>(int)$row['build_seconds'],'effect_percent'=>(float)$row['effect_percent']]; }
    public function advance(int $playerId,string $category,string $key): array { if($playerId<1||$category===''||$key==='')throw new InvalidArgumentException('Invalid progression request');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM progression_entities WHERE player_id=? AND entity_category=? AND entity_key=? FOR UPDATE');$s->execute([$playerId,$category,$key]);$entity=$s->fetch(PDO::FETCH_ASSOC);if(!$entity){$this->pdo->prepare('INSERT INTO progression_entities(player_id,entity_category,entity_key) VALUES(?,?,?)')->execute([$playerId,$category,$key]);$entity=['tier_number'=>1,'level_number'=>1,'experience'=>0];}$tier=(int)$entity['tier_number'];$level=(int)$entity['level_number'];if($tier===21&&$level===23)throw new RuntimeException('Maximum progression reached');$nextTier=$level===23?$tier+1:$tier;$nextLevel=$level===23?1:$level+1;$cost=$this->cost($nextTier,$nextLevel);$r=$this->pdo->prepare('SELECT metal,crystal,naquadah,food,water,energy,dark_matter FROM player_resources WHERE player_id=? FOR UPDATE');$r->execute([$playerId]);$resources=$r->fetch(PDO::FETCH_ASSOC);if(!$resources)throw new RuntimeException('Player resources not found');foreach(['metal','crystal','naquadah','food','water','energy','dark_matter'] as $resource)if((int)$resources[$resource]<$cost[$resource])throw new RuntimeException('Insufficient '.$resource);$set=[];$vals=[];foreach(['metal','crystal','naquadah','food','water','energy','dark_matter'] as $resource){$set[]=$resource.'='.$resource.'-?';$vals[]=$cost[$resource];}$vals[]=$playerId;$this->pdo->prepare('UPDATE player_resources SET '.implode(',',$set).' WHERE player_id=?')->execute($vals);$this->pdo->prepare('UPDATE progression_entities SET tier_number=?,level_number=?,experience=0 WHERE player_id=? AND entity_category=? AND entity_key=?')->execute([$nextTier,$nextLevel,$playerId,$category,$key]);$this->pdo->prepare('INSERT INTO progression_events(player_id,entity_category,entity_key,tier_before,level_before,tier_after,level_after,cost_payload) VALUES(?,?,?,?,?,?,?,?)')->execute([$playerId,$category,$key,$tier,$level,$nextTier,$nextLevel,json_encode($cost,JSON_THROW_ON_ERROR)]);$this->pdo->commit();return ['category'=>$category,'key'=>$key,'tier_before'=>$tier,'level_before'=>$level,'tier_after'=>$nextTier,'level_after'=>$nextLevel,'cost'=>$cost];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
}
