<?php
declare(strict_types=1);

final class TechnologyTreeService
{
    public function __construct(private PDO $pdo) {}

    private function coefficient(string $category): float
    {
        return ['offense'=>1.20,'defense'=>1.10,'covert'=>1.00,'anti_covert'=>1.05,'unique'=>1.30,'mercenary'=>1.15][$category]??1.00;
    }

    public function snapshot(int $playerId): array
    {
        $q=$this->pdo->prepare("SELECT t.*,COALESCE(pt.level,0) level,COALESCE(pt.next_cost,0) stored_next_cost FROM technologies t LEFT JOIN player_technologies pt ON pt.player_id=? AND pt.technology_key=t.technology_key ORDER BY FIELD(t.category,'offense','defense','covert','anti_covert','unique','mercenary'),t.name");$q->execute([$playerId]);$techs=[];$byKey=[];foreach($q->fetchAll() as $t){$byKey[$t['technology_key']=$t['technology_key']]=$t;}$pr=$this->pdo->query('SELECT technology_key,prerequisite_key,minimum_level FROM technology_prerequisites')->fetchAll();$prereqs=[];foreach($pr as $x)$prereqs[$x['technology_key']][]=$x;$rows=[];foreach($byKey as $t){$level=(int)$t['level'];$coef=$this->coefficient((string)$t['category']);$effect=round((float)$t['effect_value']*max(1,$level)*$coef,2);$nextCost=(int)round((float)$t['base_cost']*pow((float)$t['cost_growth'],$level));$checks=[];$ready=true;foreach($prereqs[$t['technology_key']]??[] as $x){$got=(int)($byKey[$x['prerequisite_key']]['level']??0);$ok=$got>=(int)$x['minimum_level'];$checks[]=['key'=>$x['prerequisite_key'],'level'=>$got,'required'=>(int)$x['minimum_level'],'met'=>$ok];if(!$ok)$ready=false;}$rows[]=['id'=>(int)$t['id'],'technology_key'=>$t['technology_key'],'name'=>$t['name'],'category'=>$t['category'],'level'=>$level,'next_level'=>$level+1,'base_effect'=>(float)$t['effect_value'],'tier_coefficient'=>$coef,'current_effect'=>$effect,'next_effect'=>round((float)$t['effect_value']*($level+1)*$coef,2),'base_cost'=>(int)$t['base_cost'],'cost_growth'=>(float)$t['cost_growth'],'next_cost'=>$nextCost,'description'=>$t['description'],'prerequisites'=>$checks,'ready'=>$ready,'lock_reason'=>$ready?'': 'Prerequisite technology required'];}$s=$this->pdo->prepare("SELECT id,technology_key,level_before,level_after,base_effect,tier_coefficient,starts_at,completes_at,status FROM research_queues WHERE player_id=? AND status IN ('queued','researching') ORDER BY completes_at");$s->execute([$playerId]);$queue=$s->fetchAll();$branchSystems=[];foreach($rows as $row){if((int)$row['level']>0){$branchSystems[]=['key'=>$row['technology_key'],'name'=>$row['name'],'category'=>$row['category'],'level'=>(int)$row['level'],'effect'=>(float)$row['current_effect'],'status'=>'APPLIED'];}}return ['technologies'=>$rows,'queue'=>$queue,'queue_used'=>count($queue),'queue_capacity'=>3,'queue_available'=>count($queue)<3,'formula'=>'technology effect = base effect × level × tier coefficient','categories'=>['offense','defense','covert','anti_covert','unique','mercenary'],'branch_systems'=>$branchSystems,'applied_branch_count'=>count($branchSystems),'states'=>['ready','locked','insufficient-resource','success','error']];
    }

    public function upgrade(int $playerId,string $technologyKey): array
    {
        $this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM technologies WHERE technology_key=? FOR UPDATE');$s->execute([$technologyKey]);$t=$s->fetch();if(!$t)throw new RuntimeException('Technology not found.');$s=$this->pdo->prepare('SELECT level FROM player_technologies WHERE player_id=? AND technology_key=? FOR UPDATE');$s->execute([$playerId,$technologyKey]);$level=(int)($s->fetchColumn()?:0);$s=$this->pdo->prepare('SELECT prerequisite_key,minimum_level FROM technology_prerequisites WHERE technology_key=?');$s->execute([$technologyKey]);foreach($s->fetchAll() as $p){$x=$this->pdo->prepare('SELECT level FROM player_technologies WHERE player_id=? AND technology_key=?');$x->execute([$playerId,$p['prerequisite_key']]);if((int)($x->fetchColumn()?:0)<(int)$p['minimum_level'])throw new RuntimeException('Research prerequisite not met.');}$s=$this->pdo->prepare("SELECT COUNT(*) FROM research_queues WHERE player_id=? AND status IN ('queued','researching')");$s->execute([$playerId]);if((int)$s->fetchColumn()>=3)throw new RuntimeException('Research queue capacity reached.');$cost=(int)round((float)$t['base_cost']*pow((float)$t['cost_growth'],$level));$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);if((int)$s->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah for research.');$coef=$this->coefficient((string)$t['category']);$start=new DateTimeImmutable('now');$complete=$start->modify('+'.(($level+1)*120).' seconds');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare("INSERT INTO player_technologies(player_id,technology_id,technology_key,technology_name,category,level,next_cost) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE level=VALUES(level),next_cost=VALUES(next_cost),technology_id=VALUES(technology_id)")->execute([$playerId,$t['id'],$technologyKey,$t['name'],$t['category'],$level+1,$cost]);$this->pdo->prepare('INSERT INTO research_queues(player_id,technology_id,technology_key,level_before,level_after,base_effect,tier_coefficient,starts_at,completes_at,status) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$playerId,$t['id'],$technologyKey,$level,$level+1,$t['effect_value'],$coef,$start->format('Y-m-d H:i:s'),$complete->format('Y-m-d H:i:s'),'researching']);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)')->execute([$playerId,'technology_research_queued','research_queue',$id,json_encode(['technology_key'=>$technologyKey,'level_before'=>$level,'level_after'=>$level+1,'cost'=>$cost],JSON_THROW_ON_ERROR)]);$this->pdo->commit();return ['technology_key'=>$technologyKey,'level_before'=>$level,'level_after'=>$level+1,'cost'=>$cost,'completes_at'=>$complete->format('Y-m-d H:i:s')];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }
}
