<?php
declare(strict_types=1);

final class UnitProductionService
{
    public function __construct(private PDO $pdo) {}

    public function snapshot(int $playerId): array
    {
        $r=$this->pdo->prepare('SELECT unit_production,naquadah,untrained_units FROM player_resources WHERE player_id=?');$r->execute([$playerId]);$resources=$r->fetch()?:[];$t=$this->pdo->prepare('SELECT COALESCE(pt.level,0) level,COALESCE(t.effect_value,0) effect_value FROM technologies t LEFT JOIN player_technologies pt ON pt.player_id=? AND pt.technology_key=t.technology_key WHERE t.technology_key=?');$t->execute([$playerId,'automation']);$tech=$t->fetch()?:['level'=>0,'effect_value'=>8];$techLevel=(int)$tech['level'];$techModifier=1+($techLevel*(float)$tech['effect_value']/100);$q=$this->pdo->prepare("SELECT id,queue_type,level_before,level_after,technology_modifier,starts_at,completes_at,status FROM production_queues WHERE player_id=? AND status IN ('queued','processing') ORDER BY completes_at");$q->execute([$playerId]);$queue=$q->fetchAll();$level=(int)($resources['unit_production']??0);$tracks=[['key'=>'workforce','name'=>'Workforce throughput','coefficient'=>1.000,'effect'=>round($level*1.000*$techModifier,2),'next_effect'=>round(($level+1)*1.000*$techModifier,2),'description'=>'Raises untrained population generation per settlement cycle.'],['key'=>'academy','name'=>'Academy capacity','coefficient'=>1.200,'effect'=>round($level*1.200*$techModifier,2),'next_effect'=>round(($level+1)*1.200*$techModifier,2),'description'=>'Improves recruitment throughput and training readiness.'],['key'=>'elite_capacity','name'=>'Elite deployment capacity','coefficient'=>0.800,'effect'=>round($level*0.800*$techModifier,2),'next_effect'=>round(($level+1)*0.800*$techModifier,2),'description'=>'Improves strategic elite-unit deployment capacity.']];return ['level'=>$level,'next_level'=>$level+1,'next_cost'=>$level*5000+10000,'resources'=>$resources,'automation_level'=>$techLevel,'technology_modifier'=>round($techModifier,3),'technology_requirement'=>'automation level 1','technology_ready'=>$techLevel>=1,'queue'=>$queue,'queue_used'=>count($queue),'queue_capacity'=>3,'queue_available'=>count($queue)<3,'tracks'=>$tracks,'formula'=>'upgrade effect = level × tier coefficient × technology modifier','states'=>['ready','locked','insufficient-resource','success','error']];
    }

    public function upgrade(int $playerId): array
    {
        $this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT COALESCE(pt.level,0) FROM player_technologies pt WHERE pt.player_id=? AND pt.technology_key=? FOR UPDATE');$s->execute([$playerId,'automation']);if((int)$s->fetchColumn()<1)throw new RuntimeException('Automation level 1 is required.');$s=$this->pdo->prepare("SELECT COUNT(*) FROM production_queues WHERE player_id=? AND status IN ('queued','processing')");$s->execute([$playerId]);if((int)$s->fetchColumn()>=3)throw new RuntimeException('Production queue capacity reached.');$s=$this->pdo->prepare('SELECT unit_production,naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);$r=$s->fetch();if(!$r)throw new RuntimeException('Player resources not found.');$before=(int)$r['unit_production'];$cost=$before*5000+10000;if((int)$r['naquadah']<$cost)throw new RuntimeException('Not enough Naquadah for production upgrade.');$s=$this->pdo->prepare('SELECT effect_value FROM technologies WHERE technology_key=?');$s->execute(['automation']);$effect=(float)($s->fetchColumn()?:8);$s=$this->pdo->prepare('SELECT level FROM player_technologies WHERE player_id=? AND technology_key=?');$s->execute([$playerId,'automation']);$techLevel=(int)($s->fetchColumn()?:0);$modifier=1+($techLevel*$effect/100);$start=new DateTimeImmutable('now');$complete=$start->modify('+'.(($before+1)*60).' seconds');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-?,unit_production=unit_production+1 WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare("INSERT INTO production_queues(player_id,queue_type,level_before,level_after,technology_modifier,starts_at,completes_at,status) VALUES(?,?,?,?,?,?,?,'queued')")->execute([$playerId,'unit_production',$before,$before+1,$modifier,$start->format('Y-m-d H:i:s'),$complete->format('Y-m-d H:i:s')]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,entity_type,entity_id,payload) VALUES(?,?,?,?,?)')->execute([$playerId,'unit_production_upgraded','production_queue',$id,json_encode(['level_before'=>$before,'level_after'=>$before+1,'cost'=>$cost,'technology_modifier'=>$modifier],JSON_THROW_ON_ERROR)]);$this->pdo->commit();return ['queue_id'=>$id,'level_before'=>$before,'level_after'=>$before+1,'cost'=>$cost,'completes_at'=>$complete->format('Y-m-d H:i:s')];}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
    }
}
