<?php
declare(strict_types=1);
require_once __DIR__ . '/../auth.php';
final class WorldService {
    public function __construct(?PDO $pdo = null) { $this->pdo = $pdo ?? db() ?? throw new RuntimeException('Database unavailable'); }
    private function event(int $playerId,string $type,array $payload):void{$s=$this->pdo->prepare('INSERT INTO game_events(player_id,event_type,payload) VALUES(?,?,?)');$s->execute([$playerId,$type,json_encode($payload)]);}
    public function explore(int $playerId,string $name,string $type):int{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);$naquadah=(int)$s->fetchColumn();$cost=25000;if($naquadah<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO player_planets(player_id,name,planet_type,size_label,income_bonus) VALUES(?,?,?,?,?)')->execute([$playerId,$name,$type,'Medium',5]);$id=(int)$this->pdo->lastInsertId();$this->event($playerId,'planet_explored',['planet_id'=>$id,'cost'=>$cost]);$this->pdo->commit();return $id;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function upgradePlanetDefense(int $playerId,int $planetId,string $defenseType):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT p.id FROM player_planets p WHERE p.id=? AND p.player_id=? FOR UPDATE');$s->execute([$planetId,$playerId]);if(!$s->fetch())throw new RuntimeException('Planet not owned');$cost=10000;$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);if((int)$s->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO planet_defenses(planet_id,defense_type,level,strength) VALUES(?,?,1,100) ON DUPLICATE KEY UPDATE level=level+1,strength=strength+100')->execute([$planetId,$defenseType]);$this->event($playerId,'planet_defense_upgraded',['planet_id'=>$planetId,'type'=>$defenseType]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function joinAlliance(int $playerId,int $allianceId):void{$s=$this->pdo->prepare('SELECT id FROM alliances WHERE id=?');$s->execute([$allianceId]);if(!$s->fetch())throw new RuntimeException('Alliance not found');$this->pdo->prepare("INSERT INTO alliance_members(alliance_id,player_id,role) VALUES(?,?, 'member') ON DUPLICATE KEY UPDATE role=role")->execute([$allianceId,$playerId]);$this->event($playerId,'alliance_joined',['alliance_id'=>$allianceId]);}
    public function buyMarketOrder(int $buyerId,int $orderId,int $quantity):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare("SELECT * FROM market_orders WHERE id=? AND status='open' FOR UPDATE");$s->execute([$orderId]);$order=$s->fetch();if(!$order||$quantity<1||$quantity>(int)$order['quantity'])throw new RuntimeException('Market order unavailable');if((int)$order['seller_id']===$buyerId)throw new RuntimeException('Cannot buy your own order');$cost=$quantity*(int)$order['unit_price'];$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$buyerId]);if((int)$s->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$buyerId]);$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah+? WHERE player_id=?')->execute([$cost,$order['seller_id']]);$remaining=(int)$order['quantity']-$quantity;$this->pdo->prepare("UPDATE market_orders SET quantity=?,status=IF(?=0,'filled','open') WHERE id=?")->execute([$remaining,$remaining,$orderId]);$this->event($buyerId,'market_order_bought',['order_id'=>$orderId,'quantity'=>$quantity,'cost'=>$cost]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function markMessageRead(int $playerId,int $messageId):void{$this->pdo->prepare('UPDATE messages SET read_at=NOW() WHERE id=? AND recipient_id=?')->execute([$messageId,$playerId]);}
    public function createAlliance(int $playerId,string $name,string $tag,string $description):int{$this->pdo->beginTransaction();try{$this->pdo->prepare('INSERT INTO alliances(name,tag,founder_id,description) VALUES(?,?,?,?)')->execute([$name,$tag,$playerId,$description]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare("INSERT INTO alliance_members(alliance_id,player_id,role) VALUES(?,?, 'leader')")->execute([$id,$playerId]);$this->event($playerId,'alliance_created',['alliance_id'=>$id]);$this->pdo->commit();return $id;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function listMarketOrder(int $sellerId,string $resourceType,int $quantity,int $unitPrice):int{$allowed=['naquadah','mercenary','weapon'];if(!in_array($resourceType,$allowed,true)||$quantity<1||$unitPrice<1)throw new InvalidArgumentException('Invalid market order');$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$sellerId]);$balance=(int)$s->fetchColumn();$escrow=$quantity*$unitPrice;if($resourceType==='naquadah'&&$balance<$quantity)throw new RuntimeException('Not enough Naquadah for escrow');if($resourceType==='naquadah')$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$quantity,$sellerId]);$this->pdo->prepare('INSERT INTO market_orders(seller_id,resource_type,quantity,unit_price) VALUES(?,?,?,?)')->execute([$sellerId,$resourceType,$quantity,$unitPrice]);$id=(int)$this->pdo->lastInsertId();$this->event($sellerId,'market_order_listed',['order_id'=>$id,'resource'=>$resourceType,'quantity'=>$quantity]);$this->pdo->commit();return $id;}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function buyMercenary(int $playerId,int $mercenaryTypeId,int $quantity):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT price FROM mercenary_types WHERE id=?');$s->execute([$mercenaryTypeId]);$price=$s->fetchColumn();if($price===false||$quantity<1)throw new RuntimeException('Mercenary type not found');$cost=(int)$price*$quantity;$s=$this->pdo->prepare('SELECT naquadah FROM player_resources WHERE player_id=? FOR UPDATE');$s->execute([$playerId]);if((int)$s->fetchColumn()<$cost)throw new RuntimeException('Not enough Naquadah');$this->pdo->prepare('UPDATE player_resources SET naquadah=naquadah-? WHERE player_id=?')->execute([$cost,$playerId]);$this->pdo->prepare('INSERT INTO player_mercenaries(player_id,mercenary_type_id,quantity) VALUES(?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity)')->execute([$playerId,$mercenaryTypeId,$quantity]);$this->event($playerId,'mercenary_recruited',['type_id'=>$mercenaryTypeId,'quantity'=>$quantity,'cost'=>$cost]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function sendMessage(int $senderId,int $recipientId,string $subject,string $body):int{$s=$this->pdo->prepare('SELECT id FROM players WHERE id=?');$s->execute([$recipientId]);if(!$s->fetch())throw new RuntimeException('Recipient not found');$s=$this->pdo->prepare('INSERT INTO messages(sender_id,recipient_id,subject,body) VALUES(?,?,?,?)');$s->execute([$senderId,$recipientId,$subject,$body]);$id=(int)$this->pdo->lastInsertId();$this->event($senderId,'message_sent',['message_id'=>$id]);return $id;}
    public function activateVacation(int $playerId,int $days):void{$days=max(1,min(30,$days));$until=(new DateTimeImmutable('now'))->modify('+'.$days.' days')->format('Y-m-d H:i:s');$this->pdo->prepare('UPDATE players SET vacation_until=? WHERE id=?')->execute([$until,$playerId]);$this->pdo->prepare('INSERT INTO protection_states(player_id,vacation_until) VALUES(?,?) ON DUPLICATE KEY UPDATE vacation_until=VALUES(vacation_until)')->execute([$playerId,$until]);$this->event($playerId,'vacation_enabled',['until'=>$until]);}
    public function refreshRanking():void{$this->pdo->exec('INSERT INTO rankings(player_id,overall_score,military_score,economy_score,covert_score) SELECT p.id,(r.attack_units+r.defense_units+r.unit_production*100+r.naquadah DIV 1000),(r.attack_units+r.defense_units),((r.naquadah+r.banked_naquadah) DIV 1000),(r.spies+r.anti_spies) FROM players p JOIN player_resources r ON r.player_id=p.id ON DUPLICATE KEY UPDATE overall_score=VALUES(overall_score),military_score=VALUES(military_score),economy_score=VALUES(economy_score),covert_score=VALUES(covert_score)');$this->pdo->exec('UPDATE rankings r JOIN (SELECT player_id,ROW_NUMBER() OVER(ORDER BY overall_score DESC) pos FROM rankings) x ON x.player_id=r.player_id SET r.rank_position=x.pos');}
    public function ascend(int $playerId,string $ascendedRace):void{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT glory,reputation,ascension_count FROM players WHERE id=? FOR UPDATE');$s->execute([$playerId]);$p=$s->fetch();if(!$p||$p['glory']<1000||$p['reputation']<500)throw new RuntimeException('Ascension requirements not met');$this->pdo->prepare('INSERT INTO ascensions(player_id,ascended_race,glory_spent,reputation_spent) VALUES(?,?,1000,500)')->execute([$playerId,$ascendedRace]);$this->pdo->prepare('UPDATE players SET glory=glory-1000,reputation=reputation-500,ascension_count=ascension_count+1,rank_level=3,rank_name="Commander" WHERE id=?')->execute([$playerId]);$this->event($playerId,'ascended',['race'=>$ascendedRace]);$this->pdo->commit();}catch(Throwable $e){$this->pdo->rollBack();throw $e;}}
    public function listGalaxies():array{return $this->pdo->query('SELECT * FROM universe_galaxies WHERE is_active=1 ORDER BY galaxy_number')->fetchAll(PDO::FETCH_ASSOC);}
    public function listSectors(int $galaxyId):array{$s=$this->pdo->prepare('SELECT * FROM universe_sectors WHERE galaxy_id=? AND is_active=1 ORDER BY sector_number');$s->execute([$galaxyId]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    public function listSystems(int $sectorId):array{$s=$this->pdo->prepare('SELECT * FROM universe_solar_systems WHERE sector_id=? AND is_discovered=1 ORDER BY system_number');$s->execute([$sectorId]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    public function getSystemMap(int $systemId):array{$s=$this->pdo->prepare('SELECT ss.*,s.sector_number,s.name sector_name,g.galaxy_number,g.name galaxy_name FROM universe_solar_systems ss JOIN universe_sectors s ON s.id=ss.sector_id JOIN universe_galaxies g ON g.id=s.galaxy_id WHERE ss.id=?');$s->execute([$systemId]);$system=$s->fetch(PDO::FETCH_ASSOC);if(!$system)throw new RuntimeException('Solar system not found');$p=$this->pdo->prepare('SELECT p.*,COUNT(m.id) moon_count FROM universe_planets p LEFT JOIN universe_moons m ON m.planet_id=p.id WHERE p.solar_system_id=? GROUP BY p.id ORDER BY p.orbit_position');$p->execute([$systemId]);$system['planets']=$p->fetchAll(PDO::FETCH_ASSOC);return $system;}
    public function getPlanetDetails(int $planetId):array{$s=$this->pdo->prepare('SELECT p.*,ss.system_number,ss.name system_name,s.sector_number,g.galaxy_number FROM universe_planets p JOIN universe_solar_systems ss ON ss.id=p.solar_system_id JOIN universe_sectors s ON s.id=ss.sector_id JOIN universe_galaxies g ON g.id=s.galaxy_id WHERE p.id=?');$s->execute([$planetId]);$planet=$s->fetch(PDO::FETCH_ASSOC);if(!$planet)throw new RuntimeException('Planet not found');$m=$this->pdo->prepare('SELECT * FROM universe_moons WHERE planet_id=? ORDER BY orbit_position');$m->execute([$planetId]);$planet['moons']=$m->fetchAll(PDO::FETCH_ASSOC);return $planet;}
    public function getMoonDetails(int $moonId):array{$s=$this->pdo->prepare('SELECT m.*,p.name planet_name,p.coordinate_label,ss.name system_name,g.galaxy_number,s.sector_number FROM universe_moons m JOIN universe_planets p ON p.id=m.planet_id JOIN universe_solar_systems ss ON ss.id=p.solar_system_id JOIN universe_sectors s ON s.id=ss.sector_id JOIN universe_galaxies g ON g.id=s.galaxy_id WHERE m.id=?');$s->execute([$moonId]);$moon=$s->fetch(PDO::FETCH_ASSOC);if(!$moon)throw new RuntimeException('Moon not found');return $moon;}
    public function colonizePlanet(int $playerId,int $planetId,string $colonyName):int{$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT * FROM universe_planets WHERE id=? AND is_colonizable=1 AND is_occupied=0 FOR UPDATE');$s->execute([$planetId]);$planet=$s->fetch(PDO::FETCH_ASSOC);if(!$planet)throw new RuntimeException('Planet is unavailable for colonization');$s=$this->pdo->prepare('SELECT id FROM player_colonies WHERE player_id=? AND planet_id=?');$s->execute([$playerId,$planetId]);if($s->fetch())throw new RuntimeException('Colony already established');$this->pdo->prepare('INSERT INTO player_colonies(player_id,planet_id,colony_name,is_homeworld,population,food,water,morale) VALUES(?,?,?,0,100,1000,1000,1.000)')->execute([$playerId,$planetId,trim($colonyName)?:$planet['name']]);$id=(int)$this->pdo->lastInsertId();$this->pdo->prepare('UPDATE universe_planets SET is_occupied=1 WHERE id=?')->execute([$planetId]);$this->event($playerId,'planet_colonized',['planet_id'=>$planetId,'colony_id'=>$id,'coordinate'=>$planet['coordinate_label']]);$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
}
?>
